// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createToken = `-- name: CreateToken :exec
insert into refresh_tokens(
user_id,
token,
created_at,
updated_at,
expires_at,
revoked_at
)
values (
    $1,
    $2,
    now(),
    now(),
    $3,
    null
)
`

type CreateTokenParams struct {
	UserID    string
	Token     string
	ExpiresAt time.Time
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.ExecContext(ctx, createToken, arg.UserID, arg.Token, arg.ExpiresAt)
	return err
}

const readToken = `-- name: ReadToken :one
select id, user_id, token, created_at, updated_at, expires_at, revoked_at
from refresh_tokens
where
user_id = $1
`

func (q *Queries) ReadToken(ctx context.Context, userID string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, readToken, userID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateToken = `-- name: UpdateToken :exec
update refresh_tokens
set
token = $2,
created_at = now(),
updated_at = now(),
expires_at = $3,
revoked_at = $4
where
user_id = $1
`

type UpdateTokenParams struct {
	UserID    string
	Token     string
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

func (q *Queries) UpdateToken(ctx context.Context, arg UpdateTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateToken,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
		arg.RevokedAt,
	)
	return err
}
