// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const readToken = `-- name: ReadToken :one
select id, user_id, token, created_at, updated_at, expires_at, revoked_at
from refresh_tokens
where
user_id = $1
`

func (q *Queries) ReadToken(ctx context.Context, userID string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, readToken, userID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const upsertToken = `-- name: UpsertToken :one
insert into refresh_tokens (
    user_id,
    token,
    created_at,
    updated_at,
    expires_at,
    revoked_at
) values (
    $1,
    $2,
    now(),
    now(),
    $3,
    $4
)
on conflict (user_id) 
do update set
    token = excluded.token,
    created_at = now(),
    updated_at = now(),
    expires_at = excluded.expires_at,
    revoked_at = excluded.revoked_at
returning id, user_id, token, created_at, updated_at, expires_at, revoked_at
`

type UpsertTokenParams struct {
	UserID    string
	Token     string
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

func (q *Queries) UpsertToken(ctx context.Context, arg UpsertTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, upsertToken,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
		arg.RevokedAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
