// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getTokenByUserID = `-- name: GetTokenByUserID :one
select token
from refresh_tokens
where
user_id = $1 and 
expires_at > now() and
revoked_at is null and 
token is not null
`

func (q *Queries) GetTokenByUserID(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getTokenByUserID, userID)
	var token string
	err := row.Scan(&token)
	return token, err
}

const insertTokenByUserID = `-- name: InsertTokenByUserID :exec
insert into refresh_tokens(
user_id,
token,
created_at,
updated_at,
expires_at,
revoked_at
)
values (
    $1,
    $2,
    now(),
    now(),
    now() + interval '24 hours',
    null
)
`

type InsertTokenByUserIDParams struct {
	UserID uuid.UUID
	Token  string
}

func (q *Queries) InsertTokenByUserID(ctx context.Context, arg InsertTokenByUserIDParams) error {
	_, err := q.db.ExecContext(ctx, insertTokenByUserID, arg.UserID, arg.Token)
	return err
}

const updateTokenByUserID = `-- name: UpdateTokenByUserID :exec
update refresh_tokens
set
token = $2,
updated_at = now()
where
user_id = $1 and
expires_at > now() and
revoked_at is null
`

type UpdateTokenByUserIDParams struct {
	UserID uuid.UUID
	Token  string
}

func (q *Queries) UpdateTokenByUserID(ctx context.Context, arg UpdateTokenByUserIDParams) error {
	_, err := q.db.ExecContext(ctx, updateTokenByUserID, arg.UserID, arg.Token)
	return err
}
