services:
  suproxy:
    image: gitlab.dit.htwk-leipzig.de:5050/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/suproxy:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - default

  autotester:
    image: gitlab.dit.htwk-leipzig.de:5050/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/autotester:latest
    restart: always
    ports:
      - "8079:8081"
    networks:
      - default

  frontend-mock:
    image: gitlab.dit.htwk-leipzig.de:5050/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/frontend-mock
    networks:
      - default
    ports:
      - "8082:8082"
    environment:
      - SUPPLIER_URL=http://suproxy:8080
      - API_URL=http://frontend-mock:8082
      - NODE_ENV=production

  supplier-mock:
    image: gitlab.dit.htwk-leipzig.de:5050/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/supplier-mock
    networks:
      - default
    ports:
      - "8083:8083"

  nginx:
    image: nginx:alpine
    restart: always
    networks:
      - default
    ports:
      - "8081:8081"
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - autotester