services:
  suproxy:
    image: gitlab.dit.htwk-leipzig.de:5050/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/suproxy:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - default
    environment:
      - DD_AGENT_HOST=datadog
      - DD_TRACE_AGENT_PORT=8126
      - DD_DOGSTATSD_PORT=8125
      - DD_SITE=us5.datadoghq.com

  autotester:
    image: gitlab.dit.htwk-leipzig.de:5050/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/autotester:latest
    restart: always
    volumes:
      - /run/user/1001/podman/podman.sock:/var/run/docker.sock
      - /tmp/smart/logs/:/tmp/smart/logs/
      - /tmp/tests:/tmp/tests
    ports:
      - "8079:8081"
    networks:
      - default
    environment:
      - DD_AGENT_HOST=datadog
      - DD_TRACE_AGENT_PORT=8126
      - DD_SITE=us5.datadoghq.com

  autotester-mcp:
    image: gitlab.dit.htwk-leipzig.de:5050/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/autotester-mcp:latest
    restart: always
    ports:
      - "8084:8084"
    networks:
      - default
    environment:
      - AUTOTESTER_BASE_URL=http://autotester:8081
      - DD_AGENT_HOST=datadog
      - DD_TRACE_AGENT_PORT=8126
      - DD_SITE=us5.datadoghq.com

  frontend-mock:
    image: gitlab.dit.htwk-leipzig.de:5050/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/frontend-mock
    networks:
      - default
    ports:
      - "8082:8082"
    environment:
      - SUPPLIER_URL=http://supplier-mock:8083/api/v1
      - API_URL=http://suproxy:8080/api/v1
      - NODE_ENV=production

  supplier-mock:
    image: gitlab.dit.htwk-leipzig.de:5050/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/supplier-mock
    networks:
      - default
    ports:
      - "8083:8083"

  redis:
    image: valkey/valkey:alpine
    restart: always
    networks:
      - default
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    restart: always
    networks:
      - default
    ports:
      - "8081:8081"
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - autotester
      - postgres

  postgres:
    image: postgres:17-alpine
    depends_on:
      - autotester
    networks:
      - default
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=smart

  datadog:
    image: datadog/agent:latest
    networks:
      - default
    ports:
      - "127.0.0.1:8126:8126/tcp"
      - "127.0.0.1:8125:8125/udp"
    env_file: .env
    volumes:
      - /var/run/user/1001/podman/podman.sock:/var/run/docker.sock:ro
      - /var/run/datadog:/var/run/datadog
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
    environment:
      - DD_HOSTNAME=prod-container
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_USE_DOGSTATSD=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_SITE=us5.datadoghq.com
      - DD_APM_RECEIVER_SOCKET=/var/run/datadog/apm.socket
      - DD_DOGSTATSD_SOCKET=/var/run/datadog/dsd.socket
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_AUTO_MULTI_LINE_DETECTION=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE_LOGS="name:dd-agent"
