name: mcp-tools-config
version: 1.0.0
schema: v1
models:
  - name: GPT-4o
    provider: openai
    model: gpt-4o
    roles:
      - chat
      - edit
      - apply
    defaultCompletionOptions:
      maxTokens: 1500

  - name: Claude-v1
    provider: anthropic
    model: claude-v1
    roles:
      - chat
      - edit
    defaultCompletionOptions:
      maxTokens: 2000
context:
  provider: web
mcpServers:
  - name: check24-smart-mcp
    command: go run ../../../cmd/mcp-server/main.go