stages:
  - testing

variables:
  GO_VERSION: '1.24'

default:
  image: 'golang:$GO_VERSION'

lint:
  stage: testing
  script:
    - ./bin/task lint

unit_test:
  stage: testing
  script:
    - ./bin/task test
