stages:
  - prepare
  - testing

variables:
  GO_VERSION: '1.24'

default:
  image: 'golang:$GO_VERSION'

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
        - .go/pkg/mod/

lint:
  stage: testing
  extends:
    - .go-cache

  script:
    - ./bin/task lint

unit_test:
  stage: testing
  extends:
    - .go-cache
  script:
    - ./bin/task test
