stages:
  - prepare
  - code_analysis_and_testing
  - build
  - deploy

variables:
  GO_VERSION: 1.24

default:
  image: golang:$GO_VERSION

.go_cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  rules:
    - if: $GITLAB_CI == "false"
      when: never
    - when: on_success
  cache:
    key: $CI_COMMIT_REF_SLUG
    fallback_keys:
      - $CI_DEFAULT_BRANCH
    paths:
      - .go/pkg/mod/

go_mod_download:
  stage: prepare
  extends: .go_cache
  script:
    - ./bin/task setup

lint_go:
  stage: code_analysis_and_testing
  extends: .go_cache
  script:
    - ./bin/task lint

static_analysis_go:
  stage: code_analysis_and_testing
  extends: .go_cache
  script:
    - ./bin/task static-analysis
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success

unit_test_go:
  stage: code_analysis_and_testing
  extends: .go_cache
  script:
    - ./bin/task test

build_go_artifacts:
  stage: build
  extends: .go_cache
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success
  script:
    - ./bin/task build-pipeline
  artifacts:
    name: Go_Bin
    paths:
      - build/

build_go_no_artifacts:
  stage: build
  extends: .go_cache
  rules:
    - if: $CI_COMMIT_BRANCH != "main"
      when: on_success
  script:
    - ./bin/task build-pipeline
