sonar.projectKey=projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends_smart_AZfLYHmo3uP5ldjpcn-B
sonar.qualitygate.wait=true
sonar.exclusions=**/vendor/**,**/*_test.go,**/mocks/**,**/tests/**

# CSS Rules - Exclude framework-specific at-rules
sonar.css.rules.excluded=css:S4670

sonar.tests.inclusions=**/*_test.go,**/*.test.ts
sonar.go.coverage.reportPaths=coverage.out
sonar.javascript.lcov.reportPaths=web/coverage/lcov.info
