version: "3"

includes:
  local: ./Taskfile_{{OS}}.yml

env:
  GOPRIVATE: "gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart"
  LPATH: "{{.BIN_PATH}}:{{.PATH}}"

vars:
  VERSION: '{{now | date "15-04-05"}}-debug'

tasks:
  setup:
    desc: "Setup the project"
    cmds:
      - git config core.hooksPath githooks
      - go mod download

  build:
    desc: "Build the project"
    cmds:
      - cmd: go build -o bin/suproxy -ldflags "-X 'main.Version={{.VERSION}}'" cmd/suproxy/main.go
        platforms: [linux, darwin]
      - cmd: go build -o bin/autotester -ldflags "-X 'main.Version={{.VERSION}}'" cmd/autotester/main.go
        platforms: [linux, darwin]
      - cmd: go build -o bin/suproxy.exe -ldflags "-X 'main.Version={{.VERSION}}'" cmd/suproxy/main.go
        platforms: [windows/amd64]
      - cmd: go build -o bin/autotester.exe -ldflags "-X 'main.Version={{.VERSION}}'" cmd/autotester/main.go
        platforms: [windows/amd64]

  build-pipeline:
    desc: "Use in build job of pipeline to make production build binaries"
    vars:
      BUILD_BRANCH:
        sh: git rev-parse --abbrev-ref HEAD
      BUILD_DATE:
        sh: date +"%Y-%m-%d-%H:%M:%S"
      VERSION: '{{.BUILD_BRANCH}}-{{.BUILD_DATE}}'
    cmds:
      - echo {{.VERSION}}
      - CGO_ENABLED=0 go build -o build/suproxy -ldflags "-s -w -X 'main.Version={{.VERSION}}'" cmd/suproxy/main.go
      - CGO_ENABLED=0 go build -o build/autotester -ldflags "-s -w -X 'main.Version={{.VERSION}}'" cmd/autotester/main.go

  run-suproxy:
    desc: "Run the project"
    cmds:
      - go run cmd/suproxy/main.go

  run-autotester:
    desc: "Run the project"
    cmds:
      - go run cmd/autotester/main.go

  test:
    desc: "Run the tests"
    cmds:
      - go test -v ./...

  lint:
    desc: "Run the lint"
    cmds:
      - go tool golangci-lint run --max-issues-per-linter=0 --max-same-issues=0 --timeout=10m
    ignore_error: false

  static-analysis:
    desc: "Run static code analysis tools like gosec and staticcheck"
    vars:
      GOVERSION:
        sh: echo "go$(grep '^go ' go.mod | awk '{print $2}')"
      EXCLUDE_LIST: 'G104,G107'
    cmds:
      - go tool staticcheck -tests=false ./...
      - GOSECGOVERSION={{.GOVERSION}} go tool gosec -exclude={{.EXCLUDE_LIST}} -confidence medium -severity medium -nosec -exclude-generated -sort ./...
  pre-commit:
    desc: "Run the pre-commit"
    cmds:
      - task: lint
      - task: test



