version: "3"

includes:
  local: ./Taskfile_{{OS}}.yml

env:
  GOPRIVATE: "gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart"
  LPATH: "{{.BIN_PATH}}:{{.PATH}}"

vars:
  VERSION: '{{now | date "15-04-05"}}-debug'
  MODULE_NAME: "gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart"
  OPENAI_KEY_VAR: "{{.MODULE_NAME}}/internal/build.OpenAIKey"
  AWS_ACCESS_KEY_VAR: "{{.MODULE_NAME}}/internal/build.AwsAccessKey"
  AWS_SECRET_ACCESS_KEY_VAR: "{{.MODULE_NAME}}/internal/build.AwsSecretAccessKey"
  VERSION_VAR: "{{.MODULE_NAME}}/internal/build.Version"

tasks:
  setup:
    desc: "Setup the project"
    cmds:
      - git config core.hooksPath githooks
      - go mod tidy
      - PATH=$LPATH; doppler login
      - PATH=$LPATH; doppler setup -c dev -p htwk-projekt

  build:
    desc: "Build the project"
    deps: [generate]
    vars:
      OPENAI_KEY:
        sh: "{{.BIN_PATH}}/doppler secrets get OPENAI_KEY --plain"
      AWS_ACCESS_KEY:
        sh: "{{.BIN_PATH}}/doppler secrets get AWS_ACCESS_KEY_ID --plain"
      AWS_SECRET_ACCESS_KEY:
        sh: "{{.BIN_PATH}}/doppler secrets get AWS_SECRET_ACCESS_KEY --plain"
    cmds:
      - echo "building suproxy with version {{.VERSION}}"
      - cmd: go build -o bin/suproxy -ldflags "-X '{{.VERSION_VAR}}={{.VERSION}}' -X '{{.OPENAI_KEY_VAR}}={{.OPENAI_KEY}}' -X '{{.AWS_ACCESS_KEY_VAR}}={{.AWS_ACCESS_KEY}}' -X '{{.AWS_SECRET_ACCESS_KEY_VAR}}={{.AWS_SECRET_ACCESS_KEY}}'" cmd/suproxy/main.go
        platforms: [linux, darwin]
      - echo "building autotester with version {{.VERSION}}"
      - cmd: go build -o bin/autotester -ldflags "-X '{{.VERSION_VAR}}={{.VERSION}}' -X '{{.OPENAI_KEY_VAR}}={{.OPENAI_KEY}}' -X '{{.AWS_ACCESS_KEY_VAR}}={{.AWS_ACCESS_KEY}}' -X '{{.AWS_SECRET_ACCESS_KEY_VAR}}={{.AWS_SECRET_ACCESS_KEY}}'" cmd/autotester/main.go
        platforms: [linux, darwin]
      - echo "building suproxy.exe with version {{.VERSION}}"
      - cmd: go build -o bin/suproxy.exe -ldflags "-X '{{.VERSION_VAR}}={{.VERSION}}' -X '{{.OPENAI_KEY_VAR}}={{.OPENAI_KEY}}' -X '{{.AWS_ACCESS_KEY_VAR}}={{.AWS_ACCESS_KEY}}' -X '{{.AWS_SECRET_ACCESS_KEY_VAR}}={{.AWS_SECRET_ACCESS_KEY}}'" cmd/suproxy/main.go
        platforms: [windows/amd64]
      - echo "building autotester.exe with version {{.VERSION}}"
      - cmd: go build -o bin/autotester.exe -ldflags "-X '{{.VERSION_VAR}}={{.VERSION}}' -X '{{.OPENAI_KEY_VAR}}={{.OPENAI_KEY}}' -X '{{.AWS_ACCESS_KEY_VAR}}={{.AWS_ACCESS_KEY}}' -X '{{.AWS_SECRET_ACCESS_KEY_VAR}}={{.AWS_SECRET_ACCESS_KEY}}'" cmd/autotester/main.go
        platforms: [windows/amd64]
    silent: true
  
  build-frontend:
    cmds:
      - cd web/ && pnpm install
      - task: lint-frontend
      - cd web/ && pnpm run build

  build-pipeline:
    desc: "Use in build job of pipeline to make production build binaries"
    vars:
      BUILD_BRANCH:
        sh: git rev-parse --abbrev-ref HEAD
      BUILD_DATE:
        sh: date +"%Y-%m-%d-%H:%M:%S"
      VERSION: "{{.BUILD_BRANCH}}-{{.BUILD_DATE}}"
      OPENAI_KEY:
        sh: "{{.BIN_PATH}}/doppler secrets get OPENAI_KEY --plain"
      AWS_ACCESS_KEY:
        sh: "{{.BIN_PATH}}/doppler secrets get AWS_ACCESS_KEY_ID --plain"
      AWS_SECRET_ACCESS_KEY:
        sh: "{{.BIN_PATH}}/doppler secrets get AWS_SECRET_ACCESS_KEY --plain"
    cmds:
      - echo "building suproxy with version {{.VERSION}}"
      - CGO_ENABLED=0 "{{.BIN_PATH}}/doppler" run -- go build -o build/suproxy -ldflags "-s -w -X '{{.VERSION_VAR}}={{.VERSION}}' -X '{{.OPENAI_KEY_VAR}}={{.OPENAI_KEY}}' -X '{{.AWS_ACCESS_KEY_VAR}}={{.AWS_ACCESS_KEY}}' -X '{{.AWS_SECRET_ACCESS_KEY_VAR}}={{.AWS_SECRET_ACCESS_KEY}}'" cmd/suproxy/main.go
      - echo "building autotester with version {{.VERSION}}"
      - CGO_ENABLED=0 "{{.BIN_PATH}}/doppler" run -- go build -o build/autotester -ldflags "-s -w -X '{{.VERSION_VAR}}={{.VERSION}}' -X '{{.OPENAI_KEY_VAR}}={{.OPENAI_KEY}}' -X '{{.AWS_ACCESS_KEY_VAR}}={{.AWS_ACCESS_KEY}}' -X '{{.AWS_SECRET_ACCESS_KEY_VAR}}={{.AWS_SECRET_ACCESS_KEY}}'" cmd/autotester/main.go
    silent: true

  run-suproxy:
    desc: "Run the project"
    deps: [generate-config-suproxy,generate-mocks]
    env:
      APP_CMD: "./cmd/suproxy"
      OPENAI_KEY_VAR: "{{.OPENAI_KEY_VAR}}"
      VERSION_VAR: "{{.VERSION_VAR}}"
      AWS_ACCESS_KEY:
        sh: "{{.BIN_PATH}}/doppler secrets get AWS_ACCESS_KEY_ID --plain"
      AWS_SECRET_ACCESS_KEY:
        sh: "{{.BIN_PATH}}/doppler secrets get AWS_SECRET_ACCESS_KEY --plain"
    cmds:
      - "PATH=$LPATH; doppler run -- go tool air"

  run-autotester:
    desc: "Run the project"
    deps: [generate-config-autotester,generate-mocks]
    env:
      APP_CMD: "./cmd/autotester"
      OPENAI_KEY_VAR: "{{.OPENAI_KEY_VAR}}"
      VERSION_VAR: "{{.VERSION_VAR}}"
      AWS_ACCESS_KEY:
        sh: "{{.BIN_PATH}}/doppler secrets get AWS_ACCESS_KEY_ID --plain"
      AWS_SECRET_ACCESS_KEY:
        sh: "{{.BIN_PATH}}/doppler secrets get AWS_SECRET_ACCESS_KEY --plain"
    cmds:
      - 'PATH=$LPATH; doppler run -- go tool air'

  compose-local:
    desc: "Run the whole project in docker-compose for local environment"
    dir: 'deployments'
    cmds:
      - docker compose -f compose.dev.yml up -d

  compose-local-down:
    desc: "Stop all the containers in local environment"
    dir: 'deployments'
    cmds:
      - docker compose -f compose.dev.yml down

  test:
    desc: "Run the tests"
    cmds:
      - go tool gotestsum ./...

  test-integration:
    desc: "Run the integration tests"
    cmds:
      - go tool gotestsum -- -tags=integration ./...

  test-integration-coverage:
    desc: "Run the integration tests with coverage"
    cmds:
      - go tool gotestsum -- -tags=integration -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out

  lint:
    desc: "Run the lint"
    cmds:
      - go tool golangci-lint run --max-issues-per-linter=0 --max-same-issues=0 --timeout=10m
    ignore_error: false

  static-analysis:
    desc: "Run static code analysis tools like gosec and staticcheck"
    vars:
      GOVERSION:
        sh: echo "go$(grep '^go ' go.mod | awk '{print $2}')"
      EXCLUDE_RULES: "G104,G107"
    cmds:
      - go tool staticcheck -tests=false ./cmd/... ./internal/...
      - GOSECGOVERSION={{.GOVERSION}} go tool gosec -exclude-dir="internal/shared/lib/assert" -exclude={{.EXCLUDE_RULES}} -confidence medium -severity medium -nosec -exclude-generated -sort ./cmd/... ./internal/...

  lint-frontend:
    desc: "Run the frontend lint"
    cmds:
      - cd web/ && pnpm eslint .  

  format-frontend:
    desc: "Run the frontend formatter"
    cmds:
      - cd web/ && pnpm prettier --write .

  pre-commit:
    desc: "Run the pre-commit"
    deps: [generate]
    cmds:
      - task: lint
      - task: test

  generate:
    desc: "generate code"
    cmds:
      - task: generate-config-autotester
      - task: generate-config-suproxy
      - task: generate-mocks

  generate-config-autotester:
    desc: "generate code for reading autotester config"
    cmds:
      - PATH=$LPATH; go tool github.com/apple/pkl-go/cmd/pkl-gen-go configs/autotester.pkl
    sources:
      - configs/autotester.pkl
    generates:
      - internal/autotester/domain/config/*
    method: timestamp

  generate-config-suproxy:
    desc: "generate code for reading suproxy config"
    cmds:
      - PATH=$LPATH; go tool github.com/apple/pkl-go/cmd/pkl-gen-go configs/suproxy.pkl
    sources:
      - configs/suproxy.pkl
    generates:
      - internal/suproxy/domain/config/*
    method: timestamp

  generate-mocks:
    desc: "generate all mockery mocks"
    cmds:
      - "go tool github.com/vektra/mockery/v3"

