version: "3"

includes:
  local: ./Taskfile_{{OS}}.yml

env:
  GOPRIVATE: "gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart"
  LPATH: "{{.BIN_PATH}}:{{.PATH}}"

vars:
  VERSION: '{{now | date "15-04-05"}}-debug'
  MODULE_NAME: "gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart"
  OPENAI_KEY_VAR: "{{.MODULE_NAME}}/internal/build.OpenAIKey"
  AWS_ACCESS_KEY_VAR: "{{.MODULE_NAME}}/internal/build.AwsAccessKey"
  AWS_SECRET_ACCESS_KEY_VAR: "{{.MODULE_NAME}}/internal/build.AwsSecretAccessKey"
  VERSION_VAR: "{{.MODULE_NAME}}/internal/build.Version"
  TESTCOVERAGE_THRESHOLD: 60

tasks:
  # --------------------------------------------------------------------------------
  # Setup
  # --------------------------------------------------------------------------------
  setup:
    desc: "Setup the project"
    cmds:
      - git config core.hooksPath githooks
      - go mod tidy
      - PATH=$LPATH; doppler login
      - PATH=$LPATH; doppler setup -c dev -p htwk-projekt

  # --------------------------------------------------------------------------------
  # Build
  # --------------------------------------------------------------------------------
  clean:
    desc: "Remove build artifacts"
    cmds:
      - rm -rf build
      - find . -name "coverage.out" -delete

  build:
    desc: "Build the project"
    deps: [generate]
    vars:
      OPENAI_KEY:
        sh: "{{.BIN_PATH}}/doppler secrets get OPENAI_KEY --plain"
      AWS_ACCESS_KEY:
        sh: "{{.BIN_PATH}}/doppler secrets get AWS_ACCESS_KEY_ID --plain"
      AWS_SECRET_ACCESS_KEY:
        sh: "{{.BIN_PATH}}/doppler secrets get AWS_SECRET_ACCESS_KEY --plain"
      BASE_LDFLAGS: "-X '{{.VERSION_VAR}}={{.VERSION}}' -X '{{.OPENAI_KEY_VAR}}={{.OPENAI_KEY}}' -X '{{.AWS_ACCESS_KEY_VAR}}={{.AWS_ACCESS_KEY}}' -X '{{.AWS_SECRET_ACCESS_KEY_VAR}}={{.AWS_SECRET_ACCESS_KEY}}'"
    cmds:
      - echo "building suproxy with version {{.VERSION}}"
      - cmd: go build -o build/suproxy -ldflags "{{.BASE_LDFLAGS}}" ./cmd/suproxy/
        platforms: [linux, darwin]
      - echo "building autotester with version {{.VERSION}}"
      - cmd: go build -o build/autotester -ldflags "{{.BASE_LDFLAGS}}" ./cmd/autotester/
        platforms: [linux, darwin]
      - echo "building suproxy.exe with version {{.VERSION}}"
      - cmd: go build -o build/suproxy.exe -ldflags "{{.BASE_LDFLAGS}}" ./cmd/suproxy/
        platforms: [windows/amd64]
      - echo "building autotester.exe with version {{.VERSION}}"
      - cmd: go build -o build/autotester.exe -ldflags "{{.BASE_LDFLAGS}}" ./cmd/autotester/
        platforms: [windows/amd64]
    silent: true
  
  install-frontend-deps:
    desc: "Install frontend dependencies"
    dir: web
    cmds:
      - pnpm install
    sources:
      - pnpm-lock.yaml
    generates:
      - node_modules

  build-frontend:
    dir: web
    deps: [install-frontend-deps]
    cmds:
      - task: lint-frontend
      - pnpm run build
    sources:
      - "*"
      - "src/**/*"

  build-frontend-dev:
    desc: "Build the frontend"
    dir: "web"
    deps: [install-frontend-deps]
    cmds:
      - pnpm build
    sources:
      - "*"
      - "src/**/*"

  build-pipeline:
    desc: "Use in build job of pipeline to make production build binaries"
    vars:
      BUILD_BRANCH:
        sh: git rev-parse --abbrev-ref HEAD
      BUILD_DATE:
        sh: date +"%Y-%m-%d-%H:%M:%S"
      VERSION: "{{.BUILD_BRANCH}}-{{.BUILD_DATE}}"
      OPENAI_KEY:
        sh: "{{.BIN_PATH}}/doppler secrets get OPENAI_KEY --plain"
      AWS_ACCESS_KEY:
        sh: "{{.BIN_PATH}}/doppler secrets get AWS_ACCESS_KEY_ID --plain"
      AWS_SECRET_ACCESS_KEY:
        sh: "{{.BIN_PATH}}/doppler secrets get AWS_SECRET_ACCESS_KEY --plain"
      BASE_LDFLAGS: "-X '{{.VERSION_VAR}}={{.VERSION}}' -X '{{.OPENAI_KEY_VAR}}={{.OPENAI_KEY}}' -X '{{.AWS_ACCESS_KEY_VAR}}={{.AWS_ACCESS_KEY}}' -X '{{.AWS_SECRET_ACCESS_KEY_VAR}}={{.AWS_SECRET_ACCESS_KEY}}'"
      PROD_LDFLAGS: "-s -w {{.BASE_LDFLAGS}}"
    cmds:
      - echo "building suproxy with version {{.VERSION}}"
      - CGO_ENABLED=0 go build -o build/suproxy -ldflags "{{.PROD_LDFLAGS}}" ./cmd/suproxy/
      - echo "building autotester with version {{.VERSION}}"
      - CGO_ENABLED=0 go build -o build/autotester -ldflags "{{.PROD_LDFLAGS}}" ./cmd/autotester/
    silent: true

  # --------------------------------------------------------------------------------
  # Local Development
  # --------------------------------------------------------------------------------
  .run-app:
    internal: true
    env:
      APP_CMD: "./cmd/{{.APP_NAME}}"
      OPENAI_KEY_VAR: "{{.OPENAI_KEY_VAR}}"
      VERSION_VAR: "{{.VERSION_VAR}}"
    cmds:
      - "PATH=$LPATH; doppler run -- go tool air"

  run-suproxy:
    desc: "Run the suproxy service"
    cmds:
      - task: .run-app
        vars:
          APP_NAME: suproxy

  run-autotester:
    desc: "Run the autotester service"
    deps: [build-frontend-dev]
    cmds:
      - task: .run-app
        vars:
          APP_NAME: autotester

  compose-local:
    desc: "Run the whole project in docker-compose for local environment"
    dir: 'deployments'
    cmds:
      - docker login gitlab.dit.htwk-leipzig.de:5050
      - docker compose -f compose.dev.yml up -d

  compose-local-down:
    desc: "Stop all the containers in local environment"
    dir: 'deployments'
    cmds:
      - docker compose -f compose.dev.yml down

  # --------------------------------------------------------------------------------
  # Testing
  # --------------------------------------------------------------------------------
  test:
    desc: "Run the tests"
    cmds:
      - go tool gotestsum ./...
  
  test-coverage:
    desc: "Run the tests with coverage"
    cmds:
      - go tool gotestsum -- -coverprofile=coverage.out ./...

  test-ci:
    desc: "Run the tests with coverage"
    cmds:
      - echo "Running unit tests with coverage"
      - go tool gotestsum --junitfile junit.xml -- -tags=integration -coverprofile=coverage.out -covermode=count $(go list ./... | grep -Ev 'config|build|deployments|cmd|mocks')
      - go tool cover -func=coverage.out
      - go tool gocoverageplus --input=coverage.out -o go-cobertura-coverage.xml -v
      - echo "Quality Gate checking test coverage is above threshold"
      - echo "Threshold {{.TESTCOVERAGE_THRESHOLD}} %"
      - ./scripts/check-coverage.sh {{.TESTCOVERAGE_THRESHOLD}} coverage.out
    silent: true

  test-integration:
    desc: "Run the integration tests"
    cmds:
      - go tool gotestsum -- -tags=integration ./...

  test-integration-coverage:
    desc: "Run the integration tests with coverage"
    cmds:
      - go tool gotestsum -- -tags=integration -- -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out

  test-frontend:
    desc: "Run the frontend tests"
    dir: "web"
    deps: [install-frontend-deps]
    cmds:
      - pnpm test

  test-sysprompt:
    desc: "run the test script for testing the current sysprompts against the given testcases"
    dir: "scripts"
    cmds:
    - ./sysprompt-test.sh

  # --------------------------------------------------------------------------------
  # Code Quality & Linting
  # --------------------------------------------------------------------------------
  lint:
    desc: "Run the lint"
    cmds:
      - go tool golangci-lint run --max-issues-per-linter=0 --max-same-issues=0 --timeout=10m
    ignore_error: false

  static-analysis:
    desc: "Run static code analysis tools like gosec and staticcheck"
    vars:
      GOVERSION:
        sh: echo "go$(grep '^go ' go.mod | awk '{print $2}')"
      EXCLUDE_RULES: "G104,G107"
    cmds:
      - go tool staticcheck -tests=false ./cmd/... ./internal/...
      - GOSECGOVERSION={{.GOVERSION}} go tool gosec -exclude-dir="cmd/internal" -exclude={{.EXCLUDE_RULES}} -confidence medium -severity medium -nosec -exclude-generated -sort ./cmd/... ./internal/...

  lint-frontend:
    desc: "Run the frontend lint"
    dir: web
    deps: [install-frontend-deps]
    cmds:
      - pnpm eslint .

  format-frontend:
    desc: "Run the frontend formatter"
    dir: web
    deps: [install-frontend-deps]
    cmds:
      - pnpm prettier --write .

  # --------------------------------------------------------------------------------
  # Git Hooks
  # --------------------------------------------------------------------------------
  pre-commit:
    desc: "Run the pre-commit"
    deps: [generate]
    cmds:
      - task: lint
      - task: test

  # --------------------------------------------------------------------------------
  # Code Generation
  # --------------------------------------------------------------------------------
  generate:
    desc: "generate code"
    cmds:
      - task: generate-config-autotester
      - task: generate-config-suproxy
      - task: generate-config-embedded
      - task: di-generate-autotester
      - task: di-generate-suproxy

  generate-config-autotester:
    desc: "generate code for reading autotester config"
    cmds:
      - PATH=$LPATH; go tool pkl-gen-go configs/autotester.pkl
    sources:
      - configs/autotester.pkl

  generate-config-suproxy:
    desc: "generate code for reading suproxy config"
    cmds:
      - PATH=$LPATH; go tool pkl-gen-go configs/suproxy.pkl
    sources:
      - configs/suproxy.pkl

  generate-mocks:
    desc: "generate all mockery mocks"
    cmds:
      - "go tool mockery"

  generate-config-embedded:
    desc: "generates the config in a binary format to use for embedding in compile time"
    cmds:
      - PATH=$LPATH; go run cmd/internal/generate-pkl-data/main.go
    sources:
    - configs/suproxy.pkl
    - configs/autotester.pkl
  
  di-generate-autotester:
    desc: "generate dependency injection code for autotester"
    cmds:
      - go tool wire ./cmd/autotester
    sources:
      - cmd/autotester/wire.go

  di-generate-suproxy:
    desc: "generate dependency injection code for suproxy"
    cmds:
      - go tool wire ./cmd/suproxy
    sources:
      - cmd/suproxy/wire.go

  # --------------------------------------------------------------------------------
  # Benchmarking
  # --------------------------------------------------------------------------------
  bench:
    desc: "Run the benchmark"
    cmds:
      - go run cmd/benchmark/main.go

  bench-setup:
    desc: "Setup the benchmark dependencies"
    cmds:
      - go tool playwright install
