// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuth creates a new instance of MockAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuth {
	mock := &MockAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuth is an autogenerated mock type for the Auth type
type MockAuth struct {
	mock.Mock
}

type MockAuth_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuth) EXPECT() *MockAuth_Expecter {
	return &MockAuth_Expecter{mock: &_m.Mock}
}

// GenerateToken provides a mock function for the type MockAuth
func (_mock *MockAuth) GenerateToken(ctx context.Context, userId string) (string, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuth_GenerateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateToken'
type MockAuth_GenerateToken_Call struct {
	*mock.Call
}

// GenerateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
func (_e *MockAuth_Expecter) GenerateToken(ctx interface{}, userId interface{}) *MockAuth_GenerateToken_Call {
	return &MockAuth_GenerateToken_Call{Call: _e.mock.On("GenerateToken", ctx, userId)}
}

func (_c *MockAuth_GenerateToken_Call) Run(run func(ctx context.Context, userId string)) *MockAuth_GenerateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuth_GenerateToken_Call) Return(s string, err error) *MockAuth_GenerateToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuth_GenerateToken_Call) RunAndReturn(run func(ctx context.Context, userId string) (string, error)) *MockAuth_GenerateToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetBearerToken provides a mock function for the type MockAuth
func (_mock *MockAuth) GetBearerToken(headers http.Header) (string, error) {
	ret := _mock.Called(headers)

	if len(ret) == 0 {
		panic("no return value specified for GetBearerToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(http.Header) (string, error)); ok {
		return returnFunc(headers)
	}
	if returnFunc, ok := ret.Get(0).(func(http.Header) string); ok {
		r0 = returnFunc(headers)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(http.Header) error); ok {
		r1 = returnFunc(headers)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuth_GetBearerToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBearerToken'
type MockAuth_GetBearerToken_Call struct {
	*mock.Call
}

// GetBearerToken is a helper method to define mock.On call
//   - headers http.Header
func (_e *MockAuth_Expecter) GetBearerToken(headers interface{}) *MockAuth_GetBearerToken_Call {
	return &MockAuth_GetBearerToken_Call{Call: _e.mock.On("GetBearerToken", headers)}
}

func (_c *MockAuth_GetBearerToken_Call) Run(run func(headers http.Header)) *MockAuth_GetBearerToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.Header
		if args[0] != nil {
			arg0 = args[0].(http.Header)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuth_GetBearerToken_Call) Return(s string, err error) *MockAuth_GetBearerToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuth_GetBearerToken_Call) RunAndReturn(run func(headers http.Header) (string, error)) *MockAuth_GetBearerToken_Call {
	_c.Call.Return(run)
	return _c
}
