// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/autotester/domain/entity"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// LookUp provides a mock function for the type MockCache
func (_mock *MockCache) LookUp(ctx context.Context, chatId string) (*entity.Chat, error) {
	ret := _mock.Called(ctx, chatId)

	if len(ret) == 0 {
		panic("no return value specified for LookUp")
	}

	var r0 *entity.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Chat, error)); ok {
		return returnFunc(ctx, chatId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Chat); ok {
		r0 = returnFunc(ctx, chatId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Chat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, chatId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_LookUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookUp'
type MockCache_LookUp_Call struct {
	*mock.Call
}

// LookUp is a helper method to define mock.On call
//   - ctx context.Context
//   - chatId string
func (_e *MockCache_Expecter) LookUp(ctx interface{}, chatId interface{}) *MockCache_LookUp_Call {
	return &MockCache_LookUp_Call{Call: _e.mock.On("LookUp", ctx, chatId)}
}

func (_c *MockCache_LookUp_Call) Run(run func(ctx context.Context, chatId string)) *MockCache_LookUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_LookUp_Call) Return(chat *entity.Chat, err error) *MockCache_LookUp_Call {
	_c.Call.Return(chat, err)
	return _c
}

func (_c *MockCache_LookUp_Call) RunAndReturn(run func(ctx context.Context, chatId string) (*entity.Chat, error)) *MockCache_LookUp_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type MockCache
func (_mock *MockCache) Store(ctx context.Context, chat *entity.Chat, timeToLive time.Duration) error {
	ret := _mock.Called(ctx, chat, timeToLive)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Chat, time.Duration) error); ok {
		r0 = returnFunc(ctx, chat, timeToLive)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockCache_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - chat *entity.Chat
//   - timeToLive time.Duration
func (_e *MockCache_Expecter) Store(ctx interface{}, chat interface{}, timeToLive interface{}) *MockCache_Store_Call {
	return &MockCache_Store_Call{Call: _e.mock.On("Store", ctx, chat, timeToLive)}
}

func (_c *MockCache_Store_Call) Run(run func(ctx context.Context, chat *entity.Chat, timeToLive time.Duration)) *MockCache_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Chat
		if args[1] != nil {
			arg1 = args[1].(*entity.Chat)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCache_Store_Call) Return(err error) *MockCache_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_Store_Call) RunAndReturn(run func(ctx context.Context, chat *entity.Chat, timeToLive time.Duration) error) *MockCache_Store_Call {
	_c.Call.Return(run)
	return _c
}
