// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/autotester/domain/entity"
)

// NewMockChatStorageService creates a new instance of MockChatStorageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatStorageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatStorageService {
	mock := &MockChatStorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatStorageService is an autogenerated mock type for the ChatStorageService type
type MockChatStorageService struct {
	mock.Mock
}

type MockChatStorageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatStorageService) EXPECT() *MockChatStorageService_Expecter {
	return &MockChatStorageService_Expecter{mock: &_m.Mock}
}

// LoadChat provides a mock function for the type MockChatStorageService
func (_mock *MockChatStorageService) LoadChat(ctx context.Context, chatId string, userId string) (*entity.Chat, error) {
	ret := _mock.Called(ctx, chatId, userId)

	if len(ret) == 0 {
		panic("no return value specified for LoadChat")
	}

	var r0 *entity.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*entity.Chat, error)); ok {
		return returnFunc(ctx, chatId, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *entity.Chat); ok {
		r0 = returnFunc(ctx, chatId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Chat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, chatId, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatStorageService_LoadChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadChat'
type MockChatStorageService_LoadChat_Call struct {
	*mock.Call
}

// LoadChat is a helper method to define mock.On call
//   - ctx context.Context
//   - chatId string
//   - userId string
func (_e *MockChatStorageService_Expecter) LoadChat(ctx interface{}, chatId interface{}, userId interface{}) *MockChatStorageService_LoadChat_Call {
	return &MockChatStorageService_LoadChat_Call{Call: _e.mock.On("LoadChat", ctx, chatId, userId)}
}

func (_c *MockChatStorageService_LoadChat_Call) Run(run func(ctx context.Context, chatId string, userId string)) *MockChatStorageService_LoadChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatStorageService_LoadChat_Call) Return(chat *entity.Chat, err error) *MockChatStorageService_LoadChat_Call {
	_c.Call.Return(chat, err)
	return _c
}

func (_c *MockChatStorageService_LoadChat_Call) RunAndReturn(run func(ctx context.Context, chatId string, userId string) (*entity.Chat, error)) *MockChatStorageService_LoadChat_Call {
	_c.Call.Return(run)
	return _c
}

// LoadUserChats provides a mock function for the type MockChatStorageService
func (_mock *MockChatStorageService) LoadUserChats(ctx context.Context, userID string) ([]*entity.ChatSummary, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for LoadUserChats")
	}

	var r0 []*entity.ChatSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.ChatSummary, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.ChatSummary); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ChatSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatStorageService_LoadUserChats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadUserChats'
type MockChatStorageService_LoadUserChats_Call struct {
	*mock.Call
}

// LoadUserChats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockChatStorageService_Expecter) LoadUserChats(ctx interface{}, userID interface{}) *MockChatStorageService_LoadUserChats_Call {
	return &MockChatStorageService_LoadUserChats_Call{Call: _e.mock.On("LoadUserChats", ctx, userID)}
}

func (_c *MockChatStorageService_LoadUserChats_Call) Run(run func(ctx context.Context, userID string)) *MockChatStorageService_LoadUserChats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatStorageService_LoadUserChats_Call) Return(chatSummarys []*entity.ChatSummary, err error) *MockChatStorageService_LoadUserChats_Call {
	_c.Call.Return(chatSummarys, err)
	return _c
}

func (_c *MockChatStorageService_LoadUserChats_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*entity.ChatSummary, error)) *MockChatStorageService_LoadUserChats_Call {
	_c.Call.Return(run)
	return _c
}

// SaveChat provides a mock function for the type MockChatStorageService
func (_mock *MockChatStorageService) SaveChat(ctx context.Context, summary *entity.Chat) error {
	ret := _mock.Called(ctx, summary)

	if len(ret) == 0 {
		panic("no return value specified for SaveChat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Chat) error); ok {
		r0 = returnFunc(ctx, summary)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatStorageService_SaveChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveChat'
type MockChatStorageService_SaveChat_Call struct {
	*mock.Call
}

// SaveChat is a helper method to define mock.On call
//   - ctx context.Context
//   - summary *entity.Chat
func (_e *MockChatStorageService_Expecter) SaveChat(ctx interface{}, summary interface{}) *MockChatStorageService_SaveChat_Call {
	return &MockChatStorageService_SaveChat_Call{Call: _e.mock.On("SaveChat", ctx, summary)}
}

func (_c *MockChatStorageService_SaveChat_Call) Run(run func(ctx context.Context, summary *entity.Chat)) *MockChatStorageService_SaveChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Chat
		if args[1] != nil {
			arg1 = args[1].(*entity.Chat)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatStorageService_SaveChat_Call) Return(err error) *MockChatStorageService_SaveChat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatStorageService_SaveChat_Call) RunAndReturn(run func(ctx context.Context, summary *entity.Chat) error) *MockChatStorageService_SaveChat_Call {
	_c.Call.Return(run)
	return _c
}
