// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/autotester/domain/entity"
)

// NewMockChatManager creates a new instance of MockChatManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatManager {
	mock := &MockChatManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatManager is an autogenerated mock type for the ChatManager type
type MockChatManager struct {
	mock.Mock
}

type MockChatManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatManager) EXPECT() *MockChatManager_Expecter {
	return &MockChatManager_Expecter{mock: &_m.Mock}
}

// LoadChat provides a mock function for the type MockChatManager
func (_mock *MockChatManager) LoadChat(context1 context.Context, userRequest entity.UserRequest) (*entity.Chat, error) {
	ret := _mock.Called(context1, userRequest)

	if len(ret) == 0 {
		panic("no return value specified for LoadChat")
	}

	var r0 *entity.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.UserRequest) (*entity.Chat, error)); ok {
		return returnFunc(context1, userRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.UserRequest) *entity.Chat); ok {
		r0 = returnFunc(context1, userRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Chat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.UserRequest) error); ok {
		r1 = returnFunc(context1, userRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatManager_LoadChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadChat'
type MockChatManager_LoadChat_Call struct {
	*mock.Call
}

// LoadChat is a helper method to define mock.On call
//   - context1 context.Context
//   - userRequest entity.UserRequest
func (_e *MockChatManager_Expecter) LoadChat(context1 interface{}, userRequest interface{}) *MockChatManager_LoadChat_Call {
	return &MockChatManager_LoadChat_Call{Call: _e.mock.On("LoadChat", context1, userRequest)}
}

func (_c *MockChatManager_LoadChat_Call) Run(run func(context1 context.Context, userRequest entity.UserRequest)) *MockChatManager_LoadChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.UserRequest
		if args[1] != nil {
			arg1 = args[1].(entity.UserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatManager_LoadChat_Call) Return(chat *entity.Chat, err error) *MockChatManager_LoadChat_Call {
	_c.Call.Return(chat, err)
	return _c
}

func (_c *MockChatManager_LoadChat_Call) RunAndReturn(run func(context1 context.Context, userRequest entity.UserRequest) (*entity.Chat, error)) *MockChatManager_LoadChat_Call {
	_c.Call.Return(run)
	return _c
}

// SaveChat provides a mock function for the type MockChatManager
func (_mock *MockChatManager) SaveChat(context1 context.Context, chat *entity.Chat) error {
	ret := _mock.Called(context1, chat)

	if len(ret) == 0 {
		panic("no return value specified for SaveChat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Chat) error); ok {
		r0 = returnFunc(context1, chat)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatManager_SaveChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveChat'
type MockChatManager_SaveChat_Call struct {
	*mock.Call
}

// SaveChat is a helper method to define mock.On call
//   - context1 context.Context
//   - chat *entity.Chat
func (_e *MockChatManager_Expecter) SaveChat(context1 interface{}, chat interface{}) *MockChatManager_SaveChat_Call {
	return &MockChatManager_SaveChat_Call{Call: _e.mock.On("SaveChat", context1, chat)}
}

func (_c *MockChatManager_SaveChat_Call) Run(run func(context1 context.Context, chat *entity.Chat)) *MockChatManager_SaveChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Chat
		if args[1] != nil {
			arg1 = args[1].(*entity.Chat)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatManager_SaveChat_Call) Return(err error) *MockChatManager_SaveChat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatManager_SaveChat_Call) RunAndReturn(run func(context1 context.Context, chat *entity.Chat) error) *MockChatManager_SaveChat_Call {
	_c.Call.Return(run)
	return _c
}
