// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/autotester/domain/entity"
)

// NewMockChatStorageService creates a new instance of MockChatStorageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatStorageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatStorageService {
	mock := &MockChatStorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatStorageService is an autogenerated mock type for the ChatStorageService type
type MockChatStorageService struct {
	mock.Mock
}

type MockChatStorageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatStorageService) EXPECT() *MockChatStorageService_Expecter {
	return &MockChatStorageService_Expecter{mock: &_m.Mock}
}

// LoadChat provides a mock function for the type MockChatStorageService
func (_mock *MockChatStorageService) LoadChat(ctx context.Context, chatId string) (*entity.Chat, error) {
	ret := _mock.Called(ctx, chatId)

	if len(ret) == 0 {
		panic("no return value specified for LoadChat")
	}

	var r0 *entity.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Chat, error)); ok {
		return returnFunc(ctx, chatId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Chat); ok {
		r0 = returnFunc(ctx, chatId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Chat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, chatId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatStorageService_LoadChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadChat'
type MockChatStorageService_LoadChat_Call struct {
	*mock.Call
}

// LoadChat is a helper method to define mock.On call
//   - ctx context.Context
//   - chatId string
func (_e *MockChatStorageService_Expecter) LoadChat(ctx interface{}, chatId interface{}) *MockChatStorageService_LoadChat_Call {
	return &MockChatStorageService_LoadChat_Call{Call: _e.mock.On("LoadChat", ctx, chatId)}
}

func (_c *MockChatStorageService_LoadChat_Call) Run(run func(ctx context.Context, chatId string)) *MockChatStorageService_LoadChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatStorageService_LoadChat_Call) Return(chat *entity.Chat, err error) *MockChatStorageService_LoadChat_Call {
	_c.Call.Return(chat, err)
	return _c
}

func (_c *MockChatStorageService_LoadChat_Call) RunAndReturn(run func(ctx context.Context, chatId string) (*entity.Chat, error)) *MockChatStorageService_LoadChat_Call {
	_c.Call.Return(run)
	return _c
}

// LoadSummaries provides a mock function for the type MockChatStorageService
func (_mock *MockChatStorageService) LoadSummaries(ctx context.Context, offset int, limit int, groupIds ...string) ([]*entity.ChatSummary, bool, error) {
	var tmpRet mock.Arguments
	if len(groupIds) > 0 {
		tmpRet = _mock.Called(ctx, offset, limit, groupIds)
	} else {
		tmpRet = _mock.Called(ctx, offset, limit)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for LoadSummaries")
	}

	var r0 []*entity.ChatSummary
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, ...string) ([]*entity.ChatSummary, bool, error)); ok {
		return returnFunc(ctx, offset, limit, groupIds...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, ...string) []*entity.ChatSummary); ok {
		r0 = returnFunc(ctx, offset, limit, groupIds...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ChatSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, ...string) bool); ok {
		r1 = returnFunc(ctx, offset, limit, groupIds...)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int, ...string) error); ok {
		r2 = returnFunc(ctx, offset, limit, groupIds...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockChatStorageService_LoadSummaries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadSummaries'
type MockChatStorageService_LoadSummaries_Call struct {
	*mock.Call
}

// LoadSummaries is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
//   - groupIds ...string
func (_e *MockChatStorageService_Expecter) LoadSummaries(ctx interface{}, offset interface{}, limit interface{}, groupIds ...interface{}) *MockChatStorageService_LoadSummaries_Call {
	return &MockChatStorageService_LoadSummaries_Call{Call: _e.mock.On("LoadSummaries",
		append([]interface{}{ctx, offset, limit}, groupIds...)...)}
}

func (_c *MockChatStorageService_LoadSummaries_Call) Run(run func(ctx context.Context, offset int, limit int, groupIds ...string)) *MockChatStorageService_LoadSummaries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 []string
		var variadicArgs []string
		if len(args) > 3 {
			variadicArgs = args[3].([]string)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockChatStorageService_LoadSummaries_Call) Return(chatSummarys []*entity.ChatSummary, b bool, err error) *MockChatStorageService_LoadSummaries_Call {
	_c.Call.Return(chatSummarys, b, err)
	return _c
}

func (_c *MockChatStorageService_LoadSummaries_Call) RunAndReturn(run func(ctx context.Context, offset int, limit int, groupIds ...string) ([]*entity.ChatSummary, bool, error)) *MockChatStorageService_LoadSummaries_Call {
	_c.Call.Return(run)
	return _c
}

// SaveChat provides a mock function for the type MockChatStorageService
func (_mock *MockChatStorageService) SaveChat(ctx context.Context, chat *entity.Chat) error {
	ret := _mock.Called(ctx, chat)

	if len(ret) == 0 {
		panic("no return value specified for SaveChat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Chat) error); ok {
		r0 = returnFunc(ctx, chat)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatStorageService_SaveChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveChat'
type MockChatStorageService_SaveChat_Call struct {
	*mock.Call
}

// SaveChat is a helper method to define mock.On call
//   - ctx context.Context
//   - chat *entity.Chat
func (_e *MockChatStorageService_Expecter) SaveChat(ctx interface{}, chat interface{}) *MockChatStorageService_SaveChat_Call {
	return &MockChatStorageService_SaveChat_Call{Call: _e.mock.On("SaveChat", ctx, chat)}
}

func (_c *MockChatStorageService_SaveChat_Call) Run(run func(ctx context.Context, chat *entity.Chat)) *MockChatStorageService_SaveChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Chat
		if args[1] != nil {
			arg1 = args[1].(*entity.Chat)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatStorageService_SaveChat_Call) Return(err error) *MockChatStorageService_SaveChat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatStorageService_SaveChat_Call) RunAndReturn(run func(ctx context.Context, chat *entity.Chat) error) *MockChatStorageService_SaveChat_Call {
	_c.Call.Return(run)
	return _c
}
