// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/autotester/domain/entity"
)

// NewMockGroupManager creates a new instance of MockGroupManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupManager {
	mock := &MockGroupManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGroupManager is an autogenerated mock type for the GroupManager type
type MockGroupManager struct {
	mock.Mock
}

type MockGroupManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupManager) EXPECT() *MockGroupManager_Expecter {
	return &MockGroupManager_Expecter{mock: &_m.Mock}
}

// AddChatToGroup provides a mock function for the type MockGroupManager
func (_mock *MockGroupManager) AddChatToGroup(ctx context.Context, groupId string, chatId string) error {
	ret := _mock.Called(ctx, groupId, chatId)

	if len(ret) == 0 {
		panic("no return value specified for AddChatToGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, groupId, chatId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupManager_AddChatToGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddChatToGroup'
type MockGroupManager_AddChatToGroup_Call struct {
	*mock.Call
}

// AddChatToGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - chatId string
func (_e *MockGroupManager_Expecter) AddChatToGroup(ctx interface{}, groupId interface{}, chatId interface{}) *MockGroupManager_AddChatToGroup_Call {
	return &MockGroupManager_AddChatToGroup_Call{Call: _e.mock.On("AddChatToGroup", ctx, groupId, chatId)}
}

func (_c *MockGroupManager_AddChatToGroup_Call) Run(run func(ctx context.Context, groupId string, chatId string)) *MockGroupManager_AddChatToGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupManager_AddChatToGroup_Call) Return(err error) *MockGroupManager_AddChatToGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupManager_AddChatToGroup_Call) RunAndReturn(run func(ctx context.Context, groupId string, chatId string) error) *MockGroupManager_AddChatToGroup_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockGroupManager
func (_mock *MockGroupManager) Create(ctx context.Context, name string, description string, creator string) (string, error) {
	ret := _mock.Called(ctx, name, description, creator)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return returnFunc(ctx, name, description, creator)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = returnFunc(ctx, name, description, creator)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, name, description, creator)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupManager_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGroupManager_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description string
//   - creator string
func (_e *MockGroupManager_Expecter) Create(ctx interface{}, name interface{}, description interface{}, creator interface{}) *MockGroupManager_Create_Call {
	return &MockGroupManager_Create_Call{Call: _e.mock.On("Create", ctx, name, description, creator)}
}

func (_c *MockGroupManager_Create_Call) Run(run func(ctx context.Context, name string, description string, creator string)) *MockGroupManager_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGroupManager_Create_Call) Return(s string, err error) *MockGroupManager_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGroupManager_Create_Call) RunAndReturn(run func(ctx context.Context, name string, description string, creator string) (string, error)) *MockGroupManager_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockGroupManager
func (_mock *MockGroupManager) List(ctx context.Context) ([]*entity.Group, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.Group, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.Group); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupManager_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockGroupManager_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGroupManager_Expecter) List(ctx interface{}) *MockGroupManager_List_Call {
	return &MockGroupManager_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockGroupManager_List_Call) Run(run func(ctx context.Context)) *MockGroupManager_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGroupManager_List_Call) Return(groups []*entity.Group, err error) *MockGroupManager_List_Call {
	_c.Call.Return(groups, err)
	return _c
}

func (_c *MockGroupManager_List_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.Group, error)) *MockGroupManager_List_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveChatFromGroup provides a mock function for the type MockGroupManager
func (_mock *MockGroupManager) RemoveChatFromGroup(ctx context.Context, groupId string, chatId string) error {
	ret := _mock.Called(ctx, groupId, chatId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveChatFromGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, groupId, chatId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupManager_RemoveChatFromGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveChatFromGroup'
type MockGroupManager_RemoveChatFromGroup_Call struct {
	*mock.Call
}

// RemoveChatFromGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - chatId string
func (_e *MockGroupManager_Expecter) RemoveChatFromGroup(ctx interface{}, groupId interface{}, chatId interface{}) *MockGroupManager_RemoveChatFromGroup_Call {
	return &MockGroupManager_RemoveChatFromGroup_Call{Call: _e.mock.On("RemoveChatFromGroup", ctx, groupId, chatId)}
}

func (_c *MockGroupManager_RemoveChatFromGroup_Call) Run(run func(ctx context.Context, groupId string, chatId string)) *MockGroupManager_RemoveChatFromGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupManager_RemoveChatFromGroup_Call) Return(err error) *MockGroupManager_RemoveChatFromGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupManager_RemoveChatFromGroup_Call) RunAndReturn(run func(ctx context.Context, groupId string, chatId string) error) *MockGroupManager_RemoveChatFromGroup_Call {
	_c.Call.Return(run)
	return _c
}
