// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/autotester/domain/entity"
)

// NewMockGroupStorage creates a new instance of MockGroupStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupStorage {
	mock := &MockGroupStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGroupStorage is an autogenerated mock type for the GroupStorage type
type MockGroupStorage struct {
	mock.Mock
}

type MockGroupStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupStorage) EXPECT() *MockGroupStorage_Expecter {
	return &MockGroupStorage_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockGroupStorage
func (_mock *MockGroupStorage) Load(ctx context.Context, id string) (*entity.Group, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *entity.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Group, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Group); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupStorage_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockGroupStorage_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockGroupStorage_Expecter) Load(ctx interface{}, id interface{}) *MockGroupStorage_Load_Call {
	return &MockGroupStorage_Load_Call{Call: _e.mock.On("Load", ctx, id)}
}

func (_c *MockGroupStorage_Load_Call) Run(run func(ctx context.Context, id string)) *MockGroupStorage_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupStorage_Load_Call) Return(group *entity.Group, err error) *MockGroupStorage_Load_Call {
	_c.Call.Return(group, err)
	return _c
}

func (_c *MockGroupStorage_Load_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.Group, error)) *MockGroupStorage_Load_Call {
	_c.Call.Return(run)
	return _c
}

// LoadAll provides a mock function for the type MockGroupStorage
func (_mock *MockGroupStorage) LoadAll(ctx context.Context) ([]*entity.Group, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadAll")
	}

	var r0 []*entity.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.Group, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.Group); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupStorage_LoadAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadAll'
type MockGroupStorage_LoadAll_Call struct {
	*mock.Call
}

// LoadAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGroupStorage_Expecter) LoadAll(ctx interface{}) *MockGroupStorage_LoadAll_Call {
	return &MockGroupStorage_LoadAll_Call{Call: _e.mock.On("LoadAll", ctx)}
}

func (_c *MockGroupStorage_LoadAll_Call) Run(run func(ctx context.Context)) *MockGroupStorage_LoadAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGroupStorage_LoadAll_Call) Return(groups []*entity.Group, err error) *MockGroupStorage_LoadAll_Call {
	_c.Call.Return(groups, err)
	return _c
}

func (_c *MockGroupStorage_LoadAll_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.Group, error)) *MockGroupStorage_LoadAll_Call {
	_c.Call.Return(run)
	return _c
}

// New provides a mock function for the type MockGroupStorage
func (_mock *MockGroupStorage) New(ctx context.Context, group *entity.Group) error {
	ret := _mock.Called(ctx, group)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Group) error); ok {
		r0 = returnFunc(ctx, group)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupStorage_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockGroupStorage_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - ctx context.Context
//   - group *entity.Group
func (_e *MockGroupStorage_Expecter) New(ctx interface{}, group interface{}) *MockGroupStorage_New_Call {
	return &MockGroupStorage_New_Call{Call: _e.mock.On("New", ctx, group)}
}

func (_c *MockGroupStorage_New_Call) Run(run func(ctx context.Context, group *entity.Group)) *MockGroupStorage_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Group
		if args[1] != nil {
			arg1 = args[1].(*entity.Group)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupStorage_New_Call) Return(err error) *MockGroupStorage_New_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupStorage_New_Call) RunAndReturn(run func(ctx context.Context, group *entity.Group) error) *MockGroupStorage_New_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockGroupStorage
func (_mock *MockGroupStorage) Remove(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupStorage_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockGroupStorage_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockGroupStorage_Expecter) Remove(ctx interface{}, id interface{}) *MockGroupStorage_Remove_Call {
	return &MockGroupStorage_Remove_Call{Call: _e.mock.On("Remove", ctx, id)}
}

func (_c *MockGroupStorage_Remove_Call) Run(run func(ctx context.Context, id string)) *MockGroupStorage_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupStorage_Remove_Call) Return(err error) *MockGroupStorage_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupStorage_Remove_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockGroupStorage_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockGroupStorage
func (_mock *MockGroupStorage) Update(ctx context.Context, group *entity.Group) error {
	ret := _mock.Called(ctx, group)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Group) error); ok {
		r0 = returnFunc(ctx, group)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupStorage_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockGroupStorage_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - group *entity.Group
func (_e *MockGroupStorage_Expecter) Update(ctx interface{}, group interface{}) *MockGroupStorage_Update_Call {
	return &MockGroupStorage_Update_Call{Call: _e.mock.On("Update", ctx, group)}
}

func (_c *MockGroupStorage_Update_Call) Run(run func(ctx context.Context, group *entity.Group)) *MockGroupStorage_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Group
		if args[1] != nil {
			arg1 = args[1].(*entity.Group)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupStorage_Update_Call) Return(err error) *MockGroupStorage_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupStorage_Update_Call) RunAndReturn(run func(ctx context.Context, group *entity.Group) error) *MockGroupStorage_Update_Call {
	_c.Call.Return(run)
	return _c
}
