// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/autotester/domain/entity"
)

// NewMockJWTValidator creates a new instance of MockJWTValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTValidator {
	mock := &MockJWTValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJWTValidator is an autogenerated mock type for the JWTValidator type
type MockJWTValidator struct {
	mock.Mock
}

type MockJWTValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTValidator) EXPECT() *MockJWTValidator_Expecter {
	return &MockJWTValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type MockJWTValidator
func (_mock *MockJWTValidator) Validate(ctx context.Context, jwt string) (entity.ValidationResult, error) {
	ret := _mock.Called(ctx, jwt)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 entity.ValidationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.ValidationResult, error)); ok {
		return returnFunc(ctx, jwt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.ValidationResult); ok {
		r0 = returnFunc(ctx, jwt)
	} else {
		r0 = ret.Get(0).(entity.ValidationResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, jwt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJWTValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockJWTValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - jwt string
func (_e *MockJWTValidator_Expecter) Validate(ctx interface{}, jwt interface{}) *MockJWTValidator_Validate_Call {
	return &MockJWTValidator_Validate_Call{Call: _e.mock.On("Validate", ctx, jwt)}
}

func (_c *MockJWTValidator_Validate_Call) Run(run func(ctx context.Context, jwt string)) *MockJWTValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJWTValidator_Validate_Call) Return(validationResult entity.ValidationResult, err error) *MockJWTValidator_Validate_Call {
	_c.Call.Return(validationResult, err)
	return _c
}

func (_c *MockJWTValidator_Validate_Call) RunAndReturn(run func(ctx context.Context, jwt string) (entity.ValidationResult, error)) *MockJWTValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}
