// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMediaStorageService creates a new instance of MockMediaStorageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaStorageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaStorageService {
	mock := &MockMediaStorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMediaStorageService is an autogenerated mock type for the MediaStorageService type
type MockMediaStorageService struct {
	mock.Mock
}

type MockMediaStorageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaStorageService) EXPECT() *MockMediaStorageService_Expecter {
	return &MockMediaStorageService_Expecter{mock: &_m.Mock}
}

// GetScreenshot provides a mock function for the type MockMediaStorageService
func (_mock *MockMediaStorageService) GetScreenshot(testId string) ([]byte, error) {
	ret := _mock.Called(testId)

	if len(ret) == 0 {
		panic("no return value specified for GetScreenshot")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(testId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(testId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(testId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GetVideo provides a mock function for the type MockMediaStorageService
func (_mock *MockMediaStorageService) GetVideo(testId string) ([]byte, error) {
	ret := _mock.Called(testId)

	if len(ret) == 0 {
		panic("no return value specified for GetVideo")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(testId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(testId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(testId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GetScreenshotPath provides a mock function for the type MockMediaStorageService
func (_mock *MockMediaStorageService) GetScreenshotPath(testId string) (string, error) {
	ret := _mock.Called(testId)

	if len(ret) == 0 {
		panic("no return value specified for GetScreenshotPath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(testId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(testId)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(testId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GetVideoPath provides a mock function for the type MockMediaStorageService
func (_mock *MockMediaStorageService) GetVideoPath(testId string) (string, error) {
	ret := _mock.Called(testId)

	if len(ret) == 0 {
		panic("no return value specified for GetVideoPath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(testId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(testId)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(testId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HasMedia provides a mock function for the type MockMediaStorageService
func (_mock *MockMediaStorageService) HasMedia(testId string) (bool, bool) {
	ret := _mock.Called(testId)

	if len(ret) == 0 {
		panic("no return value specified for HasMedia")
	}

	var r0 bool
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (bool, bool)); ok {
		return returnFunc(testId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(testId)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(testId)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// GetMediaDir provides a mock function for the type MockMediaStorageService
func (_mock *MockMediaStorageService) GetMediaDir(testId string) (string, error) {
	ret := _mock.Called(testId)

	if len(ret) == 0 {
		panic("no return value specified for GetMediaDir")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(testId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(testId)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(testId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CleanupMedia provides a mock function for the type MockMediaStorageService
func (_mock *MockMediaStorageService) CleanupMedia(testId string) error {
	ret := _mock.Called(testId)

	if len(ret) == 0 {
		panic("no return value specified for CleanupMedia")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(testId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}
