// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/autotester/domain/entity"
	entity0 "gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/shared/domain/entity"
)

// NewMockValidator creates a new instance of MockValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidator {
	mock := &MockValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

type MockValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidator) EXPECT() *MockValidator_Expecter {
	return &MockValidator_Expecter{mock: &_m.Mock}
}

// ValidatePrompt provides a mock function for the type MockValidator
func (_mock *MockValidator) ValidatePrompt(ctx context.Context, chat *entity.Chat, request *entity.UserRequest) (bool, string, error) {
	ret := _mock.Called(ctx, chat, request)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePrompt")
	}

	var r0 bool
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Chat, *entity.UserRequest) (bool, string, error)); ok {
		return returnFunc(ctx, chat, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Chat, *entity.UserRequest) bool); ok {
		r0 = returnFunc(ctx, chat, request)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Chat, *entity.UserRequest) string); ok {
		r1 = returnFunc(ctx, chat, request)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *entity.Chat, *entity.UserRequest) error); ok {
		r2 = returnFunc(ctx, chat, request)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockValidator_ValidatePrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatePrompt'
type MockValidator_ValidatePrompt_Call struct {
	*mock.Call
}

// ValidatePrompt is a helper method to define mock.On call
//   - ctx context.Context
//   - chat *entity.Chat
//   - request *entity.UserRequest
func (_e *MockValidator_Expecter) ValidatePrompt(ctx interface{}, chat interface{}, request interface{}) *MockValidator_ValidatePrompt_Call {
	return &MockValidator_ValidatePrompt_Call{Call: _e.mock.On("ValidatePrompt", ctx, chat, request)}
}

func (_c *MockValidator_ValidatePrompt_Call) Run(run func(ctx context.Context, chat *entity.Chat, request *entity.UserRequest)) *MockValidator_ValidatePrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Chat
		if args[1] != nil {
			arg1 = args[1].(*entity.Chat)
		}
		var arg2 *entity.UserRequest
		if args[2] != nil {
			arg2 = args[2].(*entity.UserRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockValidator_ValidatePrompt_Call) Return(b bool, s string, err error) *MockValidator_ValidatePrompt_Call {
	_c.Call.Return(b, s, err)
	return _c
}

func (_c *MockValidator_ValidatePrompt_Call) RunAndReturn(run func(ctx context.Context, chat *entity.Chat, request *entity.UserRequest) (bool, string, error)) *MockValidator_ValidatePrompt_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRequest provides a mock function for the type MockValidator
func (_mock *MockValidator) ValidateRequest(ctx context.Context, req entity0.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity0.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockValidator_ValidateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRequest'
type MockValidator_ValidateRequest_Call struct {
	*mock.Call
}

// ValidateRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - req entity0.Request
func (_e *MockValidator_Expecter) ValidateRequest(ctx interface{}, req interface{}) *MockValidator_ValidateRequest_Call {
	return &MockValidator_ValidateRequest_Call{Call: _e.mock.On("ValidateRequest", ctx, req)}
}

func (_c *MockValidator_ValidateRequest_Call) Run(run func(ctx context.Context, req entity0.Request)) *MockValidator_ValidateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity0.Request
		if args[1] != nil {
			arg1 = args[1].(entity0.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockValidator_ValidateRequest_Call) Return(err error) *MockValidator_ValidateRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockValidator_ValidateRequest_Call) RunAndReturn(run func(ctx context.Context, req entity0.Request) error) *MockValidator_ValidateRequest_Call {
	_c.Call.Return(run)
	return _c
}
