// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/shared/domain/entity"
)

// OpenAI is an autogenerated mock type for the OpenAI type
type OpenAI struct {
	mock.Mock
}

type OpenAI_Expecter struct {
	mock *mock.Mock
}

func (_m *OpenAI) EXPECT() *OpenAI_Expecter {
	return &OpenAI_Expecter{mock: &_m.Mock}
}

// CreateRequest provides a mock function with given fields: _a0, _a1
func (_m *OpenAI) CreateRequest(_a0 context.Context, _a1 entity.Request) (*entity.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateRequest")
	}

	var r0 *entity.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Request) (*entity.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Request) *entity.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Request) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OpenAI_CreateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRequest'
type OpenAI_CreateRequest_Call struct {
	*mock.Call
}

// CreateRequest is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 entity.Request
func (_e *OpenAI_Expecter) CreateRequest(_a0 interface{}, _a1 interface{}) *OpenAI_CreateRequest_Call {
	return &OpenAI_CreateRequest_Call{Call: _e.mock.On("CreateRequest", _a0, _a1)}
}

func (_c *OpenAI_CreateRequest_Call) Run(run func(_a0 context.Context, _a1 entity.Request)) *OpenAI_CreateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Request))
	})
	return _c
}

func (_c *OpenAI_CreateRequest_Call) Return(_a0 *entity.Response, _a1 error) *OpenAI_CreateRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OpenAI_CreateRequest_Call) RunAndReturn(run func(context.Context, entity.Request) (*entity.Response, error)) *OpenAI_CreateRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewOpenAI creates a new instance of OpenAI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOpenAI(t interface {
	mock.TestingT
	Cleanup(func())
}) *OpenAI {
	mock := &OpenAI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
