// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/shared/domain/entity"
)

// NewMockTaglistStorage creates a new instance of MockTaglistStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaglistStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaglistStorage {
	mock := &MockTaglistStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaglistStorage is an autogenerated mock type for the TaglistStorage type
type MockTaglistStorage struct {
	mock.Mock
}

type MockTaglistStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaglistStorage) EXPECT() *MockTaglistStorage_Expecter {
	return &MockTaglistStorage_Expecter{mock: &_m.Mock}
}

// CreateTaglist provides a mock function for the type MockTaglistStorage
func (_mock *MockTaglistStorage) CreateTaglist(ctx context.Context, TagList *entity.TagList) error {
	ret := _mock.Called(ctx, TagList)

	if len(ret) == 0 {
		panic("no return value specified for CreateTaglist")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.TagList) error); ok {
		r0 = returnFunc(ctx, TagList)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaglistStorage_CreateTaglist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTaglist'
type MockTaglistStorage_CreateTaglist_Call struct {
	*mock.Call
}

// CreateTaglist is a helper method to define mock.On call
//   - ctx context.Context
//   - TagList *entity.TagList
func (_e *MockTaglistStorage_Expecter) CreateTaglist(ctx interface{}, TagList interface{}) *MockTaglistStorage_CreateTaglist_Call {
	return &MockTaglistStorage_CreateTaglist_Call{Call: _e.mock.On("CreateTaglist", ctx, TagList)}
}

func (_c *MockTaglistStorage_CreateTaglist_Call) Run(run func(ctx context.Context, TagList *entity.TagList)) *MockTaglistStorage_CreateTaglist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.TagList
		if args[1] != nil {
			arg1 = args[1].(*entity.TagList)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaglistStorage_CreateTaglist_Call) Return(err error) *MockTaglistStorage_CreateTaglist_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaglistStorage_CreateTaglist_Call) RunAndReturn(run func(ctx context.Context, TagList *entity.TagList) error) *MockTaglistStorage_CreateTaglist_Call {
	_c.Call.Return(run)
	return _c
}

// ReadTaglist provides a mock function for the type MockTaglistStorage
func (_mock *MockTaglistStorage) ReadTaglist(ctx context.Context) (*entity.TagList, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadTaglist")
	}

	var r0 *entity.TagList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*entity.TagList, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *entity.TagList); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TagList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaglistStorage_ReadTaglist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadTaglist'
type MockTaglistStorage_ReadTaglist_Call struct {
	*mock.Call
}

// ReadTaglist is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaglistStorage_Expecter) ReadTaglist(ctx interface{}) *MockTaglistStorage_ReadTaglist_Call {
	return &MockTaglistStorage_ReadTaglist_Call{Call: _e.mock.On("ReadTaglist", ctx)}
}

func (_c *MockTaglistStorage_ReadTaglist_Call) Run(run func(ctx context.Context)) *MockTaglistStorage_ReadTaglist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaglistStorage_ReadTaglist_Call) Return(tagList *entity.TagList, err error) *MockTaglistStorage_ReadTaglist_Call {
	_c.Call.Return(tagList, err)
	return _c
}

func (_c *MockTaglistStorage_ReadTaglist_Call) RunAndReturn(run func(ctx context.Context) (*entity.TagList, error)) *MockTaglistStorage_ReadTaglist_Call {
	_c.Call.Return(run)
	return _c
}

// TaglistExists provides a mock function for the type MockTaglistStorage
func (_mock *MockTaglistStorage) TaglistExists(ctx context.Context) (bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TaglistExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaglistStorage_TaglistExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TaglistExists'
type MockTaglistStorage_TaglistExists_Call struct {
	*mock.Call
}

// TaglistExists is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaglistStorage_Expecter) TaglistExists(ctx interface{}) *MockTaglistStorage_TaglistExists_Call {
	return &MockTaglistStorage_TaglistExists_Call{Call: _e.mock.On("TaglistExists", ctx)}
}

func (_c *MockTaglistStorage_TaglistExists_Call) Run(run func(ctx context.Context)) *MockTaglistStorage_TaglistExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaglistStorage_TaglistExists_Call) Return(b bool, err error) *MockTaglistStorage_TaglistExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTaglistStorage_TaglistExists_Call) RunAndReturn(run func(ctx context.Context) (bool, error)) *MockTaglistStorage_TaglistExists_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTaglist provides a mock function for the type MockTaglistStorage
func (_mock *MockTaglistStorage) UpdateTaglist(ctx context.Context, TagList *entity.TagList) error {
	ret := _mock.Called(ctx, TagList)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaglist")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.TagList) error); ok {
		r0 = returnFunc(ctx, TagList)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaglistStorage_UpdateTaglist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTaglist'
type MockTaglistStorage_UpdateTaglist_Call struct {
	*mock.Call
}

// UpdateTaglist is a helper method to define mock.On call
//   - ctx context.Context
//   - TagList *entity.TagList
func (_e *MockTaglistStorage_Expecter) UpdateTaglist(ctx interface{}, TagList interface{}) *MockTaglistStorage_UpdateTaglist_Call {
	return &MockTaglistStorage_UpdateTaglist_Call{Call: _e.mock.On("UpdateTaglist", ctx, TagList)}
}

func (_c *MockTaglistStorage_UpdateTaglist_Call) Run(run func(ctx context.Context, TagList *entity.TagList)) *MockTaglistStorage_UpdateTaglist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.TagList
		if args[1] != nil {
			arg1 = args[1].(*entity.TagList)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaglistStorage_UpdateTaglist_Call) Return(err error) *MockTaglistStorage_UpdateTaglist_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaglistStorage_UpdateTaglist_Call) RunAndReturn(run func(ctx context.Context, TagList *entity.TagList) error) *MockTaglistStorage_UpdateTaglist_Call {
	_c.Call.Return(run)
	return _c
}
