// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/mcp/domain/entity"
)

// NewMockTestLogStreamStore creates a new instance of MockTestLogStreamStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestLogStreamStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestLogStreamStore {
	mock := &MockTestLogStreamStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTestLogStreamStore is an autogenerated mock type for the TestLogStreamStore type
type MockTestLogStreamStore struct {
	mock.Mock
}

type MockTestLogStreamStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTestLogStreamStore) EXPECT() *MockTestLogStreamStore_Expecter {
	return &MockTestLogStreamStore_Expecter{mock: &_m.Mock}
}

// AddEvent provides a mock function for the type MockTestLogStreamStore
func (_mock *MockTestLogStreamStore) AddEvent(testId string, event entity.LogEvent) {
	_mock.Called(testId, event)
	return
}

// MockTestLogStreamStore_AddEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEvent'
type MockTestLogStreamStore_AddEvent_Call struct {
	*mock.Call
}

// AddEvent is a helper method to define mock.On call
//   - testId string
//   - event entity.LogEvent
func (_e *MockTestLogStreamStore_Expecter) AddEvent(testId interface{}, event interface{}) *MockTestLogStreamStore_AddEvent_Call {
	return &MockTestLogStreamStore_AddEvent_Call{Call: _e.mock.On("AddEvent", testId, event)}
}

func (_c *MockTestLogStreamStore_AddEvent_Call) Run(run func(testId string, event entity.LogEvent)) *MockTestLogStreamStore_AddEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 entity.LogEvent
		if args[1] != nil {
			arg1 = args[1].(entity.LogEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestLogStreamStore_AddEvent_Call) Return() *MockTestLogStreamStore_AddEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTestLogStreamStore_AddEvent_Call) RunAndReturn(run func(testId string, event entity.LogEvent)) *MockTestLogStreamStore_AddEvent_Call {
	_c.Run(run)
	return _c
}

// CompleteStream provides a mock function for the type MockTestLogStreamStore
func (_mock *MockTestLogStreamStore) CompleteStream(testId string) {
	_mock.Called(testId)
	return
}

// MockTestLogStreamStore_CompleteStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteStream'
type MockTestLogStreamStore_CompleteStream_Call struct {
	*mock.Call
}

// CompleteStream is a helper method to define mock.On call
//   - testId string
func (_e *MockTestLogStreamStore_Expecter) CompleteStream(testId interface{}) *MockTestLogStreamStore_CompleteStream_Call {
	return &MockTestLogStreamStore_CompleteStream_Call{Call: _e.mock.On("CompleteStream", testId)}
}

func (_c *MockTestLogStreamStore_CompleteStream_Call) Run(run func(testId string)) *MockTestLogStreamStore_CompleteStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestLogStreamStore_CompleteStream_Call) Return() *MockTestLogStreamStore_CompleteStream_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTestLogStreamStore_CompleteStream_Call) RunAndReturn(run func(testId string)) *MockTestLogStreamStore_CompleteStream_Call {
	_c.Run(run)
	return _c
}

// GetStream provides a mock function for the type MockTestLogStreamStore
func (_mock *MockTestLogStreamStore) GetStream(testId string) (*entity.LogStream, bool) {
	ret := _mock.Called(testId)

	if len(ret) == 0 {
		panic("no return value specified for GetStream")
	}

	var r0 *entity.LogStream
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (*entity.LogStream, bool)); ok {
		return returnFunc(testId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entity.LogStream); ok {
		r0 = returnFunc(testId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.LogStream)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(testId)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockTestLogStreamStore_GetStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStream'
type MockTestLogStreamStore_GetStream_Call struct {
	*mock.Call
}

// GetStream is a helper method to define mock.On call
//   - testId string
func (_e *MockTestLogStreamStore_Expecter) GetStream(testId interface{}) *MockTestLogStreamStore_GetStream_Call {
	return &MockTestLogStreamStore_GetStream_Call{Call: _e.mock.On("GetStream", testId)}
}

func (_c *MockTestLogStreamStore_GetStream_Call) Run(run func(testId string)) *MockTestLogStreamStore_GetStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestLogStreamStore_GetStream_Call) Return(logStream *entity.LogStream, b bool) *MockTestLogStreamStore_GetStream_Call {
	_c.Call.Return(logStream, b)
	return _c
}

func (_c *MockTestLogStreamStore_GetStream_Call) RunAndReturn(run func(testId string) (*entity.LogStream, bool)) *MockTestLogStreamStore_GetStream_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockTestLogStreamStore
func (_mock *MockTestLogStreamStore) Shutdown() {
	_mock.Called()
	return
}

// MockTestLogStreamStore_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockTestLogStreamStore_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockTestLogStreamStore_Expecter) Shutdown() *MockTestLogStreamStore_Shutdown_Call {
	return &MockTestLogStreamStore_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockTestLogStreamStore_Shutdown_Call) Run(run func()) *MockTestLogStreamStore_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestLogStreamStore_Shutdown_Call) Return() *MockTestLogStreamStore_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTestLogStreamStore_Shutdown_Call) RunAndReturn(run func()) *MockTestLogStreamStore_Shutdown_Call {
	_c.Run(run)
	return _c
}
