// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/shared/domain/entity"
)

// NewMockOpenAI creates a new instance of MockOpenAI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOpenAI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOpenAI {
	mock := &MockOpenAI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOpenAI is an autogenerated mock type for the OpenAI type
type MockOpenAI struct {
	mock.Mock
}

type MockOpenAI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOpenAI) EXPECT() *MockOpenAI_Expecter {
	return &MockOpenAI_Expecter{mock: &_m.Mock}
}

// Request provides a mock function for the type MockOpenAI
func (_mock *MockOpenAI) Request(context1 context.Context, request entity.Request) (*entity.Message, error) {
	ret := _mock.Called(context1, request)

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 *entity.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Request) (*entity.Message, error)); ok {
		return returnFunc(context1, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Request) *entity.Message); ok {
		r0 = returnFunc(context1, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Request) error); ok {
		r1 = returnFunc(context1, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOpenAI_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type MockOpenAI_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
//   - context1 context.Context
//   - request entity.Request
func (_e *MockOpenAI_Expecter) Request(context1 interface{}, request interface{}) *MockOpenAI_Request_Call {
	return &MockOpenAI_Request_Call{Call: _e.mock.On("Request", context1, request)}
}

func (_c *MockOpenAI_Request_Call) Run(run func(context1 context.Context, request entity.Request)) *MockOpenAI_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Request
		if args[1] != nil {
			arg1 = args[1].(entity.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOpenAI_Request_Call) Return(message *entity.Message, err error) *MockOpenAI_Request_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockOpenAI_Request_Call) RunAndReturn(run func(context1 context.Context, request entity.Request) (*entity.Message, error)) *MockOpenAI_Request_Call {
	_c.Call.Return(run)
	return _c
}
