// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/openai/openai-go/responses"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOpenAIClient creates a new instance of MockOpenAIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOpenAIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOpenAIClient {
	mock := &MockOpenAIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOpenAIClient is an autogenerated mock type for the OpenAIClient type
type MockOpenAIClient struct {
	mock.Mock
}

type MockOpenAIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOpenAIClient) EXPECT() *MockOpenAIClient_Expecter {
	return &MockOpenAIClient_Expecter{mock: &_m.Mock}
}

// Responses provides a mock function for the type MockOpenAIClient
func (_mock *MockOpenAIClient) Responses() *responses.ResponseService {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Responses")
	}

	var r0 *responses.ResponseService
	if returnFunc, ok := ret.Get(0).(func() *responses.ResponseService); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.ResponseService)
		}
	}
	return r0
}

// MockOpenAIClient_Responses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Responses'
type MockOpenAIClient_Responses_Call struct {
	*mock.Call
}

// Responses is a helper method to define mock.On call
func (_e *MockOpenAIClient_Expecter) Responses() *MockOpenAIClient_Responses_Call {
	return &MockOpenAIClient_Responses_Call{Call: _e.mock.On("Responses")}
}

func (_c *MockOpenAIClient_Responses_Call) Run(run func()) *MockOpenAIClient_Responses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOpenAIClient_Responses_Call) Return(responseService *responses.ResponseService) *MockOpenAIClient_Responses_Call {
	_c.Call.Return(responseService)
	return _c
}

func (_c *MockOpenAIClient_Responses_Call) RunAndReturn(run func() *responses.ResponseService) *MockOpenAIClient_Responses_Call {
	_c.Call.Return(run)
	return _c
}
