// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockValidatePrompt creates a new instance of MockValidatePrompt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidatePrompt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidatePrompt {
	mock := &MockValidatePrompt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValidatePrompt is an autogenerated mock type for the ValidatePrompt type
type MockValidatePrompt struct {
	mock.Mock
}

type MockValidatePrompt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidatePrompt) EXPECT() *MockValidatePrompt_Expecter {
	return &MockValidatePrompt_Expecter{mock: &_m.Mock}
}

// ValidatePrompt provides a mock function for the type MockValidatePrompt
func (_mock *MockValidatePrompt) ValidatePrompt(ctx context.Context, userPrompt string, sessionID string) error {
	ret := _mock.Called(ctx, userPrompt, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePrompt")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userPrompt, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockValidatePrompt_ValidatePrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatePrompt'
type MockValidatePrompt_ValidatePrompt_Call struct {
	*mock.Call
}

// ValidatePrompt is a helper method to define mock.On call
//   - ctx context.Context
//   - userPrompt string
//   - sessionID string
func (_e *MockValidatePrompt_Expecter) ValidatePrompt(ctx interface{}, userPrompt interface{}, sessionID interface{}) *MockValidatePrompt_ValidatePrompt_Call {
	return &MockValidatePrompt_ValidatePrompt_Call{Call: _e.mock.On("ValidatePrompt", ctx, userPrompt, sessionID)}
}

func (_c *MockValidatePrompt_ValidatePrompt_Call) Run(run func(ctx context.Context, userPrompt string, sessionID string)) *MockValidatePrompt_ValidatePrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockValidatePrompt_ValidatePrompt_Call) Return(err error) *MockValidatePrompt_ValidatePrompt_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockValidatePrompt_ValidatePrompt_Call) RunAndReturn(run func(ctx context.Context, userPrompt string, sessionID string) error) *MockValidatePrompt_ValidatePrompt_Call {
	_c.Call.Return(run)
	return _c
}
