// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/parquet-go/parquet-go"
	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/shared/domain/entity/wrapper"
)

// NewMockParquetFileWrapper creates a new instance of MockParquetFileWrapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParquetFileWrapper[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParquetFileWrapper[T] {
	mock := &MockParquetFileWrapper[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParquetFileWrapper is an autogenerated mock type for the ParquetFileWrapper type
type MockParquetFileWrapper[T any] struct {
	mock.Mock
}

type MockParquetFileWrapper_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockParquetFileWrapper[T]) EXPECT() *MockParquetFileWrapper_Expecter[T] {
	return &MockParquetFileWrapper_Expecter[T]{mock: &_m.Mock}
}

// GetParquetFileInfo provides a mock function for the type MockParquetFileWrapper
func (_mock *MockParquetFileWrapper[T]) GetParquetFileInfo(ctx context.Context, parquetData []byte) (*entity.ParquetFileInfo, error) {
	ret := _mock.Called(ctx, parquetData)

	if len(ret) == 0 {
		panic("no return value specified for GetParquetFileInfo")
	}

	var r0 *entity.ParquetFileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (*entity.ParquetFileInfo, error)); ok {
		return returnFunc(ctx, parquetData)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) *entity.ParquetFileInfo); ok {
		r0 = returnFunc(ctx, parquetData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ParquetFileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, parquetData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParquetFileWrapper_GetParquetFileInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParquetFileInfo'
type MockParquetFileWrapper_GetParquetFileInfo_Call[T any] struct {
	*mock.Call
}

// GetParquetFileInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - parquetData []byte
func (_e *MockParquetFileWrapper_Expecter[T]) GetParquetFileInfo(ctx interface{}, parquetData interface{}) *MockParquetFileWrapper_GetParquetFileInfo_Call[T] {
	return &MockParquetFileWrapper_GetParquetFileInfo_Call[T]{Call: _e.mock.On("GetParquetFileInfo", ctx, parquetData)}
}

func (_c *MockParquetFileWrapper_GetParquetFileInfo_Call[T]) Run(run func(ctx context.Context, parquetData []byte)) *MockParquetFileWrapper_GetParquetFileInfo_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParquetFileWrapper_GetParquetFileInfo_Call[T]) Return(parquetFileInfo *entity.ParquetFileInfo, err error) *MockParquetFileWrapper_GetParquetFileInfo_Call[T] {
	_c.Call.Return(parquetFileInfo, err)
	return _c
}

func (_c *MockParquetFileWrapper_GetParquetFileInfo_Call[T]) RunAndReturn(run func(ctx context.Context, parquetData []byte) (*entity.ParquetFileInfo, error)) *MockParquetFileWrapper_GetParquetFileInfo_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetParquetSchema provides a mock function for the type MockParquetFileWrapper
func (_mock *MockParquetFileWrapper[T]) GetParquetSchema(ctx context.Context) (*parquet.Schema, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetParquetSchema")
	}

	var r0 *parquet.Schema
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*parquet.Schema, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *parquet.Schema); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*parquet.Schema)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParquetFileWrapper_GetParquetSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParquetSchema'
type MockParquetFileWrapper_GetParquetSchema_Call[T any] struct {
	*mock.Call
}

// GetParquetSchema is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockParquetFileWrapper_Expecter[T]) GetParquetSchema(ctx interface{}) *MockParquetFileWrapper_GetParquetSchema_Call[T] {
	return &MockParquetFileWrapper_GetParquetSchema_Call[T]{Call: _e.mock.On("GetParquetSchema", ctx)}
}

func (_c *MockParquetFileWrapper_GetParquetSchema_Call[T]) Run(run func(ctx context.Context)) *MockParquetFileWrapper_GetParquetSchema_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParquetFileWrapper_GetParquetSchema_Call[T]) Return(schema *parquet.Schema, err error) *MockParquetFileWrapper_GetParquetSchema_Call[T] {
	_c.Call.Return(schema, err)
	return _c
}

func (_c *MockParquetFileWrapper_GetParquetSchema_Call[T]) RunAndReturn(run func(ctx context.Context) (*parquet.Schema, error)) *MockParquetFileWrapper_GetParquetSchema_Call[T] {
	_c.Call.Return(run)
	return _c
}

// ReadStructsFromParquet provides a mock function for the type MockParquetFileWrapper
func (_mock *MockParquetFileWrapper[T]) ReadStructsFromParquet(ctx context.Context, parquetData []byte) ([]T, error) {
	ret := _mock.Called(ctx, parquetData)

	if len(ret) == 0 {
		panic("no return value specified for ReadStructsFromParquet")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) ([]T, error)); ok {
		return returnFunc(ctx, parquetData)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) []T); ok {
		r0 = returnFunc(ctx, parquetData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, parquetData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParquetFileWrapper_ReadStructsFromParquet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadStructsFromParquet'
type MockParquetFileWrapper_ReadStructsFromParquet_Call[T any] struct {
	*mock.Call
}

// ReadStructsFromParquet is a helper method to define mock.On call
//   - ctx context.Context
//   - parquetData []byte
func (_e *MockParquetFileWrapper_Expecter[T]) ReadStructsFromParquet(ctx interface{}, parquetData interface{}) *MockParquetFileWrapper_ReadStructsFromParquet_Call[T] {
	return &MockParquetFileWrapper_ReadStructsFromParquet_Call[T]{Call: _e.mock.On("ReadStructsFromParquet", ctx, parquetData)}
}

func (_c *MockParquetFileWrapper_ReadStructsFromParquet_Call[T]) Run(run func(ctx context.Context, parquetData []byte)) *MockParquetFileWrapper_ReadStructsFromParquet_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParquetFileWrapper_ReadStructsFromParquet_Call[T]) Return(vs []T, err error) *MockParquetFileWrapper_ReadStructsFromParquet_Call[T] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockParquetFileWrapper_ReadStructsFromParquet_Call[T]) RunAndReturn(run func(ctx context.Context, parquetData []byte) ([]T, error)) *MockParquetFileWrapper_ReadStructsFromParquet_Call[T] {
	_c.Call.Return(run)
	return _c
}

// ValidateStruct provides a mock function for the type MockParquetFileWrapper
func (_mock *MockParquetFileWrapper[T]) ValidateStruct(ctx context.Context, data T) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for ValidateStruct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockParquetFileWrapper_ValidateStruct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateStruct'
type MockParquetFileWrapper_ValidateStruct_Call[T any] struct {
	*mock.Call
}

// ValidateStruct is a helper method to define mock.On call
//   - ctx context.Context
//   - data T
func (_e *MockParquetFileWrapper_Expecter[T]) ValidateStruct(ctx interface{}, data interface{}) *MockParquetFileWrapper_ValidateStruct_Call[T] {
	return &MockParquetFileWrapper_ValidateStruct_Call[T]{Call: _e.mock.On("ValidateStruct", ctx, data)}
}

func (_c *MockParquetFileWrapper_ValidateStruct_Call[T]) Run(run func(ctx context.Context, data T)) *MockParquetFileWrapper_ValidateStruct_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParquetFileWrapper_ValidateStruct_Call[T]) Return(err error) *MockParquetFileWrapper_ValidateStruct_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockParquetFileWrapper_ValidateStruct_Call[T]) RunAndReturn(run func(ctx context.Context, data T) error) *MockParquetFileWrapper_ValidateStruct_Call[T] {
	_c.Call.Return(run)
	return _c
}

// WriteStructToParquet provides a mock function for the type MockParquetFileWrapper
func (_mock *MockParquetFileWrapper[T]) WriteStructToParquet(ctx context.Context, data T) ([]byte, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteStructToParquet")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) ([]byte, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) []byte); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, T) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParquetFileWrapper_WriteStructToParquet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteStructToParquet'
type MockParquetFileWrapper_WriteStructToParquet_Call[T any] struct {
	*mock.Call
}

// WriteStructToParquet is a helper method to define mock.On call
//   - ctx context.Context
//   - data T
func (_e *MockParquetFileWrapper_Expecter[T]) WriteStructToParquet(ctx interface{}, data interface{}) *MockParquetFileWrapper_WriteStructToParquet_Call[T] {
	return &MockParquetFileWrapper_WriteStructToParquet_Call[T]{Call: _e.mock.On("WriteStructToParquet", ctx, data)}
}

func (_c *MockParquetFileWrapper_WriteStructToParquet_Call[T]) Run(run func(ctx context.Context, data T)) *MockParquetFileWrapper_WriteStructToParquet_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParquetFileWrapper_WriteStructToParquet_Call[T]) Return(bytes []byte, err error) *MockParquetFileWrapper_WriteStructToParquet_Call[T] {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockParquetFileWrapper_WriteStructToParquet_Call[T]) RunAndReturn(run func(ctx context.Context, data T) ([]byte, error)) *MockParquetFileWrapper_WriteStructToParquet_Call[T] {
	_c.Call.Return(run)
	return _c
}

// WriteStructsToParquet provides a mock function for the type MockParquetFileWrapper
func (_mock *MockParquetFileWrapper[T]) WriteStructsToParquet(ctx context.Context, data []T) ([]byte, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteStructsToParquet")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []T) ([]byte, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []T) []byte); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []T) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParquetFileWrapper_WriteStructsToParquet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteStructsToParquet'
type MockParquetFileWrapper_WriteStructsToParquet_Call[T any] struct {
	*mock.Call
}

// WriteStructsToParquet is a helper method to define mock.On call
//   - ctx context.Context
//   - data []T
func (_e *MockParquetFileWrapper_Expecter[T]) WriteStructsToParquet(ctx interface{}, data interface{}) *MockParquetFileWrapper_WriteStructsToParquet_Call[T] {
	return &MockParquetFileWrapper_WriteStructsToParquet_Call[T]{Call: _e.mock.On("WriteStructsToParquet", ctx, data)}
}

func (_c *MockParquetFileWrapper_WriteStructsToParquet_Call[T]) Run(run func(ctx context.Context, data []T)) *MockParquetFileWrapper_WriteStructsToParquet_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []T
		if args[1] != nil {
			arg1 = args[1].([]T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParquetFileWrapper_WriteStructsToParquet_Call[T]) Return(bytes []byte, err error) *MockParquetFileWrapper_WriteStructsToParquet_Call[T] {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockParquetFileWrapper_WriteStructsToParquet_Call[T]) RunAndReturn(run func(ctx context.Context, data []T) ([]byte, error)) *MockParquetFileWrapper_WriteStructsToParquet_Call[T] {
	_c.Call.Return(run)
	return _c
}
