// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockS3StorageWrapper creates a new instance of MockS3StorageWrapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3StorageWrapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3StorageWrapper {
	mock := &MockS3StorageWrapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockS3StorageWrapper is an autogenerated mock type for the S3StorageWrapper type
type MockS3StorageWrapper struct {
	mock.Mock
}

type MockS3StorageWrapper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3StorageWrapper) EXPECT() *MockS3StorageWrapper_Expecter {
	return &MockS3StorageWrapper_Expecter{mock: &_m.Mock}
}

// DeleteParquetFile provides a mock function for the type MockS3StorageWrapper
func (_mock *MockS3StorageWrapper) DeleteParquetFile(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteParquetFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockS3StorageWrapper_DeleteParquetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteParquetFile'
type MockS3StorageWrapper_DeleteParquetFile_Call struct {
	*mock.Call
}

// DeleteParquetFile is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockS3StorageWrapper_Expecter) DeleteParquetFile(ctx interface{}, key interface{}) *MockS3StorageWrapper_DeleteParquetFile_Call {
	return &MockS3StorageWrapper_DeleteParquetFile_Call{Call: _e.mock.On("DeleteParquetFile", ctx, key)}
}

func (_c *MockS3StorageWrapper_DeleteParquetFile_Call) Run(run func(ctx context.Context, key string)) *MockS3StorageWrapper_DeleteParquetFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockS3StorageWrapper_DeleteParquetFile_Call) Return(err error) *MockS3StorageWrapper_DeleteParquetFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockS3StorageWrapper_DeleteParquetFile_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockS3StorageWrapper_DeleteParquetFile_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadParquetFile provides a mock function for the type MockS3StorageWrapper
func (_mock *MockS3StorageWrapper) DownloadParquetFile(ctx context.Context, key string) ([]byte, map[string]string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DownloadParquetFile")
	}

	var r0 []byte
	var r1 map[string]string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, map[string]string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) map[string]string); ok {
		r1 = returnFunc(ctx, key)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, key)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockS3StorageWrapper_DownloadParquetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadParquetFile'
type MockS3StorageWrapper_DownloadParquetFile_Call struct {
	*mock.Call
}

// DownloadParquetFile is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockS3StorageWrapper_Expecter) DownloadParquetFile(ctx interface{}, key interface{}) *MockS3StorageWrapper_DownloadParquetFile_Call {
	return &MockS3StorageWrapper_DownloadParquetFile_Call{Call: _e.mock.On("DownloadParquetFile", ctx, key)}
}

func (_c *MockS3StorageWrapper_DownloadParquetFile_Call) Run(run func(ctx context.Context, key string)) *MockS3StorageWrapper_DownloadParquetFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockS3StorageWrapper_DownloadParquetFile_Call) Return(bytes []byte, stringToString map[string]string, err error) *MockS3StorageWrapper_DownloadParquetFile_Call {
	_c.Call.Return(bytes, stringToString, err)
	return _c
}

func (_c *MockS3StorageWrapper_DownloadParquetFile_Call) RunAndReturn(run func(ctx context.Context, key string) ([]byte, map[string]string, error)) *MockS3StorageWrapper_DownloadParquetFile_Call {
	_c.Call.Return(run)
	return _c
}

// FileExists provides a mock function for the type MockS3StorageWrapper
func (_mock *MockS3StorageWrapper) FileExists(ctx context.Context, key string) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for FileExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3StorageWrapper_FileExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileExists'
type MockS3StorageWrapper_FileExists_Call struct {
	*mock.Call
}

// FileExists is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockS3StorageWrapper_Expecter) FileExists(ctx interface{}, key interface{}) *MockS3StorageWrapper_FileExists_Call {
	return &MockS3StorageWrapper_FileExists_Call{Call: _e.mock.On("FileExists", ctx, key)}
}

func (_c *MockS3StorageWrapper_FileExists_Call) Run(run func(ctx context.Context, key string)) *MockS3StorageWrapper_FileExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockS3StorageWrapper_FileExists_Call) Return(b bool, err error) *MockS3StorageWrapper_FileExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockS3StorageWrapper_FileExists_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, error)) *MockS3StorageWrapper_FileExists_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileSize provides a mock function for the type MockS3StorageWrapper
func (_mock *MockS3StorageWrapper) GetFileSize(ctx context.Context, key string) (int64, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetFileSize")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3StorageWrapper_GetFileSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileSize'
type MockS3StorageWrapper_GetFileSize_Call struct {
	*mock.Call
}

// GetFileSize is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockS3StorageWrapper_Expecter) GetFileSize(ctx interface{}, key interface{}) *MockS3StorageWrapper_GetFileSize_Call {
	return &MockS3StorageWrapper_GetFileSize_Call{Call: _e.mock.On("GetFileSize", ctx, key)}
}

func (_c *MockS3StorageWrapper_GetFileSize_Call) Run(run func(ctx context.Context, key string)) *MockS3StorageWrapper_GetFileSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockS3StorageWrapper_GetFileSize_Call) Return(n int64, err error) *MockS3StorageWrapper_GetFileSize_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockS3StorageWrapper_GetFileSize_Call) RunAndReturn(run func(ctx context.Context, key string) (int64, error)) *MockS3StorageWrapper_GetFileSize_Call {
	_c.Call.Return(run)
	return _c
}

// ListParquetFiles provides a mock function for the type MockS3StorageWrapper
func (_mock *MockS3StorageWrapper) ListParquetFiles(ctx context.Context, prefix string) ([]string, error) {
	ret := _mock.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for ListParquetFiles")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, prefix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prefix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3StorageWrapper_ListParquetFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParquetFiles'
type MockS3StorageWrapper_ListParquetFiles_Call struct {
	*mock.Call
}

// ListParquetFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
func (_e *MockS3StorageWrapper_Expecter) ListParquetFiles(ctx interface{}, prefix interface{}) *MockS3StorageWrapper_ListParquetFiles_Call {
	return &MockS3StorageWrapper_ListParquetFiles_Call{Call: _e.mock.On("ListParquetFiles", ctx, prefix)}
}

func (_c *MockS3StorageWrapper_ListParquetFiles_Call) Run(run func(ctx context.Context, prefix string)) *MockS3StorageWrapper_ListParquetFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockS3StorageWrapper_ListParquetFiles_Call) Return(strings []string, err error) *MockS3StorageWrapper_ListParquetFiles_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockS3StorageWrapper_ListParquetFiles_Call) RunAndReturn(run func(ctx context.Context, prefix string) ([]string, error)) *MockS3StorageWrapper_ListParquetFiles_Call {
	_c.Call.Return(run)
	return _c
}

// UploadParquetFile provides a mock function for the type MockS3StorageWrapper
func (_mock *MockS3StorageWrapper) UploadParquetFile(ctx context.Context, key string, data []byte, metadata map[string]string) error {
	ret := _mock.Called(ctx, key, data, metadata)

	if len(ret) == 0 {
		panic("no return value specified for UploadParquetFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, map[string]string) error); ok {
		r0 = returnFunc(ctx, key, data, metadata)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockS3StorageWrapper_UploadParquetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadParquetFile'
type MockS3StorageWrapper_UploadParquetFile_Call struct {
	*mock.Call
}

// UploadParquetFile is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - data []byte
//   - metadata map[string]string
func (_e *MockS3StorageWrapper_Expecter) UploadParquetFile(ctx interface{}, key interface{}, data interface{}, metadata interface{}) *MockS3StorageWrapper_UploadParquetFile_Call {
	return &MockS3StorageWrapper_UploadParquetFile_Call{Call: _e.mock.On("UploadParquetFile", ctx, key, data, metadata)}
}

func (_c *MockS3StorageWrapper_UploadParquetFile_Call) Run(run func(ctx context.Context, key string, data []byte, metadata map[string]string)) *MockS3StorageWrapper_UploadParquetFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 map[string]string
		if args[3] != nil {
			arg3 = args[3].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockS3StorageWrapper_UploadParquetFile_Call) Return(err error) *MockS3StorageWrapper_UploadParquetFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockS3StorageWrapper_UploadParquetFile_Call) RunAndReturn(run func(ctx context.Context, key string, data []byte, metadata map[string]string) error) *MockS3StorageWrapper_UploadParquetFile_Call {
	_c.Call.Return(run)
	return _c
}
