// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/autotester/domain/entity"
)

// NewMockChatStorageRepository creates a new instance of MockChatStorageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatStorageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatStorageRepository {
	mock := &MockChatStorageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatStorageRepository is an autogenerated mock type for the ChatStorageRepository type
type MockChatStorageRepository struct {
	mock.Mock
}

type MockChatStorageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatStorageRepository) EXPECT() *MockChatStorageRepository_Expecter {
	return &MockChatStorageRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockChatStorageRepository
func (_mock *MockChatStorageRepository) Create(ctx context.Context, obj *entity.Chat) error {
	ret := _mock.Called(ctx, obj)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Chat) error); ok {
		r0 = returnFunc(ctx, obj)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatStorageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockChatStorageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - obj *entity.Chat
func (_e *MockChatStorageRepository_Expecter) Create(ctx interface{}, obj interface{}) *MockChatStorageRepository_Create_Call {
	return &MockChatStorageRepository_Create_Call{Call: _e.mock.On("Create", ctx, obj)}
}

func (_c *MockChatStorageRepository_Create_Call) Run(run func(ctx context.Context, obj *entity.Chat)) *MockChatStorageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Chat
		if args[1] != nil {
			arg1 = args[1].(*entity.Chat)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatStorageRepository_Create_Call) Return(err error) *MockChatStorageRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatStorageRepository_Create_Call) RunAndReturn(run func(ctx context.Context, obj *entity.Chat) error) *MockChatStorageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockChatStorageRepository
func (_mock *MockChatStorageRepository) Delete(ctx context.Context, chatId string) error {
	ret := _mock.Called(ctx, chatId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, chatId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatStorageRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockChatStorageRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - chatId string
func (_e *MockChatStorageRepository_Expecter) Delete(ctx interface{}, chatId interface{}) *MockChatStorageRepository_Delete_Call {
	return &MockChatStorageRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, chatId)}
}

func (_c *MockChatStorageRepository_Delete_Call) Run(run func(ctx context.Context, chatId string)) *MockChatStorageRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatStorageRepository_Delete_Call) Return(err error) *MockChatStorageRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatStorageRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, chatId string) error) *MockChatStorageRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function for the type MockChatStorageRepository
func (_mock *MockChatStorageRepository) ListAll(ctx context.Context) ([]*entity.ChatSummary, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []*entity.ChatSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.ChatSummary, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.ChatSummary); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ChatSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatStorageRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockChatStorageRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockChatStorageRepository_Expecter) ListAll(ctx interface{}) *MockChatStorageRepository_ListAll_Call {
	return &MockChatStorageRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx)}
}

func (_c *MockChatStorageRepository_ListAll_Call) Run(run func(ctx context.Context)) *MockChatStorageRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatStorageRepository_ListAll_Call) Return(chatSummarys []*entity.ChatSummary, err error) *MockChatStorageRepository_ListAll_Call {
	_c.Call.Return(chatSummarys, err)
	return _c
}

func (_c *MockChatStorageRepository_ListAll_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.ChatSummary, error)) *MockChatStorageRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockChatStorageRepository
func (_mock *MockChatStorageRepository) Read(ctx context.Context, chatId string) (*entity.Chat, error) {
	ret := _mock.Called(ctx, chatId)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *entity.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Chat, error)); ok {
		return returnFunc(ctx, chatId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Chat); ok {
		r0 = returnFunc(ctx, chatId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Chat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, chatId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatStorageRepository_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockChatStorageRepository_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - chatId string
func (_e *MockChatStorageRepository_Expecter) Read(ctx interface{}, chatId interface{}) *MockChatStorageRepository_Read_Call {
	return &MockChatStorageRepository_Read_Call{Call: _e.mock.On("Read", ctx, chatId)}
}

func (_c *MockChatStorageRepository_Read_Call) Run(run func(ctx context.Context, chatId string)) *MockChatStorageRepository_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatStorageRepository_Read_Call) Return(chat *entity.Chat, err error) *MockChatStorageRepository_Read_Call {
	_c.Call.Return(chat, err)
	return _c
}

func (_c *MockChatStorageRepository_Read_Call) RunAndReturn(run func(ctx context.Context, chatId string) (*entity.Chat, error)) *MockChatStorageRepository_Read_Call {
	_c.Call.Return(run)
	return _c
}
