// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/autotester/domain/entity"
)

// NewMockGroupStorage creates a new instance of MockGroupStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupStorage {
	mock := &MockGroupStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGroupStorage is an autogenerated mock type for the GroupStorage type
type MockGroupStorage struct {
	mock.Mock
}

type MockGroupStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupStorage) EXPECT() *MockGroupStorage_Expecter {
	return &MockGroupStorage_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockGroupStorage
func (_mock *MockGroupStorage) Create(ctx context.Context, obj *entity.Group) error {
	ret := _mock.Called(ctx, obj)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Group) error); ok {
		r0 = returnFunc(ctx, obj)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupStorage_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGroupStorage_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - obj *entity.Group
func (_e *MockGroupStorage_Expecter) Create(ctx interface{}, obj interface{}) *MockGroupStorage_Create_Call {
	return &MockGroupStorage_Create_Call{Call: _e.mock.On("Create", ctx, obj)}
}

func (_c *MockGroupStorage_Create_Call) Run(run func(ctx context.Context, obj *entity.Group)) *MockGroupStorage_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Group
		if args[1] != nil {
			arg1 = args[1].(*entity.Group)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupStorage_Create_Call) Return(err error) *MockGroupStorage_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupStorage_Create_Call) RunAndReturn(run func(ctx context.Context, obj *entity.Group) error) *MockGroupStorage_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockGroupStorage
func (_mock *MockGroupStorage) Delete(ctx context.Context, groupId string) error {
	ret := _mock.Called(ctx, groupId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, groupId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockGroupStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
func (_e *MockGroupStorage_Expecter) Delete(ctx interface{}, groupId interface{}) *MockGroupStorage_Delete_Call {
	return &MockGroupStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, groupId)}
}

func (_c *MockGroupStorage_Delete_Call) Run(run func(ctx context.Context, groupId string)) *MockGroupStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupStorage_Delete_Call) Return(err error) *MockGroupStorage_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupStorage_Delete_Call) RunAndReturn(run func(ctx context.Context, groupId string) error) *MockGroupStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function for the type MockGroupStorage
func (_mock *MockGroupStorage) ListAll(ctx context.Context) ([]*entity.Group, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []*entity.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.Group, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.Group); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupStorage_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockGroupStorage_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGroupStorage_Expecter) ListAll(ctx interface{}) *MockGroupStorage_ListAll_Call {
	return &MockGroupStorage_ListAll_Call{Call: _e.mock.On("ListAll", ctx)}
}

func (_c *MockGroupStorage_ListAll_Call) Run(run func(ctx context.Context)) *MockGroupStorage_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGroupStorage_ListAll_Call) Return(groups []*entity.Group, err error) *MockGroupStorage_ListAll_Call {
	_c.Call.Return(groups, err)
	return _c
}

func (_c *MockGroupStorage_ListAll_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.Group, error)) *MockGroupStorage_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockGroupStorage
func (_mock *MockGroupStorage) Read(ctx context.Context, groupId string) (*entity.Group, error) {
	ret := _mock.Called(ctx, groupId)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *entity.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Group, error)); ok {
		return returnFunc(ctx, groupId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Group); ok {
		r0 = returnFunc(ctx, groupId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, groupId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupStorage_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockGroupStorage_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
func (_e *MockGroupStorage_Expecter) Read(ctx interface{}, groupId interface{}) *MockGroupStorage_Read_Call {
	return &MockGroupStorage_Read_Call{Call: _e.mock.On("Read", ctx, groupId)}
}

func (_c *MockGroupStorage_Read_Call) Run(run func(ctx context.Context, groupId string)) *MockGroupStorage_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupStorage_Read_Call) Return(group *entity.Group, err error) *MockGroupStorage_Read_Call {
	_c.Call.Return(group, err)
	return _c
}

func (_c *MockGroupStorage_Read_Call) RunAndReturn(run func(ctx context.Context, groupId string) (*entity.Group, error)) *MockGroupStorage_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockGroupStorage
func (_mock *MockGroupStorage) Update(ctx context.Context, obj *entity.Group) error {
	ret := _mock.Called(ctx, obj)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Group) error); ok {
		r0 = returnFunc(ctx, obj)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupStorage_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockGroupStorage_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - obj *entity.Group
func (_e *MockGroupStorage_Expecter) Update(ctx interface{}, obj interface{}) *MockGroupStorage_Update_Call {
	return &MockGroupStorage_Update_Call{Call: _e.mock.On("Update", ctx, obj)}
}

func (_c *MockGroupStorage_Update_Call) Run(run func(ctx context.Context, obj *entity.Group)) *MockGroupStorage_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Group
		if args[1] != nil {
			arg1 = args[1].(*entity.Group)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupStorage_Update_Call) Return(err error) *MockGroupStorage_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupStorage_Update_Call) RunAndReturn(run func(ctx context.Context, obj *entity.Group) error) *MockGroupStorage_Update_Call {
	_c.Call.Return(run)
	return _c
}
