// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/autotester/domain/entity"
)

// NewMockMediaFileSystem creates a new instance of MockMediaFileSystem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaFileSystem(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaFileSystem {
	mock := &MockMediaFileSystem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMediaFileSystem is an autogenerated mock type for the MediaFileSystem type
type MockMediaFileSystem struct {
	mock.Mock
}

type MockMediaFileSystem_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaFileSystem) EXPECT() *MockMediaFileSystem_Expecter {
	return &MockMediaFileSystem_Expecter{mock: &_m.Mock}
}

// GetScreenshotUrl provides a mock function for the type MockMediaFileSystem
func (_mock *MockMediaFileSystem) GetScreenshotUrl(ctx context.Context, testId string) (string, error) {
	ret := _mock.Called(ctx, testId)

	if len(ret) == 0 {
		panic("no return value specified for GetScreenshotUrl")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, testId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, testId)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, testId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaFileSystem_GetScreenshotUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScreenshotUrl'
type MockMediaFileSystem_GetScreenshotUrl_Call struct {
	*mock.Call
}

// GetScreenshotUrl is a helper method to define mock.On call
//   - ctx context.Context
//   - testId string
func (_e *MockMediaFileSystem_Expecter) GetScreenshotUrl(ctx interface{}, testId interface{}) *MockMediaFileSystem_GetScreenshotUrl_Call {
	return &MockMediaFileSystem_GetScreenshotUrl_Call{Call: _e.mock.On("GetScreenshotUrl", ctx, testId)}
}

func (_c *MockMediaFileSystem_GetScreenshotUrl_Call) Run(run func(ctx context.Context, testId string)) *MockMediaFileSystem_GetScreenshotUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaFileSystem_GetScreenshotUrl_Call) Return(s string, err error) *MockMediaFileSystem_GetScreenshotUrl_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockMediaFileSystem_GetScreenshotUrl_Call) RunAndReturn(run func(ctx context.Context, testId string) (string, error)) *MockMediaFileSystem_GetScreenshotUrl_Call {
	_c.Call.Return(run)
	return _c
}

// GetVideoUrl provides a mock function for the type MockMediaFileSystem
func (_mock *MockMediaFileSystem) GetVideoUrl(ctx context.Context, testId string) (string, error) {
	ret := _mock.Called(ctx, testId)

	if len(ret) == 0 {
		panic("no return value specified for GetVideoUrl")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, testId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, testId)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, testId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaFileSystem_GetVideoUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVideoUrl'
type MockMediaFileSystem_GetVideoUrl_Call struct {
	*mock.Call
}

// GetVideoUrl is a helper method to define mock.On call
//   - ctx context.Context
//   - testId string
func (_e *MockMediaFileSystem_Expecter) GetVideoUrl(ctx interface{}, testId interface{}) *MockMediaFileSystem_GetVideoUrl_Call {
	return &MockMediaFileSystem_GetVideoUrl_Call{Call: _e.mock.On("GetVideoUrl", ctx, testId)}
}

func (_c *MockMediaFileSystem_GetVideoUrl_Call) Run(run func(ctx context.Context, testId string)) *MockMediaFileSystem_GetVideoUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaFileSystem_GetVideoUrl_Call) Return(s string, err error) *MockMediaFileSystem_GetVideoUrl_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockMediaFileSystem_GetVideoUrl_Call) RunAndReturn(run func(ctx context.Context, testId string) (string, error)) *MockMediaFileSystem_GetVideoUrl_Call {
	_c.Call.Return(run)
	return _c
}

// HasScreenshot provides a mock function for the type MockMediaFileSystem
func (_mock *MockMediaFileSystem) HasScreenshot(ctx context.Context, testId string) bool {
	ret := _mock.Called(ctx, testId)

	if len(ret) == 0 {
		panic("no return value specified for HasScreenshot")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, testId)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockMediaFileSystem_HasScreenshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasScreenshot'
type MockMediaFileSystem_HasScreenshot_Call struct {
	*mock.Call
}

// HasScreenshot is a helper method to define mock.On call
//   - ctx context.Context
//   - testId string
func (_e *MockMediaFileSystem_Expecter) HasScreenshot(ctx interface{}, testId interface{}) *MockMediaFileSystem_HasScreenshot_Call {
	return &MockMediaFileSystem_HasScreenshot_Call{Call: _e.mock.On("HasScreenshot", ctx, testId)}
}

func (_c *MockMediaFileSystem_HasScreenshot_Call) Run(run func(ctx context.Context, testId string)) *MockMediaFileSystem_HasScreenshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaFileSystem_HasScreenshot_Call) Return(b bool) *MockMediaFileSystem_HasScreenshot_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockMediaFileSystem_HasScreenshot_Call) RunAndReturn(run func(ctx context.Context, testId string) bool) *MockMediaFileSystem_HasScreenshot_Call {
	_c.Call.Return(run)
	return _c
}

// HasVideo provides a mock function for the type MockMediaFileSystem
func (_mock *MockMediaFileSystem) HasVideo(ctx context.Context, testId string) bool {
	ret := _mock.Called(ctx, testId)

	if len(ret) == 0 {
		panic("no return value specified for HasVideo")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, testId)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockMediaFileSystem_HasVideo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasVideo'
type MockMediaFileSystem_HasVideo_Call struct {
	*mock.Call
}

// HasVideo is a helper method to define mock.On call
//   - ctx context.Context
//   - testId string
func (_e *MockMediaFileSystem_Expecter) HasVideo(ctx interface{}, testId interface{}) *MockMediaFileSystem_HasVideo_Call {
	return &MockMediaFileSystem_HasVideo_Call{Call: _e.mock.On("HasVideo", ctx, testId)}
}

func (_c *MockMediaFileSystem_HasVideo_Call) Run(run func(ctx context.Context, testId string)) *MockMediaFileSystem_HasVideo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaFileSystem_HasVideo_Call) Return(b bool) *MockMediaFileSystem_HasVideo_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockMediaFileSystem_HasVideo_Call) RunAndReturn(run func(ctx context.Context, testId string) bool) *MockMediaFileSystem_HasVideo_Call {
	_c.Call.Return(run)
	return _c
}

// UploadMedia provides a mock function for the type MockMediaFileSystem
func (_mock *MockMediaFileSystem) UploadMedia(ctx context.Context, testId string, file entity.File) error {
	ret := _mock.Called(ctx, testId, file)

	if len(ret) == 0 {
		panic("no return value specified for UploadMedia")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.File) error); ok {
		r0 = returnFunc(ctx, testId, file)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMediaFileSystem_UploadMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadMedia'
type MockMediaFileSystem_UploadMedia_Call struct {
	*mock.Call
}

// UploadMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - testId string
//   - file entity.File
func (_e *MockMediaFileSystem_Expecter) UploadMedia(ctx interface{}, testId interface{}, file interface{}) *MockMediaFileSystem_UploadMedia_Call {
	return &MockMediaFileSystem_UploadMedia_Call{Call: _e.mock.On("UploadMedia", ctx, testId, file)}
}

func (_c *MockMediaFileSystem_UploadMedia_Call) Run(run func(ctx context.Context, testId string, file entity.File)) *MockMediaFileSystem_UploadMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entity.File
		if args[2] != nil {
			arg2 = args[2].(entity.File)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMediaFileSystem_UploadMedia_Call) Return(err error) *MockMediaFileSystem_UploadMedia_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMediaFileSystem_UploadMedia_Call) RunAndReturn(run func(ctx context.Context, testId string, file entity.File) error) *MockMediaFileSystem_UploadMedia_Call {
	_c.Call.Return(run)
	return _c
}
