// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/autotester/infrastructure/database"
)

// NewMockTokenDatabase creates a new instance of MockTokenDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenDatabase {
	mock := &MockTokenDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenDatabase is an autogenerated mock type for the TokenDatabase type
type MockTokenDatabase struct {
	mock.Mock
}

type MockTokenDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenDatabase) EXPECT() *MockTokenDatabase_Expecter {
	return &MockTokenDatabase_Expecter{mock: &_m.Mock}
}

// ReadToken provides a mock function for the type MockTokenDatabase
func (_mock *MockTokenDatabase) ReadToken(ctx context.Context, userID string) (database.RefreshToken, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ReadToken")
	}

	var r0 database.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (database.RefreshToken, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) database.RefreshToken); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(database.RefreshToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenDatabase_ReadToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadToken'
type MockTokenDatabase_ReadToken_Call struct {
	*mock.Call
}

// ReadToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTokenDatabase_Expecter) ReadToken(ctx interface{}, userID interface{}) *MockTokenDatabase_ReadToken_Call {
	return &MockTokenDatabase_ReadToken_Call{Call: _e.mock.On("ReadToken", ctx, userID)}
}

func (_c *MockTokenDatabase_ReadToken_Call) Run(run func(ctx context.Context, userID string)) *MockTokenDatabase_ReadToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenDatabase_ReadToken_Call) Return(refreshToken database.RefreshToken, err error) *MockTokenDatabase_ReadToken_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockTokenDatabase_ReadToken_Call) RunAndReturn(run func(ctx context.Context, userID string) (database.RefreshToken, error)) *MockTokenDatabase_ReadToken_Call {
	_c.Call.Return(run)
	return _c
}

// ReadTokenByToken provides a mock function for the type MockTokenDatabase
func (_mock *MockTokenDatabase) ReadTokenByToken(ctx context.Context, token string) (database.RefreshToken, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ReadTokenByToken")
	}

	var r0 database.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (database.RefreshToken, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) database.RefreshToken); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(database.RefreshToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenDatabase_ReadTokenByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadTokenByToken'
type MockTokenDatabase_ReadTokenByToken_Call struct {
	*mock.Call
}

// ReadTokenByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenDatabase_Expecter) ReadTokenByToken(ctx interface{}, token interface{}) *MockTokenDatabase_ReadTokenByToken_Call {
	return &MockTokenDatabase_ReadTokenByToken_Call{Call: _e.mock.On("ReadTokenByToken", ctx, token)}
}

func (_c *MockTokenDatabase_ReadTokenByToken_Call) Run(run func(ctx context.Context, token string)) *MockTokenDatabase_ReadTokenByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenDatabase_ReadTokenByToken_Call) Return(refreshToken database.RefreshToken, err error) *MockTokenDatabase_ReadTokenByToken_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockTokenDatabase_ReadTokenByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (database.RefreshToken, error)) *MockTokenDatabase_ReadTokenByToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertToken provides a mock function for the type MockTokenDatabase
func (_mock *MockTokenDatabase) UpsertToken(ctx context.Context, arg database.UpsertTokenParams) (database.RefreshToken, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertToken")
	}

	var r0 database.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.UpsertTokenParams) (database.RefreshToken, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.UpsertTokenParams) database.RefreshToken); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.RefreshToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, database.UpsertTokenParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenDatabase_UpsertToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertToken'
type MockTokenDatabase_UpsertToken_Call struct {
	*mock.Call
}

// UpsertToken is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.UpsertTokenParams
func (_e *MockTokenDatabase_Expecter) UpsertToken(ctx interface{}, arg interface{}) *MockTokenDatabase_UpsertToken_Call {
	return &MockTokenDatabase_UpsertToken_Call{Call: _e.mock.On("UpsertToken", ctx, arg)}
}

func (_c *MockTokenDatabase_UpsertToken_Call) Run(run func(ctx context.Context, arg database.UpsertTokenParams)) *MockTokenDatabase_UpsertToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.UpsertTokenParams
		if args[1] != nil {
			arg1 = args[1].(database.UpsertTokenParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenDatabase_UpsertToken_Call) Return(refreshToken database.RefreshToken, err error) *MockTokenDatabase_UpsertToken_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockTokenDatabase_UpsertToken_Call) RunAndReturn(run func(ctx context.Context, arg database.UpsertTokenParams) (database.RefreshToken, error)) *MockTokenDatabase_UpsertToken_Call {
	_c.Call.Return(run)
	return _c
}
