// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFileSystem creates a new instance of MockFileSystem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileSystem(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileSystem {
	mock := &MockFileSystem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileSystem is an autogenerated mock type for the FileSystem type
type MockFileSystem struct {
	mock.Mock
}

type MockFileSystem_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileSystem) EXPECT() *MockFileSystem_Expecter {
	return &MockFileSystem_Expecter{mock: &_m.Mock}
}

// GetFileStats provides a mock function for the type MockFileSystem
func (_mock *MockFileSystem) GetFileStats(path string) (os.FileInfo, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetFileStats")
	}

	var r0 os.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (os.FileInfo, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) os.FileInfo); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileSystem_GetFileStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileStats'
type MockFileSystem_GetFileStats_Call struct {
	*mock.Call
}

// GetFileStats is a helper method to define mock.On call
//   - path string
func (_e *MockFileSystem_Expecter) GetFileStats(path interface{}) *MockFileSystem_GetFileStats_Call {
	return &MockFileSystem_GetFileStats_Call{Call: _e.mock.On("GetFileStats", path)}
}

func (_c *MockFileSystem_GetFileStats_Call) Run(run func(path string)) *MockFileSystem_GetFileStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileSystem_GetFileStats_Call) Return(v os.FileInfo, err error) *MockFileSystem_GetFileStats_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockFileSystem_GetFileStats_Call) RunAndReturn(run func(path string) (os.FileInfo, error)) *MockFileSystem_GetFileStats_Call {
	_c.Call.Return(run)
	return _c
}

// MkdirAll provides a mock function for the type MockFileSystem
func (_mock *MockFileSystem) MkdirAll(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileSystem_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type MockFileSystem_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
func (_e *MockFileSystem_Expecter) MkdirAll(path interface{}) *MockFileSystem_MkdirAll_Call {
	return &MockFileSystem_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path)}
}

func (_c *MockFileSystem_MkdirAll_Call) Run(run func(path string)) *MockFileSystem_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileSystem_MkdirAll_Call) Return(err error) *MockFileSystem_MkdirAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileSystem_MkdirAll_Call) RunAndReturn(run func(path string) error) *MockFileSystem_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDir provides a mock function for the type MockFileSystem
func (_mock *MockFileSystem) ReadDir(path string) ([]string, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileSystem_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type MockFileSystem_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - path string
func (_e *MockFileSystem_Expecter) ReadDir(path interface{}) *MockFileSystem_ReadDir_Call {
	return &MockFileSystem_ReadDir_Call{Call: _e.mock.On("ReadDir", path)}
}

func (_c *MockFileSystem_ReadDir_Call) Run(run func(path string)) *MockFileSystem_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileSystem_ReadDir_Call) Return(strings []string, err error) *MockFileSystem_ReadDir_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockFileSystem_ReadDir_Call) RunAndReturn(run func(path string) ([]string, error)) *MockFileSystem_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function for the type MockFileSystem
func (_mock *MockFileSystem) ReadFile(relativeFilePath string) ([]byte, error) {
	ret := _mock.Called(relativeFilePath)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(relativeFilePath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(relativeFilePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(relativeFilePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileSystem_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockFileSystem_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - relativeFilePath string
func (_e *MockFileSystem_Expecter) ReadFile(relativeFilePath interface{}) *MockFileSystem_ReadFile_Call {
	return &MockFileSystem_ReadFile_Call{Call: _e.mock.On("ReadFile", relativeFilePath)}
}

func (_c *MockFileSystem_ReadFile_Call) Run(run func(relativeFilePath string)) *MockFileSystem_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileSystem_ReadFile_Call) Return(bytes []byte, err error) *MockFileSystem_ReadFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockFileSystem_ReadFile_Call) RunAndReturn(run func(relativeFilePath string) ([]byte, error)) *MockFileSystem_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockFileSystem
func (_mock *MockFileSystem) Remove(path string, recursive bool) error {
	ret := _mock.Called(path, recursive)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, bool) error); ok {
		r0 = returnFunc(path, recursive)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileSystem_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockFileSystem_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - path string
//   - recursive bool
func (_e *MockFileSystem_Expecter) Remove(path interface{}, recursive interface{}) *MockFileSystem_Remove_Call {
	return &MockFileSystem_Remove_Call{Call: _e.mock.On("Remove", path, recursive)}
}

func (_c *MockFileSystem_Remove_Call) Run(run func(path string, recursive bool)) *MockFileSystem_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileSystem_Remove_Call) Return(err error) *MockFileSystem_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileSystem_Remove_Call) RunAndReturn(run func(path string, recursive bool) error) *MockFileSystem_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function for the type MockFileSystem
func (_mock *MockFileSystem) WriteFile(relativeFilePath string, data []byte) error {
	ret := _mock.Called(relativeFilePath, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(relativeFilePath, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileSystem_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockFileSystem_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - relativeFilePath string
//   - data []byte
func (_e *MockFileSystem_Expecter) WriteFile(relativeFilePath interface{}, data interface{}) *MockFileSystem_WriteFile_Call {
	return &MockFileSystem_WriteFile_Call{Call: _e.mock.On("WriteFile", relativeFilePath, data)}
}

func (_c *MockFileSystem_WriteFile_Call) Run(run func(relativeFilePath string, data []byte)) *MockFileSystem_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileSystem_WriteFile_Call) Return(err error) *MockFileSystem_WriteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileSystem_WriteFile_Call) RunAndReturn(run func(relativeFilePath string, data []byte) error) *MockFileSystem_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}
