// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/autotester/domain/entity"
)

// NewMockSessionSummaryStorageRepository creates a new instance of MockSessionSummaryStorageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionSummaryStorageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionSummaryStorageRepository {
	mock := &MockSessionSummaryStorageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionSummaryStorageRepository is an autogenerated mock type for the SessionSummaryStorageRepository type
type MockSessionSummaryStorageRepository struct {
	mock.Mock
}

type MockSessionSummaryStorageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionSummaryStorageRepository) EXPECT() *MockSessionSummaryStorageRepository_Expecter {
	return &MockSessionSummaryStorageRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSessionSummaryStorageRepository
func (_mock *MockSessionSummaryStorageRepository) Create(ctx context.Context, obj *entity.SessionSummary) error {
	ret := _mock.Called(ctx, obj)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.SessionSummary) error); ok {
		r0 = returnFunc(ctx, obj)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionSummaryStorageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionSummaryStorageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - obj *entity.SessionSummary
func (_e *MockSessionSummaryStorageRepository_Expecter) Create(ctx interface{}, obj interface{}) *MockSessionSummaryStorageRepository_Create_Call {
	return &MockSessionSummaryStorageRepository_Create_Call{Call: _e.mock.On("Create", ctx, obj)}
}

func (_c *MockSessionSummaryStorageRepository_Create_Call) Run(run func(ctx context.Context, obj *entity.SessionSummary)) *MockSessionSummaryStorageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.SessionSummary
		if args[1] != nil {
			arg1 = args[1].(*entity.SessionSummary)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionSummaryStorageRepository_Create_Call) Return(err error) *MockSessionSummaryStorageRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionSummaryStorageRepository_Create_Call) RunAndReturn(run func(ctx context.Context, obj *entity.SessionSummary) error) *MockSessionSummaryStorageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSessionSummaryStorageRepository
func (_mock *MockSessionSummaryStorageRepository) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionSummaryStorageRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionSummaryStorageRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockSessionSummaryStorageRepository_Expecter) Delete(ctx interface{}, key interface{}) *MockSessionSummaryStorageRepository_Delete_Call {
	return &MockSessionSummaryStorageRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockSessionSummaryStorageRepository_Delete_Call) Run(run func(ctx context.Context, key string)) *MockSessionSummaryStorageRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionSummaryStorageRepository_Delete_Call) Return(err error) *MockSessionSummaryStorageRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionSummaryStorageRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockSessionSummaryStorageRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function for the type MockSessionSummaryStorageRepository
func (_mock *MockSessionSummaryStorageRepository) ListAll(ctx context.Context) ([]entity.SessionSummary, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []entity.SessionSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entity.SessionSummary, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entity.SessionSummary); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.SessionSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionSummaryStorageRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockSessionSummaryStorageRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSessionSummaryStorageRepository_Expecter) ListAll(ctx interface{}) *MockSessionSummaryStorageRepository_ListAll_Call {
	return &MockSessionSummaryStorageRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx)}
}

func (_c *MockSessionSummaryStorageRepository_ListAll_Call) Run(run func(ctx context.Context)) *MockSessionSummaryStorageRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionSummaryStorageRepository_ListAll_Call) Return(sessionSummarys []entity.SessionSummary, err error) *MockSessionSummaryStorageRepository_ListAll_Call {
	_c.Call.Return(sessionSummarys, err)
	return _c
}

func (_c *MockSessionSummaryStorageRepository_ListAll_Call) RunAndReturn(run func(ctx context.Context) ([]entity.SessionSummary, error)) *MockSessionSummaryStorageRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockSessionSummaryStorageRepository
func (_mock *MockSessionSummaryStorageRepository) Read(ctx context.Context, key string) (*entity.SessionSummary, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *entity.SessionSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.SessionSummary, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.SessionSummary); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SessionSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionSummaryStorageRepository_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockSessionSummaryStorageRepository_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockSessionSummaryStorageRepository_Expecter) Read(ctx interface{}, key interface{}) *MockSessionSummaryStorageRepository_Read_Call {
	return &MockSessionSummaryStorageRepository_Read_Call{Call: _e.mock.On("Read", ctx, key)}
}

func (_c *MockSessionSummaryStorageRepository_Read_Call) Run(run func(ctx context.Context, key string)) *MockSessionSummaryStorageRepository_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionSummaryStorageRepository_Read_Call) Return(sessionSummary *entity.SessionSummary, err error) *MockSessionSummaryStorageRepository_Read_Call {
	_c.Call.Return(sessionSummary, err)
	return _c
}

func (_c *MockSessionSummaryStorageRepository_Read_Call) RunAndReturn(run func(ctx context.Context, key string) (*entity.SessionSummary, error)) *MockSessionSummaryStorageRepository_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockSessionSummaryStorageRepository
func (_mock *MockSessionSummaryStorageRepository) Update(ctx context.Context, obj *entity.SessionSummary, key string) error {
	ret := _mock.Called(ctx, obj, key)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.SessionSummary, string) error); ok {
		r0 = returnFunc(ctx, obj, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionSummaryStorageRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSessionSummaryStorageRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - obj *entity.SessionSummary
//   - key string
func (_e *MockSessionSummaryStorageRepository_Expecter) Update(ctx interface{}, obj interface{}, key interface{}) *MockSessionSummaryStorageRepository_Update_Call {
	return &MockSessionSummaryStorageRepository_Update_Call{Call: _e.mock.On("Update", ctx, obj, key)}
}

func (_c *MockSessionSummaryStorageRepository_Update_Call) Run(run func(ctx context.Context, obj *entity.SessionSummary, key string)) *MockSessionSummaryStorageRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.SessionSummary
		if args[1] != nil {
			arg1 = args[1].(*entity.SessionSummary)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionSummaryStorageRepository_Update_Call) Return(err error) *MockSessionSummaryStorageRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionSummaryStorageRepository_Update_Call) RunAndReturn(run func(ctx context.Context, obj *entity.SessionSummary, key string) error) *MockSessionSummaryStorageRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
