// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/autotester/domain/entity"
)

// NewMockTestCaseStorageRepository creates a new instance of MockTestCaseStorageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestCaseStorageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestCaseStorageRepository {
	mock := &MockTestCaseStorageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTestCaseStorageRepository is an autogenerated mock type for the TestCaseStorageRepository type
type MockTestCaseStorageRepository struct {
	mock.Mock
}

type MockTestCaseStorageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTestCaseStorageRepository) EXPECT() *MockTestCaseStorageRepository_Expecter {
	return &MockTestCaseStorageRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTestCaseStorageRepository
func (_mock *MockTestCaseStorageRepository) Create(ctx context.Context, obj *entity.TestCase) error {
	ret := _mock.Called(ctx, obj)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.TestCase) error); ok {
		r0 = returnFunc(ctx, obj)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTestCaseStorageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTestCaseStorageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - obj *entity.TestCase
func (_e *MockTestCaseStorageRepository_Expecter) Create(ctx interface{}, obj interface{}) *MockTestCaseStorageRepository_Create_Call {
	return &MockTestCaseStorageRepository_Create_Call{Call: _e.mock.On("Create", ctx, obj)}
}

func (_c *MockTestCaseStorageRepository_Create_Call) Run(run func(ctx context.Context, obj *entity.TestCase)) *MockTestCaseStorageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.TestCase
		if args[1] != nil {
			arg1 = args[1].(*entity.TestCase)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestCaseStorageRepository_Create_Call) Return(err error) *MockTestCaseStorageRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTestCaseStorageRepository_Create_Call) RunAndReturn(run func(ctx context.Context, obj *entity.TestCase) error) *MockTestCaseStorageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTestCaseStorageRepository
func (_mock *MockTestCaseStorageRepository) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTestCaseStorageRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTestCaseStorageRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockTestCaseStorageRepository_Expecter) Delete(ctx interface{}, key interface{}) *MockTestCaseStorageRepository_Delete_Call {
	return &MockTestCaseStorageRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockTestCaseStorageRepository_Delete_Call) Run(run func(ctx context.Context, key string)) *MockTestCaseStorageRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestCaseStorageRepository_Delete_Call) Return(err error) *MockTestCaseStorageRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTestCaseStorageRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockTestCaseStorageRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockTestCaseStorageRepository
func (_mock *MockTestCaseStorageRepository) Read(ctx context.Context, key string) (*entity.TestCase, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *entity.TestCase
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.TestCase, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.TestCase); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TestCase)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestCaseStorageRepository_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockTestCaseStorageRepository_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockTestCaseStorageRepository_Expecter) Read(ctx interface{}, key interface{}) *MockTestCaseStorageRepository_Read_Call {
	return &MockTestCaseStorageRepository_Read_Call{Call: _e.mock.On("Read", ctx, key)}
}

func (_c *MockTestCaseStorageRepository_Read_Call) Run(run func(ctx context.Context, key string)) *MockTestCaseStorageRepository_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestCaseStorageRepository_Read_Call) Return(testCase *entity.TestCase, err error) *MockTestCaseStorageRepository_Read_Call {
	_c.Call.Return(testCase, err)
	return _c
}

func (_c *MockTestCaseStorageRepository_Read_Call) RunAndReturn(run func(ctx context.Context, key string) (*entity.TestCase, error)) *MockTestCaseStorageRepository_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTestCaseStorageRepository
func (_mock *MockTestCaseStorageRepository) Update(ctx context.Context, obj *entity.TestCase, key string) error {
	ret := _mock.Called(ctx, obj, key)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.TestCase, string) error); ok {
		r0 = returnFunc(ctx, obj, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTestCaseStorageRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTestCaseStorageRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - obj *entity.TestCase
//   - key string
func (_e *MockTestCaseStorageRepository_Expecter) Update(ctx interface{}, obj interface{}, key interface{}) *MockTestCaseStorageRepository_Update_Call {
	return &MockTestCaseStorageRepository_Update_Call{Call: _e.mock.On("Update", ctx, obj, key)}
}

func (_c *MockTestCaseStorageRepository_Update_Call) Run(run func(ctx context.Context, obj *entity.TestCase, key string)) *MockTestCaseStorageRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.TestCase
		if args[1] != nil {
			arg1 = args[1].(*entity.TestCase)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTestCaseStorageRepository_Update_Call) Return(err error) *MockTestCaseStorageRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTestCaseStorageRepository_Update_Call) RunAndReturn(run func(ctx context.Context, obj *entity.TestCase, key string) error) *MockTestCaseStorageRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
