// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/autotester/domain/entity"
)

// NewMockTestcaseLocalStorageRepository creates a new instance of MockTestcaseLocalStorageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestcaseLocalStorageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestcaseLocalStorageRepository {
	mock := &MockTestcaseLocalStorageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTestcaseLocalStorageRepository is an autogenerated mock type for the TestcaseLocalStorageRepository type
type MockTestcaseLocalStorageRepository struct {
	mock.Mock
}

type MockTestcaseLocalStorageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTestcaseLocalStorageRepository) EXPECT() *MockTestcaseLocalStorageRepository_Expecter {
	return &MockTestcaseLocalStorageRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockTestcaseLocalStorageRepository
func (_mock *MockTestcaseLocalStorageRepository) Delete(testId string, userId string, sessionId string) error {
	ret := _mock.Called(testId, userId, sessionId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(testId, userId, sessionId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTestcaseLocalStorageRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTestcaseLocalStorageRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - testId string
//   - userId string
//   - sessionId string
func (_e *MockTestcaseLocalStorageRepository_Expecter) Delete(testId interface{}, userId interface{}, sessionId interface{}) *MockTestcaseLocalStorageRepository_Delete_Call {
	return &MockTestcaseLocalStorageRepository_Delete_Call{Call: _e.mock.On("Delete", testId, userId, sessionId)}
}

func (_c *MockTestcaseLocalStorageRepository_Delete_Call) Run(run func(testId string, userId string, sessionId string)) *MockTestcaseLocalStorageRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTestcaseLocalStorageRepository_Delete_Call) Return(err error) *MockTestcaseLocalStorageRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTestcaseLocalStorageRepository_Delete_Call) RunAndReturn(run func(testId string, userId string, sessionId string) error) *MockTestcaseLocalStorageRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOlderThan provides a mock function for the type MockTestcaseLocalStorageRepository
func (_mock *MockTestcaseLocalStorageRepository) DeleteOlderThan(maxAge time.Duration) (int, error) {
	ret := _mock.Called(maxAge)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOlderThan")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Duration) (int, error)); ok {
		return returnFunc(maxAge)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Duration) int); ok {
		r0 = returnFunc(maxAge)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(time.Duration) error); ok {
		r1 = returnFunc(maxAge)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestcaseLocalStorageRepository_DeleteOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOlderThan'
type MockTestcaseLocalStorageRepository_DeleteOlderThan_Call struct {
	*mock.Call
}

// DeleteOlderThan is a helper method to define mock.On call
//   - maxAge time.Duration
func (_e *MockTestcaseLocalStorageRepository_Expecter) DeleteOlderThan(maxAge interface{}) *MockTestcaseLocalStorageRepository_DeleteOlderThan_Call {
	return &MockTestcaseLocalStorageRepository_DeleteOlderThan_Call{Call: _e.mock.On("DeleteOlderThan", maxAge)}
}

func (_c *MockTestcaseLocalStorageRepository_DeleteOlderThan_Call) Run(run func(maxAge time.Duration)) *MockTestcaseLocalStorageRepository_DeleteOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestcaseLocalStorageRepository_DeleteOlderThan_Call) Return(n int, err error) *MockTestcaseLocalStorageRepository_DeleteOlderThan_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTestcaseLocalStorageRepository_DeleteOlderThan_Call) RunAndReturn(run func(maxAge time.Duration) (int, error)) *MockTestcaseLocalStorageRepository_DeleteOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// GetTestPath provides a mock function for the type MockTestcaseLocalStorageRepository
func (_mock *MockTestcaseLocalStorageRepository) GetTestPath(testId string, userId string, sessionId string) (string, error) {
	ret := _mock.Called(testId, userId, sessionId)

	if len(ret) == 0 {
		panic("no return value specified for GetTestPath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return returnFunc(testId, userId, sessionId)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = returnFunc(testId, userId, sessionId)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(testId, userId, sessionId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestcaseLocalStorageRepository_GetTestPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTestPath'
type MockTestcaseLocalStorageRepository_GetTestPath_Call struct {
	*mock.Call
}

// GetTestPath is a helper method to define mock.On call
//   - testId string
//   - userId string
//   - sessionId string
func (_e *MockTestcaseLocalStorageRepository_Expecter) GetTestPath(testId interface{}, userId interface{}, sessionId interface{}) *MockTestcaseLocalStorageRepository_GetTestPath_Call {
	return &MockTestcaseLocalStorageRepository_GetTestPath_Call{Call: _e.mock.On("GetTestPath", testId, userId, sessionId)}
}

func (_c *MockTestcaseLocalStorageRepository_GetTestPath_Call) Run(run func(testId string, userId string, sessionId string)) *MockTestcaseLocalStorageRepository_GetTestPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTestcaseLocalStorageRepository_GetTestPath_Call) Return(s string, err error) *MockTestcaseLocalStorageRepository_GetTestPath_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTestcaseLocalStorageRepository_GetTestPath_Call) RunAndReturn(run func(testId string, userId string, sessionId string) (string, error)) *MockTestcaseLocalStorageRepository_GetTestPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetTestPathsBySession provides a mock function for the type MockTestcaseLocalStorageRepository
func (_mock *MockTestcaseLocalStorageRepository) GetTestPathsBySession(userId string, sessionId string) ([]string, error) {
	ret := _mock.Called(userId, sessionId)

	if len(ret) == 0 {
		panic("no return value specified for GetTestPathsBySession")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) ([]string, error)); ok {
		return returnFunc(userId, sessionId)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) []string); ok {
		r0 = returnFunc(userId, sessionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userId, sessionId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestcaseLocalStorageRepository_GetTestPathsBySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTestPathsBySession'
type MockTestcaseLocalStorageRepository_GetTestPathsBySession_Call struct {
	*mock.Call
}

// GetTestPathsBySession is a helper method to define mock.On call
//   - userId string
//   - sessionId string
func (_e *MockTestcaseLocalStorageRepository_Expecter) GetTestPathsBySession(userId interface{}, sessionId interface{}) *MockTestcaseLocalStorageRepository_GetTestPathsBySession_Call {
	return &MockTestcaseLocalStorageRepository_GetTestPathsBySession_Call{Call: _e.mock.On("GetTestPathsBySession", userId, sessionId)}
}

func (_c *MockTestcaseLocalStorageRepository_GetTestPathsBySession_Call) Run(run func(userId string, sessionId string)) *MockTestcaseLocalStorageRepository_GetTestPathsBySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestcaseLocalStorageRepository_GetTestPathsBySession_Call) Return(strings []string, err error) *MockTestcaseLocalStorageRepository_GetTestPathsBySession_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockTestcaseLocalStorageRepository_GetTestPathsBySession_Call) RunAndReturn(run func(userId string, sessionId string) ([]string, error)) *MockTestcaseLocalStorageRepository_GetTestPathsBySession_Call {
	_c.Call.Return(run)
	return _c
}

// GetTestPathsByUser provides a mock function for the type MockTestcaseLocalStorageRepository
func (_mock *MockTestcaseLocalStorageRepository) GetTestPathsByUser(userId string) (map[string][]string, error) {
	ret := _mock.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetTestPathsByUser")
	}

	var r0 map[string][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (map[string][]string, error)); ok {
		return returnFunc(userId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) map[string][]string); ok {
		r0 = returnFunc(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestcaseLocalStorageRepository_GetTestPathsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTestPathsByUser'
type MockTestcaseLocalStorageRepository_GetTestPathsByUser_Call struct {
	*mock.Call
}

// GetTestPathsByUser is a helper method to define mock.On call
//   - userId string
func (_e *MockTestcaseLocalStorageRepository_Expecter) GetTestPathsByUser(userId interface{}) *MockTestcaseLocalStorageRepository_GetTestPathsByUser_Call {
	return &MockTestcaseLocalStorageRepository_GetTestPathsByUser_Call{Call: _e.mock.On("GetTestPathsByUser", userId)}
}

func (_c *MockTestcaseLocalStorageRepository_GetTestPathsByUser_Call) Run(run func(userId string)) *MockTestcaseLocalStorageRepository_GetTestPathsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestcaseLocalStorageRepository_GetTestPathsByUser_Call) Return(stringToStrings map[string][]string, err error) *MockTestcaseLocalStorageRepository_GetTestPathsByUser_Call {
	_c.Call.Return(stringToStrings, err)
	return _c
}

func (_c *MockTestcaseLocalStorageRepository_GetTestPathsByUser_Call) RunAndReturn(run func(userId string) (map[string][]string, error)) *MockTestcaseLocalStorageRepository_GetTestPathsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockTestcaseLocalStorageRepository
func (_mock *MockTestcaseLocalStorageRepository) Save(testcase *entity.TestCase, userId string, sessionId string) error {
	ret := _mock.Called(testcase, userId, sessionId)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entity.TestCase, string, string) error); ok {
		r0 = returnFunc(testcase, userId, sessionId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTestcaseLocalStorageRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockTestcaseLocalStorageRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - testcase *entity.TestCase
//   - userId string
//   - sessionId string
func (_e *MockTestcaseLocalStorageRepository_Expecter) Save(testcase interface{}, userId interface{}, sessionId interface{}) *MockTestcaseLocalStorageRepository_Save_Call {
	return &MockTestcaseLocalStorageRepository_Save_Call{Call: _e.mock.On("Save", testcase, userId, sessionId)}
}

func (_c *MockTestcaseLocalStorageRepository_Save_Call) Run(run func(testcase *entity.TestCase, userId string, sessionId string)) *MockTestcaseLocalStorageRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.TestCase
		if args[0] != nil {
			arg0 = args[0].(*entity.TestCase)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTestcaseLocalStorageRepository_Save_Call) Return(err error) *MockTestcaseLocalStorageRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTestcaseLocalStorageRepository_Save_Call) RunAndReturn(run func(testcase *entity.TestCase, userId string, sessionId string) error) *MockTestcaseLocalStorageRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
