// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/shared/domain/entity"
)

// NewMockOpenAIService creates a new instance of MockOpenAIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOpenAIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOpenAIService {
	mock := &MockOpenAIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOpenAIService is an autogenerated mock type for the OpenAIService type
type MockOpenAIService struct {
	mock.Mock
}

type MockOpenAIService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOpenAIService) EXPECT() *MockOpenAIService_Expecter {
	return &MockOpenAIService_Expecter{mock: &_m.Mock}
}

// Request provides a mock function for the type MockOpenAIService
func (_mock *MockOpenAIService) Request(ctx context.Context, request entity.Request) (*entity.Response, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 *entity.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Request) (*entity.Response, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Request) *entity.Response); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Request) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOpenAIService_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type MockOpenAIService_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
//   - ctx context.Context
//   - request entity.Request
func (_e *MockOpenAIService_Expecter) Request(ctx interface{}, request interface{}) *MockOpenAIService_Request_Call {
	return &MockOpenAIService_Request_Call{Call: _e.mock.On("Request", ctx, request)}
}

func (_c *MockOpenAIService_Request_Call) Run(run func(ctx context.Context, request entity.Request)) *MockOpenAIService_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Request
		if args[1] != nil {
			arg1 = args[1].(entity.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOpenAIService_Request_Call) Return(response *entity.Response, err error) *MockOpenAIService_Request_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockOpenAIService_Request_Call) RunAndReturn(run func(ctx context.Context, request entity.Request) (*entity.Response, error)) *MockOpenAIService_Request_Call {
	_c.Call.Return(run)
	return _c
}
