// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTaglistStorage creates a new instance of MockTaglistStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaglistStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaglistStorage {
	mock := &MockTaglistStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaglistStorage is an autogenerated mock type for the TaglistStorage type
type MockTaglistStorage struct {
	mock.Mock
}

type MockTaglistStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaglistStorage) EXPECT() *MockTaglistStorage_Expecter {
	return &MockTaglistStorage_Expecter{mock: &_m.Mock}
}

// GetTaglist provides a mock function for the type MockTaglistStorage
func (_mock *MockTaglistStorage) GetTaglist(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTaglist")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaglistStorage_GetTaglist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaglist'
type MockTaglistStorage_GetTaglist_Call struct {
	*mock.Call
}

// GetTaglist is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaglistStorage_Expecter) GetTaglist(ctx interface{}) *MockTaglistStorage_GetTaglist_Call {
	return &MockTaglistStorage_GetTaglist_Call{Call: _e.mock.On("GetTaglist", ctx)}
}

func (_c *MockTaglistStorage_GetTaglist_Call) Run(run func(ctx context.Context)) *MockTaglistStorage_GetTaglist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaglistStorage_GetTaglist_Call) Return(strings []string, err error) *MockTaglistStorage_GetTaglist_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockTaglistStorage_GetTaglist_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockTaglistStorage_GetTaglist_Call {
	_c.Call.Return(run)
	return _c
}

// StoreTaglist provides a mock function for the type MockTaglistStorage
func (_mock *MockTaglistStorage) StoreTaglist(context1 context.Context, strings []string) error {
	ret := _mock.Called(context1, strings)

	if len(ret) == 0 {
		panic("no return value specified for StoreTaglist")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(context1, strings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaglistStorage_StoreTaglist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreTaglist'
type MockTaglistStorage_StoreTaglist_Call struct {
	*mock.Call
}

// StoreTaglist is a helper method to define mock.On call
//   - context1 context.Context
//   - strings []string
func (_e *MockTaglistStorage_Expecter) StoreTaglist(context1 interface{}, strings interface{}) *MockTaglistStorage_StoreTaglist_Call {
	return &MockTaglistStorage_StoreTaglist_Call{Call: _e.mock.On("StoreTaglist", context1, strings)}
}

func (_c *MockTaglistStorage_StoreTaglist_Call) Run(run func(context1 context.Context, strings []string)) *MockTaglistStorage_StoreTaglist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaglistStorage_StoreTaglist_Call) Return(err error) *MockTaglistStorage_StoreTaglist_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaglistStorage_StoreTaglist_Call) RunAndReturn(run func(context1 context.Context, strings []string) error) *MockTaglistStorage_StoreTaglist_Call {
	_c.Call.Return(run)
	return _c
}
