// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/mcp/domain/entity"
)

// NewMockAutotesterAPIRepository creates a new instance of MockAutotesterAPIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAutotesterAPIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAutotesterAPIRepository {
	mock := &MockAutotesterAPIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAutotesterAPIRepository is an autogenerated mock type for the AutotesterAPIRepository type
type MockAutotesterAPIRepository struct {
	mock.Mock
}

type MockAutotesterAPIRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAutotesterAPIRepository) EXPECT() *MockAutotesterAPIRepository_Expecter {
	return &MockAutotesterAPIRepository_Expecter{mock: &_m.Mock}
}

// GenerateTest provides a mock function for the type MockAutotesterAPIRepository
func (_mock *MockAutotesterAPIRepository) GenerateTest(ctx context.Context, request *entity.GenerateTestRequest) (*entity.GenerateTestResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTest")
	}

	var r0 *entity.GenerateTestResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.GenerateTestRequest) (*entity.GenerateTestResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.GenerateTestRequest) *entity.GenerateTestResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.GenerateTestResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.GenerateTestRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAutotesterAPIRepository_GenerateTest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTest'
type MockAutotesterAPIRepository_GenerateTest_Call struct {
	*mock.Call
}

// GenerateTest is a helper method to define mock.On call
//   - ctx context.Context
//   - request *entity.GenerateTestRequest
func (_e *MockAutotesterAPIRepository_Expecter) GenerateTest(ctx interface{}, request interface{}) *MockAutotesterAPIRepository_GenerateTest_Call {
	return &MockAutotesterAPIRepository_GenerateTest_Call{Call: _e.mock.On("GenerateTest", ctx, request)}
}

func (_c *MockAutotesterAPIRepository_GenerateTest_Call) Run(run func(ctx context.Context, request *entity.GenerateTestRequest)) *MockAutotesterAPIRepository_GenerateTest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.GenerateTestRequest
		if args[1] != nil {
			arg1 = args[1].(*entity.GenerateTestRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAutotesterAPIRepository_GenerateTest_Call) Return(generateTestResponse *entity.GenerateTestResponse, err error) *MockAutotesterAPIRepository_GenerateTest_Call {
	_c.Call.Return(generateTestResponse, err)
	return _c
}

func (_c *MockAutotesterAPIRepository_GenerateTest_Call) RunAndReturn(run func(ctx context.Context, request *entity.GenerateTestRequest) (*entity.GenerateTestResponse, error)) *MockAutotesterAPIRepository_GenerateTest_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplate provides a mock function for the type MockAutotesterAPIRepository
func (_mock *MockAutotesterAPIRepository) GetTemplate(ctx context.Context) (*entity.TemplateResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplate")
	}

	var r0 *entity.TemplateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*entity.TemplateResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *entity.TemplateResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TemplateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAutotesterAPIRepository_GetTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplate'
type MockAutotesterAPIRepository_GetTemplate_Call struct {
	*mock.Call
}

// GetTemplate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAutotesterAPIRepository_Expecter) GetTemplate(ctx interface{}) *MockAutotesterAPIRepository_GetTemplate_Call {
	return &MockAutotesterAPIRepository_GetTemplate_Call{Call: _e.mock.On("GetTemplate", ctx)}
}

func (_c *MockAutotesterAPIRepository_GetTemplate_Call) Run(run func(ctx context.Context)) *MockAutotesterAPIRepository_GetTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAutotesterAPIRepository_GetTemplate_Call) Return(templateResponse *entity.TemplateResponse, err error) *MockAutotesterAPIRepository_GetTemplate_Call {
	_c.Call.Return(templateResponse, err)
	return _c
}

func (_c *MockAutotesterAPIRepository_GetTemplate_Call) RunAndReturn(run func(ctx context.Context) (*entity.TemplateResponse, error)) *MockAutotesterAPIRepository_GetTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// ReadTestLogStream provides a mock function for the type MockAutotesterAPIRepository
func (_mock *MockAutotesterAPIRepository) ReadTestLogStream(ctx context.Context, testId string, eventsCh chan<- *entity.LogEvent) error {
	ret := _mock.Called(ctx, testId, eventsCh)

	if len(ret) == 0 {
		panic("no return value specified for ReadTestLogStream")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, chan<- *entity.LogEvent) error); ok {
		r0 = returnFunc(ctx, testId, eventsCh)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAutotesterAPIRepository_ReadTestLogStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadTestLogStream'
type MockAutotesterAPIRepository_ReadTestLogStream_Call struct {
	*mock.Call
}

// ReadTestLogStream is a helper method to define mock.On call
//   - ctx context.Context
//   - testId string
//   - eventsCh chan<- *entity.LogEvent
func (_e *MockAutotesterAPIRepository_Expecter) ReadTestLogStream(ctx interface{}, testId interface{}, eventsCh interface{}) *MockAutotesterAPIRepository_ReadTestLogStream_Call {
	return &MockAutotesterAPIRepository_ReadTestLogStream_Call{Call: _e.mock.On("ReadTestLogStream", ctx, testId, eventsCh)}
}

func (_c *MockAutotesterAPIRepository_ReadTestLogStream_Call) Run(run func(ctx context.Context, testId string, eventsCh chan<- *entity.LogEvent)) *MockAutotesterAPIRepository_ReadTestLogStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 chan<- *entity.LogEvent
		if args[2] != nil {
			arg2 = args[2].(chan<- *entity.LogEvent)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAutotesterAPIRepository_ReadTestLogStream_Call) Return(err error) *MockAutotesterAPIRepository_ReadTestLogStream_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAutotesterAPIRepository_ReadTestLogStream_Call) RunAndReturn(run func(ctx context.Context, testId string, eventsCh chan<- *entity.LogEvent) error) *MockAutotesterAPIRepository_ReadTestLogStream_Call {
	_c.Call.Return(run)
	return _c
}

// RunTest provides a mock function for the type MockAutotesterAPIRepository
func (_mock *MockAutotesterAPIRepository) RunTest(ctx context.Context, request *entity.RunTestRequest) (*entity.RunTestResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for RunTest")
	}

	var r0 *entity.RunTestResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.RunTestRequest) (*entity.RunTestResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.RunTestRequest) *entity.RunTestResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RunTestResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.RunTestRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAutotesterAPIRepository_RunTest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunTest'
type MockAutotesterAPIRepository_RunTest_Call struct {
	*mock.Call
}

// RunTest is a helper method to define mock.On call
//   - ctx context.Context
//   - request *entity.RunTestRequest
func (_e *MockAutotesterAPIRepository_Expecter) RunTest(ctx interface{}, request interface{}) *MockAutotesterAPIRepository_RunTest_Call {
	return &MockAutotesterAPIRepository_RunTest_Call{Call: _e.mock.On("RunTest", ctx, request)}
}

func (_c *MockAutotesterAPIRepository_RunTest_Call) Run(run func(ctx context.Context, request *entity.RunTestRequest)) *MockAutotesterAPIRepository_RunTest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.RunTestRequest
		if args[1] != nil {
			arg1 = args[1].(*entity.RunTestRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAutotesterAPIRepository_RunTest_Call) Return(runTestResponse *entity.RunTestResponse, err error) *MockAutotesterAPIRepository_RunTest_Call {
	_c.Call.Return(runTestResponse, err)
	return _c
}

func (_c *MockAutotesterAPIRepository_RunTest_Call) RunAndReturn(run func(ctx context.Context, request *entity.RunTestRequest) (*entity.RunTestResponse, error)) *MockAutotesterAPIRepository_RunTest_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTest provides a mock function for the type MockAutotesterAPIRepository
func (_mock *MockAutotesterAPIRepository) SaveTest(ctx context.Context, request *entity.SaveTestRequest) (*entity.SaveTestResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SaveTest")
	}

	var r0 *entity.SaveTestResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.SaveTestRequest) (*entity.SaveTestResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.SaveTestRequest) *entity.SaveTestResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SaveTestResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.SaveTestRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAutotesterAPIRepository_SaveTest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTest'
type MockAutotesterAPIRepository_SaveTest_Call struct {
	*mock.Call
}

// SaveTest is a helper method to define mock.On call
//   - ctx context.Context
//   - request *entity.SaveTestRequest
func (_e *MockAutotesterAPIRepository_Expecter) SaveTest(ctx interface{}, request interface{}) *MockAutotesterAPIRepository_SaveTest_Call {
	return &MockAutotesterAPIRepository_SaveTest_Call{Call: _e.mock.On("SaveTest", ctx, request)}
}

func (_c *MockAutotesterAPIRepository_SaveTest_Call) Run(run func(ctx context.Context, request *entity.SaveTestRequest)) *MockAutotesterAPIRepository_SaveTest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.SaveTestRequest
		if args[1] != nil {
			arg1 = args[1].(*entity.SaveTestRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAutotesterAPIRepository_SaveTest_Call) Return(saveTestResponse *entity.SaveTestResponse, err error) *MockAutotesterAPIRepository_SaveTest_Call {
	_c.Call.Return(saveTestResponse, err)
	return _c
}

func (_c *MockAutotesterAPIRepository_SaveTest_Call) RunAndReturn(run func(ctx context.Context, request *entity.SaveTestRequest) (*entity.SaveTestResponse, error)) *MockAutotesterAPIRepository_SaveTest_Call {
	_c.Call.Return(run)
	return _c
}

// ValidatePrompt provides a mock function for the type MockAutotesterAPIRepository
func (_mock *MockAutotesterAPIRepository) ValidatePrompt(ctx context.Context, request *entity.GenerateTestRequest) (*entity.ValidatePromptResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePrompt")
	}

	var r0 *entity.ValidatePromptResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.GenerateTestRequest) (*entity.ValidatePromptResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.GenerateTestRequest) *entity.ValidatePromptResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ValidatePromptResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.GenerateTestRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAutotesterAPIRepository_ValidatePrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatePrompt'
type MockAutotesterAPIRepository_ValidatePrompt_Call struct {
	*mock.Call
}

// ValidatePrompt is a helper method to define mock.On call
//   - ctx context.Context
//   - request *entity.GenerateTestRequest
func (_e *MockAutotesterAPIRepository_Expecter) ValidatePrompt(ctx interface{}, request interface{}) *MockAutotesterAPIRepository_ValidatePrompt_Call {
	return &MockAutotesterAPIRepository_ValidatePrompt_Call{Call: _e.mock.On("ValidatePrompt", ctx, request)}
}

func (_c *MockAutotesterAPIRepository_ValidatePrompt_Call) Run(run func(ctx context.Context, request *entity.GenerateTestRequest)) *MockAutotesterAPIRepository_ValidatePrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.GenerateTestRequest
		if args[1] != nil {
			arg1 = args[1].(*entity.GenerateTestRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAutotesterAPIRepository_ValidatePrompt_Call) Return(validatePromptResponse *entity.ValidatePromptResponse, err error) *MockAutotesterAPIRepository_ValidatePrompt_Call {
	_c.Call.Return(validatePromptResponse, err)
	return _c
}

func (_c *MockAutotesterAPIRepository_ValidatePrompt_Call) RunAndReturn(run func(ctx context.Context, request *entity.GenerateTestRequest) (*entity.ValidatePromptResponse, error)) *MockAutotesterAPIRepository_ValidatePrompt_Call {
	_c.Call.Return(run)
	return _c
}
