FROM golang:alpine AS builder

WORKDIR /app

COPY build/autotester bin/autotester

# Build static goose for Alpine
RUN CGO_ENABLED=0 go install github.com/pressly/goose/v3/cmd/goose@latest

FROM docker:cli

ARG DOPPLER_TOKEN

COPY --from=builder /app/bin/autotester /bin/autotester
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /go/bin/goose /usr/local/bin/goose

COPY scripts/run-migrations.sh /bin/run-migrations.sh
COPY internal/autotester/infrastructure/database/sql/migrations /migrations

ENV DOPPLER_TOKEN=$DOPPLER_TOKEN

RUN wget -q -t3 'https://packages.doppler.com/public/cli/rsa.8004D9FF50437357.key' -O /etc/apk/keys/cli@doppler-8004D9FF50437357.rsa.pub && \
    echo 'https://packages.doppler.com/public/cli/alpine/any-version/main' | tee -a /etc/apk/repositories && \
    apk add doppler

RUN chmod +x /bin/run-migrations.sh
RUN mkdir -p /var/log/smart/

ENTRYPOINT ["/bin/autotester"]
