FROM golang:latest AS builder

WORKDIR /app

COPY build/autotester bin/autotester
RUN ls -la build/
COPY web/embed.go web/embed.go
COPY web/dist web/dist
RUN ls -la web/
RUN ls -la web/dist

FROM scratch

COPY --from=builder /app/bin/autotester /bin/autotester
COPY --from=builder /app/web /web

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENTRYPOINT ["/bin/autotester"]
