// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDocker creates a new instance of MockDocker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDocker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDocker {
	mock := &MockDocker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDocker is an autogenerated mock type for the Docker type
type MockDocker struct {
	mock.Mock
}

type MockDocker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDocker) EXPECT() *MockDocker_Expecter {
	return &MockDocker_Expecter{mock: &_m.Mock}
}

// ReadLog provides a mock function for the type MockDocker
func (_mock *MockDocker) ReadLog(filename string) (string, error) {
	ret := _mock.Called(filename)

	if len(ret) == 0 {
		panic("no return value specified for ReadLog")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(filename)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(filename)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(filename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDocker_ReadLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadLog'
type MockDocker_ReadLog_Call struct {
	*mock.Call
}

// ReadLog is a helper method to define mock.On call
//   - filename string
func (_e *MockDocker_Expecter) ReadLog(filename interface{}) *MockDocker_ReadLog_Call {
	return &MockDocker_ReadLog_Call{Call: _e.mock.On("ReadLog", filename)}
}

func (_c *MockDocker_ReadLog_Call) Run(run func(filename string)) *MockDocker_ReadLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDocker_ReadLog_Call) Return(s string, err error) *MockDocker_ReadLog_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDocker_ReadLog_Call) RunAndReturn(run func(filename string) (string, error)) *MockDocker_ReadLog_Call {
	_c.Call.Return(run)
	return _c
}

// RunTest provides a mock function for the type MockDocker
func (_mock *MockDocker) RunTest(ctx context.Context, filename string) error {
	ret := _mock.Called(ctx, filename)

	if len(ret) == 0 {
		panic("no return value specified for RunTest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, filename)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDocker_RunTest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunTest'
type MockDocker_RunTest_Call struct {
	*mock.Call
}

// RunTest is a helper method to define mock.On call
//   - ctx context.Context
//   - filename string
func (_e *MockDocker_Expecter) RunTest(ctx interface{}, filename interface{}) *MockDocker_RunTest_Call {
	return &MockDocker_RunTest_Call{Call: _e.mock.On("RunTest", ctx, filename)}
}

func (_c *MockDocker_RunTest_Call) Run(run func(ctx context.Context, filename string)) *MockDocker_RunTest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDocker_RunTest_Call) Return(err error) *MockDocker_RunTest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDocker_RunTest_Call) RunAndReturn(run func(ctx context.Context, filename string) error) *MockDocker_RunTest_Call {
	_c.Call.Return(run)
	return _c
}
