// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGeneratePrompt creates a new instance of MockGeneratePrompt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGeneratePrompt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGeneratePrompt {
	mock := &MockGeneratePrompt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGeneratePrompt is an autogenerated mock type for the GeneratePrompt type
type MockGeneratePrompt struct {
	mock.Mock
}

type MockGeneratePrompt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGeneratePrompt) EXPECT() *MockGeneratePrompt_Expecter {
	return &MockGeneratePrompt_Expecter{mock: &_m.Mock}
}

// GeneratePrompt provides a mock function for the type MockGeneratePrompt
func (_mock *MockGeneratePrompt) GeneratePrompt(ctx context.Context, userPrompt string, sessionID string) (string, error) {
	ret := _mock.Called(ctx, userPrompt, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GeneratePrompt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, userPrompt, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, userPrompt, sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userPrompt, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGeneratePrompt_GeneratePrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GeneratePrompt'
type MockGeneratePrompt_GeneratePrompt_Call struct {
	*mock.Call
}

// GeneratePrompt is a helper method to define mock.On call
//   - ctx context.Context
//   - userPrompt string
//   - sessionID string
func (_e *MockGeneratePrompt_Expecter) GeneratePrompt(ctx interface{}, userPrompt interface{}, sessionID interface{}) *MockGeneratePrompt_GeneratePrompt_Call {
	return &MockGeneratePrompt_GeneratePrompt_Call{Call: _e.mock.On("GeneratePrompt", ctx, userPrompt, sessionID)}
}

func (_c *MockGeneratePrompt_GeneratePrompt_Call) Run(run func(ctx context.Context, userPrompt string, sessionID string)) *MockGeneratePrompt_GeneratePrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGeneratePrompt_GeneratePrompt_Call) Return(s string, err error) *MockGeneratePrompt_GeneratePrompt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGeneratePrompt_GeneratePrompt_Call) RunAndReturn(run func(ctx context.Context, userPrompt string, sessionID string) (string, error)) *MockGeneratePrompt_GeneratePrompt_Call {
	_c.Call.Return(run)
	return _c
}
