// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/autotester/domain/entity"
)

// NewMockTestcaseStorageService creates a new instance of MockTestcaseStorageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestcaseStorageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestcaseStorageService {
	mock := &MockTestcaseStorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTestcaseStorageService is an autogenerated mock type for the TestcaseStorageService type
type MockTestcaseStorageService struct {
	mock.Mock
}

type MockTestcaseStorageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTestcaseStorageService) EXPECT() *MockTestcaseStorageService_Expecter {
	return &MockTestcaseStorageService_Expecter{mock: &_m.Mock}
}

// SaveTestCase provides a mock function for the type MockTestcaseStorageService
func (_mock *MockTestcaseStorageService) SaveTestCase(ctx context.Context, testcase *entity.TestCase, userId string) error {
	ret := _mock.Called(ctx, testcase, userId)

	if len(ret) == 0 {
		panic("no return value specified for SaveTestCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.TestCase, string) error); ok {
		r0 = returnFunc(ctx, testcase, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTestcaseStorageService_SaveTestCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTestCase'
type MockTestcaseStorageService_SaveTestCase_Call struct {
	*mock.Call
}

// SaveTestCase is a helper method to define mock.On call
//   - ctx context.Context
//   - testcase *entity.TestCase
//   - userId string
func (_e *MockTestcaseStorageService_Expecter) SaveTestCase(ctx interface{}, testcase interface{}, userId interface{}) *MockTestcaseStorageService_SaveTestCase_Call {
	return &MockTestcaseStorageService_SaveTestCase_Call{Call: _e.mock.On("SaveTestCase", ctx, testcase, userId)}
}

func (_c *MockTestcaseStorageService_SaveTestCase_Call) Run(run func(ctx context.Context, testcase *entity.TestCase, userId string)) *MockTestcaseStorageService_SaveTestCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.TestCase
		if args[1] != nil {
			arg1 = args[1].(*entity.TestCase)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTestcaseStorageService_SaveTestCase_Call) Return(err error) *MockTestcaseStorageService_SaveTestCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTestcaseStorageService_SaveTestCase_Call) RunAndReturn(run func(ctx context.Context, testcase *entity.TestCase, userId string) error) *MockTestcaseStorageService_SaveTestCase_Call {
	_c.Call.Return(run)
	return _c
}
