// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/autotester/domain/entity"
)

// NewMockValidatePrompt creates a new instance of MockValidatePrompt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidatePrompt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidatePrompt {
	mock := &MockValidatePrompt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValidatePrompt is an autogenerated mock type for the ValidatePrompt type
type MockValidatePrompt struct {
	mock.Mock
}

type MockValidatePrompt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidatePrompt) EXPECT() *MockValidatePrompt_Expecter {
	return &MockValidatePrompt_Expecter{mock: &_m.Mock}
}

// ValidatePrompt provides a mock function for the type MockValidatePrompt
func (_mock *MockValidatePrompt) ValidatePrompt(ctx context.Context, chat *entity.Chat, request *entity.UserRequest) (bool, string, error) {
	ret := _mock.Called(ctx, chat, request)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePrompt")
	}

	var r0 bool
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Chat, *entity.UserRequest) (bool, string, error)); ok {
		return returnFunc(ctx, chat, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Chat, *entity.UserRequest) bool); ok {
		r0 = returnFunc(ctx, chat, request)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Chat, *entity.UserRequest) string); ok {
		r1 = returnFunc(ctx, chat, request)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *entity.Chat, *entity.UserRequest) error); ok {
		r2 = returnFunc(ctx, chat, request)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockValidatePrompt_ValidatePrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatePrompt'
type MockValidatePrompt_ValidatePrompt_Call struct {
	*mock.Call
}

// ValidatePrompt is a helper method to define mock.On call
//   - ctx context.Context
//   - chat *entity.Chat
//   - request *entity.UserRequest
func (_e *MockValidatePrompt_Expecter) ValidatePrompt(ctx interface{}, chat interface{}, request interface{}) *MockValidatePrompt_ValidatePrompt_Call {
	return &MockValidatePrompt_ValidatePrompt_Call{Call: _e.mock.On("ValidatePrompt", ctx, chat, request)}
}

func (_c *MockValidatePrompt_ValidatePrompt_Call) Run(run func(ctx context.Context, chat *entity.Chat, request *entity.UserRequest)) *MockValidatePrompt_ValidatePrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Chat
		if args[1] != nil {
			arg1 = args[1].(*entity.Chat)
		}
		var arg2 *entity.UserRequest
		if args[2] != nil {
			arg2 = args[2].(*entity.UserRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockValidatePrompt_ValidatePrompt_Call) Return(b bool, s string, err error) *MockValidatePrompt_ValidatePrompt_Call {
	_c.Call.Return(b, s, err)
	return _c
}

func (_c *MockValidatePrompt_ValidatePrompt_Call) RunAndReturn(run func(ctx context.Context, chat *entity.Chat, request *entity.UserRequest) (bool, string, error)) *MockValidatePrompt_ValidatePrompt_Call {
	_c.Call.Return(run)
	return _c
}
