// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/suproxy/domain/entity"
)

// NewMockDatabaseRepository creates a new instance of MockDatabaseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabaseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabaseRepository {
	mock := &MockDatabaseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatabaseRepository is an autogenerated mock type for the DatabaseRepository type
type MockDatabaseRepository struct {
	mock.Mock
}

type MockDatabaseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabaseRepository) EXPECT() *MockDatabaseRepository_Expecter {
	return &MockDatabaseRepository_Expecter{mock: &_m.Mock}
}

// CreateRequest provides a mock function for the type MockDatabaseRepository
func (_mock *MockDatabaseRepository) CreateRequest(ctx context.Context, dbEntry entity.DatabaseEntry) error {
	ret := _mock.Called(ctx, dbEntry)

	if len(ret) == 0 {
		panic("no return value specified for CreateRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.DatabaseEntry) error); ok {
		r0 = returnFunc(ctx, dbEntry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabaseRepository_CreateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRequest'
type MockDatabaseRepository_CreateRequest_Call struct {
	*mock.Call
}

// CreateRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - dbEntry entity.DatabaseEntry
func (_e *MockDatabaseRepository_Expecter) CreateRequest(ctx interface{}, dbEntry interface{}) *MockDatabaseRepository_CreateRequest_Call {
	return &MockDatabaseRepository_CreateRequest_Call{Call: _e.mock.On("CreateRequest", ctx, dbEntry)}
}

func (_c *MockDatabaseRepository_CreateRequest_Call) Run(run func(ctx context.Context, dbEntry entity.DatabaseEntry)) *MockDatabaseRepository_CreateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.DatabaseEntry
		if args[1] != nil {
			arg1 = args[1].(entity.DatabaseEntry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabaseRepository_CreateRequest_Call) Return(err error) *MockDatabaseRepository_CreateRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabaseRepository_CreateRequest_Call) RunAndReturn(run func(ctx context.Context, dbEntry entity.DatabaseEntry) error) *MockDatabaseRepository_CreateRequest_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRequest provides a mock function for the type MockDatabaseRepository
func (_mock *MockDatabaseRepository) DeleteRequest(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabaseRepository_DeleteRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRequest'
type MockDatabaseRepository_DeleteRequest_Call struct {
	*mock.Call
}

// DeleteRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockDatabaseRepository_Expecter) DeleteRequest(ctx interface{}, key interface{}) *MockDatabaseRepository_DeleteRequest_Call {
	return &MockDatabaseRepository_DeleteRequest_Call{Call: _e.mock.On("DeleteRequest", ctx, key)}
}

func (_c *MockDatabaseRepository_DeleteRequest_Call) Run(run func(ctx context.Context, key string)) *MockDatabaseRepository_DeleteRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabaseRepository_DeleteRequest_Call) Return(err error) *MockDatabaseRepository_DeleteRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabaseRepository_DeleteRequest_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockDatabaseRepository_DeleteRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllKeys provides a mock function for the type MockDatabaseRepository
func (_mock *MockDatabaseRepository) ListAllKeys(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAllKeys")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabaseRepository_ListAllKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllKeys'
type MockDatabaseRepository_ListAllKeys_Call struct {
	*mock.Call
}

// ListAllKeys is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabaseRepository_Expecter) ListAllKeys(ctx interface{}) *MockDatabaseRepository_ListAllKeys_Call {
	return &MockDatabaseRepository_ListAllKeys_Call{Call: _e.mock.On("ListAllKeys", ctx)}
}

func (_c *MockDatabaseRepository_ListAllKeys_Call) Run(run func(ctx context.Context)) *MockDatabaseRepository_ListAllKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatabaseRepository_ListAllKeys_Call) Return(strings []string, err error) *MockDatabaseRepository_ListAllKeys_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockDatabaseRepository_ListAllKeys_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockDatabaseRepository_ListAllKeys_Call {
	_c.Call.Return(run)
	return _c
}

// ReadRequest provides a mock function for the type MockDatabaseRepository
func (_mock *MockDatabaseRepository) ReadRequest(ctx context.Context, key string) (*entity.DatabaseEntry, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for ReadRequest")
	}

	var r0 *entity.DatabaseEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.DatabaseEntry, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.DatabaseEntry); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.DatabaseEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabaseRepository_ReadRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadRequest'
type MockDatabaseRepository_ReadRequest_Call struct {
	*mock.Call
}

// ReadRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockDatabaseRepository_Expecter) ReadRequest(ctx interface{}, key interface{}) *MockDatabaseRepository_ReadRequest_Call {
	return &MockDatabaseRepository_ReadRequest_Call{Call: _e.mock.On("ReadRequest", ctx, key)}
}

func (_c *MockDatabaseRepository_ReadRequest_Call) Run(run func(ctx context.Context, key string)) *MockDatabaseRepository_ReadRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabaseRepository_ReadRequest_Call) Return(databaseEntry *entity.DatabaseEntry, err error) *MockDatabaseRepository_ReadRequest_Call {
	_c.Call.Return(databaseEntry, err)
	return _c
}

func (_c *MockDatabaseRepository_ReadRequest_Call) RunAndReturn(run func(ctx context.Context, key string) (*entity.DatabaseEntry, error)) *MockDatabaseRepository_ReadRequest_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRequest provides a mock function for the type MockDatabaseRepository
func (_mock *MockDatabaseRepository) UpdateRequest(ctx context.Context, key string, dbEntry entity.DatabaseEntry) error {
	ret := _mock.Called(ctx, key, dbEntry)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.DatabaseEntry) error); ok {
		r0 = returnFunc(ctx, key, dbEntry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabaseRepository_UpdateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRequest'
type MockDatabaseRepository_UpdateRequest_Call struct {
	*mock.Call
}

// UpdateRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - dbEntry entity.DatabaseEntry
func (_e *MockDatabaseRepository_Expecter) UpdateRequest(ctx interface{}, key interface{}, dbEntry interface{}) *MockDatabaseRepository_UpdateRequest_Call {
	return &MockDatabaseRepository_UpdateRequest_Call{Call: _e.mock.On("UpdateRequest", ctx, key, dbEntry)}
}

func (_c *MockDatabaseRepository_UpdateRequest_Call) Run(run func(ctx context.Context, key string, dbEntry entity.DatabaseEntry)) *MockDatabaseRepository_UpdateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entity.DatabaseEntry
		if args[2] != nil {
			arg2 = args[2].(entity.DatabaseEntry)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDatabaseRepository_UpdateRequest_Call) Return(err error) *MockDatabaseRepository_UpdateRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabaseRepository_UpdateRequest_Call) RunAndReturn(run func(ctx context.Context, key string, dbEntry entity.DatabaseEntry) error) *MockDatabaseRepository_UpdateRequest_Call {
	_c.Call.Return(run)
	return _c
}
