package repository

import (
	"context"

	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/autotester/domain/entity"
)

// MediaFileSystem provides an abstraction for media files (screenshots and videos)
// generated by Playwright tests. Media is stored in and retrieved from S3.
type MediaFileSystem interface {
	// GetScreenshotUrl returns the S3 URL to the screenshot file for the given testId.
	// Returns an error if the file does not exist in S3.
	GetScreenshotUrl(ctx context.Context, testId string) (string, error)

	// GetVideoUrl returns the S3 URL to the video file for the given testId.
	// Returns an error if the file does not exist in S3.
	GetVideoUrl(ctx context.Context, testId string) (string, error)

	// HasScreenshot checks if a screenshot exists for the given testId in S3.
	HasScreenshot(ctx context.Context, testId string) bool

	// HasVideo checks if a video exists for the given testId in S3.
	HasVideo(ctx context.Context, testId string) bool

	// UploadMedia uploads a file to s3
	UploadMedia(ctx context.Context, testId string, file entity.File) error
}
