package repository

import (
	"fmt"
	"os"
	"path/filepath"

	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/shared/lib/assert"
)

// MediaFileSystem provides a filesystem abstraction for media files (screenshots and videos)
// generated by Playwright tests. All operations are confined to a configured root directory.
type MediaFileSystem interface {
	// GetScreenshotPath returns the path to the screenshot file for the given testId.
	// Returns an error if the path validation fails.
	GetScreenshotPath(testId string) (string, error)

	// GetVideoPath returns the path to the video file for the given testId.
	// Returns an error if the path validation fails.
	GetVideoPath(testId string) (string, error)

	// GetScreenshot reads and returns the screenshot data for the given testId.
	// Returns an error if the file does not exist or cannot be read.
	GetScreenshot(testId string) ([]byte, error)

	// GetVideo reads and returns the video data for the given testId.
	// Returns an error if the file does not exist or cannot be read.
	GetVideo(testId string) ([]byte, error)

	// HasScreenshot checks if a screenshot exists for the given testId.
	HasScreenshot(testId string) bool

	// HasVideo checks if a video exists for the given testId.
	HasVideo(testId string) bool

	// GetMediaDir returns the full path to the media directory for the given testId.
	// Creates the directory if it does not exist.
	GetMediaDir(testId string) (string, error)

	// DeleteMedia removes all media files for the given testId.
	// Returns nil if the directory does not exist.
	DeleteMedia(testId string) error
}

// mediaFileSystem is an implementation of the MediaFileSystem interface.
type mediaFileSystem struct {
	Root string
}

// NewMediaFileSystem returns a MediaFileSystem rooted at the provided directory.
// The root is created if it does not exist. Root must not be empty.
func NewMediaFileSystem(root string) (MediaFileSystem, error) {
	if err := assert.StringNotEmpty(root); err != nil {
		return nil, fmt.Errorf("root must not be empty")
	}
	if err := os.MkdirAll(root, DefaultDirPerm); err != nil {
		return nil, fmt.Errorf("create root: %w", err)
	}

	resolvedRoot := root
	if r, err := filepath.EvalSymlinks(root); err == nil {
		resolvedRoot = r
	}

	return &mediaFileSystem{
		Root: filepath.Clean(resolvedRoot),
	}, nil
}

func (fs *mediaFileSystem) getMediaPath(testId, extension, mediaType string) (string, error) {
	if err := assert.StringNotEmpty(testId); err != nil {
		return "", fmt.Errorf("testId must not be empty")
	}

	mediaDir := filepath.Join(fs.Root, testId)
	pattern := filepath.Join(mediaDir, "**", "*."+extension)

	matches, err := filepath.Glob(pattern)
	if err != nil {
		return "", fmt.Errorf("glob pattern error: %w", err)
	}

	// Try a simpler pattern if no matches
	if len(matches) == 0 {
		pattern = filepath.Join(mediaDir, "*."+extension)
		matches, err = filepath.Glob(pattern)
		if err != nil {
			return "", fmt.Errorf("glob pattern error: %w", err)
		}
	}

	// Also check in test-results subdirectory
	if len(matches) == 0 {
		pattern = filepath.Join(mediaDir, "test-results", "*."+extension)
		matches, err = filepath.Glob(pattern)
		if err != nil {
			return "", fmt.Errorf("glob pattern error: %w", err)
		}
	}

	if len(matches) == 0 {
		return "", fmt.Errorf("no %s found for testId: %s", mediaType, testId)
	}

	return matches[0], nil
}

func (fs *mediaFileSystem) GetScreenshotPath(testId string) (string, error) {
	return fs.getMediaPath(testId, "png", "screenshot")
}

func (fs *mediaFileSystem) GetVideoPath(testId string) (string, error) {
	return fs.getMediaPath(testId, "webm", "video")
}

func (fs *mediaFileSystem) GetScreenshot(testId string) ([]byte, error) {
	path, err := fs.GetScreenshotPath(testId)
	if err != nil {
		return nil, err
	}
	return os.ReadFile(path) //nolint:gosec // G304: path is validated by getMediaPath within fs.Root
}

func (fs *mediaFileSystem) GetVideo(testId string) ([]byte, error) {
	path, err := fs.GetVideoPath(testId)
	if err != nil {
		return nil, err
	}
	return os.ReadFile(path) //nolint:gosec // G304: path is validated by getMediaPath within fs.Root
}

func (fs *mediaFileSystem) HasScreenshot(testId string) bool {
	_, err := fs.GetScreenshotPath(testId)
	return err == nil
}

func (fs *mediaFileSystem) HasVideo(testId string) bool {
	_, err := fs.GetVideoPath(testId)
	return err == nil
}

func (fs *mediaFileSystem) GetMediaDir(testId string) (string, error) {
	if err := assert.StringNotEmpty(testId); err != nil {
		return "", fmt.Errorf("testId must not be empty")
	}

	mediaDir := filepath.Join(fs.Root, testId)
	if err := os.MkdirAll(mediaDir, DefaultDirPerm); err != nil {
		return "", fmt.Errorf("create media directory: %w", err)
	}

	return mediaDir, nil
}

func (fs *mediaFileSystem) DeleteMedia(testId string) error {
	if err := assert.StringNotEmpty(testId); err != nil {
		return fmt.Errorf("testId must not be empty")
	}

	mediaDir := filepath.Join(fs.Root, testId)
	err := os.RemoveAll(mediaDir)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("remove media directory: %w", err)
	}

	return nil
}
