package repository

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	wrapperService "gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/shared/domain/service/wrapper"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/shared/lib/assert"
)

// MediaFileSystem provides an abstraction for media files (screenshots and videos)
// generated by Playwright tests. Media is stored in and retrieved from S3.
type MediaFileSystem interface {
	// GetScreenshotUrl returns the S3 URL to the screenshot file for the given testId.
	// Returns an error if the file does not exist in S3.
	GetScreenshotUrl(ctx context.Context, testId string) (string, error)

	// GetVideoUrl returns the S3 URL to the video file for the given testId.
	// Returns an error if the file does not exist in S3.
	GetVideoUrl(ctx context.Context, testId string) (string, error)

	// HasScreenshot checks if a screenshot exists for the given testId in S3.
	HasScreenshot(ctx context.Context, testId string) bool

	// HasVideo checks if a video exists for the given testId in S3.
	HasVideo(ctx context.Context, testId string) bool

	// UploadMediaFromDir uploads screenshot and video files from a local directory to S3.
	// It searches for .png and .webm files in the directory and uploads them.
	// Returns the number of files uploaded and any error encountered.
	UploadMediaFromDir(ctx context.Context, testId string, localDir string) (int, error)
}

const (
	screenshotExtension = "png"
	videoExtension      = "webm"
)

// mediaFileSystem is an implementation of the MediaFileSystem interface using S3.
type mediaFileSystem struct {
	s3Wrapper wrapperService.S3StorageWrapper
	prefix    string
}

// NewMediaFileSystem returns a MediaFileSystem that uses S3 for storage.
// The prefix is prepended to all S3 keys.
func NewMediaFileSystem(s3Wrapper wrapperService.S3StorageWrapper, prefix string) (MediaFileSystem, error) {
	if err := assert.NotNil(s3Wrapper); err != nil {
		return nil, fmt.Errorf("s3Wrapper must not be nil")
	}

	return &mediaFileSystem{
		s3Wrapper: s3Wrapper,
		prefix:    prefix,
	}, nil
}

func (fs *mediaFileSystem) getMediaKey(testId, extension string) string {
	if fs.prefix != "" {
		return fmt.Sprintf("%s/%s.%s", fs.prefix, testId, extension)
	}
	return fmt.Sprintf("%s.%s", testId, extension)
}

func (fs *mediaFileSystem) GetScreenshotUrl(ctx context.Context, testId string) (string, error) {
	if err := assert.StringNotEmpty(testId); err != nil {
		return "", fmt.Errorf("testId must not be empty")
	}

	key := fs.getMediaKey(testId, screenshotExtension)
	return fs.s3Wrapper.GetMediaUrl(ctx, key)
}

func (fs *mediaFileSystem) GetVideoUrl(ctx context.Context, testId string) (string, error) {
	if err := assert.StringNotEmpty(testId); err != nil {
		return "", fmt.Errorf("testId must not be empty")
	}

	key := fs.getMediaKey(testId, videoExtension)
	return fs.s3Wrapper.GetMediaUrl(ctx, key)
}

func (fs *mediaFileSystem) HasScreenshot(ctx context.Context, testId string) bool {
	if err := assert.StringNotEmpty(testId); err != nil {
		return false
	}

	key := fs.getMediaKey(testId, screenshotExtension)
	exists, err := fs.s3Wrapper.FileExists(ctx, key)
	return err == nil && exists
}

func (fs *mediaFileSystem) HasVideo(ctx context.Context, testId string) bool {
	if err := assert.StringNotEmpty(testId); err != nil {
		return false
	}

	key := fs.getMediaKey(testId, videoExtension)
	exists, err := fs.s3Wrapper.FileExists(ctx, key)
	return err == nil && exists
}

func (fs *mediaFileSystem) UploadMediaFromDir(ctx context.Context, testId string, localDir string) (int, error) {
	if err := assert.StringNotEmpty(testId); err != nil {
		return 0, fmt.Errorf("testId must not be empty")
	}
	if err := assert.StringNotEmpty(localDir); err != nil {
		return 0, fmt.Errorf("localDir must not be empty")
	}

	uploaded := 0

	// Find and upload screenshot (.png)
	if err := fs.uploadFileByExtension(ctx, testId, localDir, screenshotExtension); err == nil {
		uploaded++
	}

	// Find and upload video (.webm)
	if err := fs.uploadFileByExtension(ctx, testId, localDir, videoExtension); err == nil {
		uploaded++
	}

	return uploaded, nil
}

func (fs *mediaFileSystem) uploadFileByExtension(ctx context.Context, testId, localDir, extension string) error {
	// Search for files with the given extension in the directory and subdirectories
	var filePath string

	err := filepath.Walk(localDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && filepath.Ext(path) == "."+extension {
			filePath = path
			return filepath.SkipAll // Stop after finding the first match
		}
		return nil
	})

	if err != nil && err != filepath.SkipAll {
		return fmt.Errorf("error walking directory: %w", err)
	}

	if filePath == "" {
		return fmt.Errorf("no %s file found in %s", extension, localDir)
	}

	// Read the file
	data, err := os.ReadFile(filePath) //nolint:gosec // G304: path is from controlled directory
	if err != nil {
		return fmt.Errorf("failed to read file %s: %w", filePath, err)
	}

	// Upload to S3
	key := fs.getMediaKey(testId, extension)
	if err := fs.s3Wrapper.UploadMediaFile(ctx, key, data, nil); err != nil {
		return fmt.Errorf("failed to upload %s to S3: %w", extension, err)
	}

	return nil
}
