// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/suproxy/domain/entity"
)

// NewMockDatabaseService creates a new instance of MockDatabaseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabaseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabaseService {
	mock := &MockDatabaseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatabaseService is an autogenerated mock type for the DatabaseService type
type MockDatabaseService struct {
	mock.Mock
}

type MockDatabaseService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabaseService) EXPECT() *MockDatabaseService_Expecter {
	return &MockDatabaseService_Expecter{mock: &_m.Mock}
}

// GetAllKeys provides a mock function for the type MockDatabaseService
func (_mock *MockDatabaseService) GetAllKeys(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllKeys")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabaseService_GetAllKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllKeys'
type MockDatabaseService_GetAllKeys_Call struct {
	*mock.Call
}

// GetAllKeys is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabaseService_Expecter) GetAllKeys(ctx interface{}) *MockDatabaseService_GetAllKeys_Call {
	return &MockDatabaseService_GetAllKeys_Call{Call: _e.mock.On("GetAllKeys", ctx)}
}

func (_c *MockDatabaseService_GetAllKeys_Call) Run(run func(ctx context.Context)) *MockDatabaseService_GetAllKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatabaseService_GetAllKeys_Call) Return(strings []string, err error) *MockDatabaseService_GetAllKeys_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockDatabaseService_GetAllKeys_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockDatabaseService_GetAllKeys_Call {
	_c.Call.Return(run)
	return _c
}

// SaveDbEntry provides a mock function for the type MockDatabaseService
func (_mock *MockDatabaseService) SaveDbEntry(context1 context.Context, databaseEntry entity.DatabaseEntry) error {
	ret := _mock.Called(context1, databaseEntry)

	if len(ret) == 0 {
		panic("no return value specified for SaveDbEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.DatabaseEntry) error); ok {
		r0 = returnFunc(context1, databaseEntry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabaseService_SaveDbEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveDbEntry'
type MockDatabaseService_SaveDbEntry_Call struct {
	*mock.Call
}

// SaveDbEntry is a helper method to define mock.On call
//   - context1 context.Context
//   - databaseEntry entity.DatabaseEntry
func (_e *MockDatabaseService_Expecter) SaveDbEntry(context1 interface{}, databaseEntry interface{}) *MockDatabaseService_SaveDbEntry_Call {
	return &MockDatabaseService_SaveDbEntry_Call{Call: _e.mock.On("SaveDbEntry", context1, databaseEntry)}
}

func (_c *MockDatabaseService_SaveDbEntry_Call) Run(run func(context1 context.Context, databaseEntry entity.DatabaseEntry)) *MockDatabaseService_SaveDbEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.DatabaseEntry
		if args[1] != nil {
			arg1 = args[1].(entity.DatabaseEntry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabaseService_SaveDbEntry_Call) Return(err error) *MockDatabaseService_SaveDbEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabaseService_SaveDbEntry_Call) RunAndReturn(run func(context1 context.Context, databaseEntry entity.DatabaseEntry) error) *MockDatabaseService_SaveDbEntry_Call {
	_c.Call.Return(run)
	return _c
}
