// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTagSearchService creates a new instance of MockTagSearchService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagSearchService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagSearchService {
	mock := &MockTagSearchService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTagSearchService is an autogenerated mock type for the TagSearchService type
type MockTagSearchService struct {
	mock.Mock
}

type MockTagSearchService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagSearchService) EXPECT() *MockTagSearchService_Expecter {
	return &MockTagSearchService_Expecter{mock: &_m.Mock}
}

// FindKeysByTags provides a mock function for the type MockTagSearchService
func (_mock *MockTagSearchService) FindKeysByTags(ctx context.Context, tag string) ([]string, error) {
	ret := _mock.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for FindKeysByTags")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagSearchService_FindKeysByTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindKeysByTags'
type MockTagSearchService_FindKeysByTags_Call struct {
	*mock.Call
}

// FindKeysByTags is a helper method to define mock.On call
//   - ctx context.Context
//   - tag string
func (_e *MockTagSearchService_Expecter) FindKeysByTags(ctx interface{}, tag interface{}) *MockTagSearchService_FindKeysByTags_Call {
	return &MockTagSearchService_FindKeysByTags_Call{Call: _e.mock.On("FindKeysByTags", ctx, tag)}
}

func (_c *MockTagSearchService_FindKeysByTags_Call) Run(run func(ctx context.Context, tag string)) *MockTagSearchService_FindKeysByTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagSearchService_FindKeysByTags_Call) Return(strings []string, err error) *MockTagSearchService_FindKeysByTags_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockTagSearchService_FindKeysByTags_Call) RunAndReturn(run func(ctx context.Context, tag string) ([]string, error)) *MockTagSearchService_FindKeysByTags_Call {
	_c.Call.Return(run)
	return _c
}
