// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/mcp/domain/entity"
)

// NewMockAutotesterAPIService creates a new instance of MockAutotesterAPIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAutotesterAPIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAutotesterAPIService {
	mock := &MockAutotesterAPIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAutotesterAPIService is an autogenerated mock type for the AutotesterAPIService type
type MockAutotesterAPIService struct {
	mock.Mock
}

type MockAutotesterAPIService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAutotesterAPIService) EXPECT() *MockAutotesterAPIService_Expecter {
	return &MockAutotesterAPIService_Expecter{mock: &_m.Mock}
}

// ExecuteTest provides a mock function for the type MockAutotesterAPIService
func (_mock *MockAutotesterAPIService) ExecuteTest(ctx context.Context, request *entity.ExecuteTestRequest) (*entity.ExecuteTestResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteTest")
	}

	var r0 *entity.ExecuteTestResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.ExecuteTestRequest) (*entity.ExecuteTestResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.ExecuteTestRequest) *entity.ExecuteTestResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ExecuteTestResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.ExecuteTestRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAutotesterAPIService_ExecuteTest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteTest'
type MockAutotesterAPIService_ExecuteTest_Call struct {
	*mock.Call
}

// ExecuteTest is a helper method to define mock.On call
//   - ctx context.Context
//   - request *entity.ExecuteTestRequest
func (_e *MockAutotesterAPIService_Expecter) ExecuteTest(ctx interface{}, request interface{}) *MockAutotesterAPIService_ExecuteTest_Call {
	return &MockAutotesterAPIService_ExecuteTest_Call{Call: _e.mock.On("ExecuteTest", ctx, request)}
}

func (_c *MockAutotesterAPIService_ExecuteTest_Call) Run(run func(ctx context.Context, request *entity.ExecuteTestRequest)) *MockAutotesterAPIService_ExecuteTest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.ExecuteTestRequest
		if args[1] != nil {
			arg1 = args[1].(*entity.ExecuteTestRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAutotesterAPIService_ExecuteTest_Call) Return(executeTestResponse *entity.ExecuteTestResponse, err error) *MockAutotesterAPIService_ExecuteTest_Call {
	_c.Call.Return(executeTestResponse, err)
	return _c
}

func (_c *MockAutotesterAPIService_ExecuteTest_Call) RunAndReturn(run func(ctx context.Context, request *entity.ExecuteTestRequest) (*entity.ExecuteTestResponse, error)) *MockAutotesterAPIService_ExecuteTest_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateTest provides a mock function for the type MockAutotesterAPIService
func (_mock *MockAutotesterAPIService) GenerateTest(ctx context.Context, request *entity.GenerateTestRequest) (*entity.GenerateTestToolResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTest")
	}

	var r0 *entity.GenerateTestToolResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.GenerateTestRequest) (*entity.GenerateTestToolResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.GenerateTestRequest) *entity.GenerateTestToolResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.GenerateTestToolResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.GenerateTestRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAutotesterAPIService_GenerateTest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTest'
type MockAutotesterAPIService_GenerateTest_Call struct {
	*mock.Call
}

// GenerateTest is a helper method to define mock.On call
//   - ctx context.Context
//   - request *entity.GenerateTestRequest
func (_e *MockAutotesterAPIService_Expecter) GenerateTest(ctx interface{}, request interface{}) *MockAutotesterAPIService_GenerateTest_Call {
	return &MockAutotesterAPIService_GenerateTest_Call{Call: _e.mock.On("GenerateTest", ctx, request)}
}

func (_c *MockAutotesterAPIService_GenerateTest_Call) Run(run func(ctx context.Context, request *entity.GenerateTestRequest)) *MockAutotesterAPIService_GenerateTest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.GenerateTestRequest
		if args[1] != nil {
			arg1 = args[1].(*entity.GenerateTestRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAutotesterAPIService_GenerateTest_Call) Return(generateTestToolResponse *entity.GenerateTestToolResponse, err error) *MockAutotesterAPIService_GenerateTest_Call {
	_c.Call.Return(generateTestToolResponse, err)
	return _c
}

func (_c *MockAutotesterAPIService_GenerateTest_Call) RunAndReturn(run func(ctx context.Context, request *entity.GenerateTestRequest) (*entity.GenerateTestToolResponse, error)) *MockAutotesterAPIService_GenerateTest_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplate provides a mock function for the type MockAutotesterAPIService
func (_mock *MockAutotesterAPIService) GetTemplate(ctx context.Context) (*entity.TemplateResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplate")
	}

	var r0 *entity.TemplateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*entity.TemplateResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *entity.TemplateResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TemplateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAutotesterAPIService_GetTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplate'
type MockAutotesterAPIService_GetTemplate_Call struct {
	*mock.Call
}

// GetTemplate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAutotesterAPIService_Expecter) GetTemplate(ctx interface{}) *MockAutotesterAPIService_GetTemplate_Call {
	return &MockAutotesterAPIService_GetTemplate_Call{Call: _e.mock.On("GetTemplate", ctx)}
}

func (_c *MockAutotesterAPIService_GetTemplate_Call) Run(run func(ctx context.Context)) *MockAutotesterAPIService_GetTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAutotesterAPIService_GetTemplate_Call) Return(templateResponse *entity.TemplateResponse, err error) *MockAutotesterAPIService_GetTemplate_Call {
	_c.Call.Return(templateResponse, err)
	return _c
}

func (_c *MockAutotesterAPIService_GetTemplate_Call) RunAndReturn(run func(ctx context.Context) (*entity.TemplateResponse, error)) *MockAutotesterAPIService_GetTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// ReadTestLogStream provides a mock function for the type MockAutotesterAPIService
func (_mock *MockAutotesterAPIService) ReadTestLogStream(ctx context.Context, testId string) {
	_mock.Called(ctx, testId)
	return
}

// MockAutotesterAPIService_ReadTestLogStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadTestLogStream'
type MockAutotesterAPIService_ReadTestLogStream_Call struct {
	*mock.Call
}

// ReadTestLogStream is a helper method to define mock.On call
//   - ctx context.Context
//   - testId string
func (_e *MockAutotesterAPIService_Expecter) ReadTestLogStream(ctx interface{}, testId interface{}) *MockAutotesterAPIService_ReadTestLogStream_Call {
	return &MockAutotesterAPIService_ReadTestLogStream_Call{Call: _e.mock.On("ReadTestLogStream", ctx, testId)}
}

func (_c *MockAutotesterAPIService_ReadTestLogStream_Call) Run(run func(ctx context.Context, testId string)) *MockAutotesterAPIService_ReadTestLogStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAutotesterAPIService_ReadTestLogStream_Call) Return() *MockAutotesterAPIService_ReadTestLogStream_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAutotesterAPIService_ReadTestLogStream_Call) RunAndReturn(run func(ctx context.Context, testId string)) *MockAutotesterAPIService_ReadTestLogStream_Call {
	_c.Run(run)
	return _c
}
