// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package entity

import (
	"errors"
	"fmt"
)

const (
	// MessageTypeValidation is a MessageType of type Validation.
	MessageTypeValidation MessageType = iota
	// MessageTypeGeneration is a MessageType of type Generation.
	MessageTypeGeneration
	// MessageTypeUser is a MessageType of type User.
	MessageTypeUser
)

var ErrInvalidMessageType = errors.New("not a valid MessageType")

const _MessageTypeName = "ValidationGenerationUser"

var _MessageTypeMap = map[MessageType]string{
	MessageTypeValidation: _MessageTypeName[0:10],
	MessageTypeGeneration: _MessageTypeName[10:20],
	MessageTypeUser:       _MessageTypeName[20:24],
}

// String implements the Stringer interface.
func (x MessageType) String() string {
	if str, ok := _MessageTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("MessageType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x MessageType) IsValid() bool {
	_, ok := _MessageTypeMap[x]
	return ok
}

var _MessageTypeValue = map[string]MessageType{
	_MessageTypeName[0:10]:  MessageTypeValidation,
	_MessageTypeName[10:20]: MessageTypeGeneration,
	_MessageTypeName[20:24]: MessageTypeUser,
}

// ParseMessageType attempts to convert a string to a MessageType.
func ParseMessageType(name string) (MessageType, error) {
	if x, ok := _MessageTypeValue[name]; ok {
		return x, nil
	}
	return MessageType(0), fmt.Errorf("%s is %w", name, ErrInvalidMessageType)
}

// MarshalText implements the text marshaller method.
func (x MessageType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *MessageType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseMessageType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *MessageType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
