// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package entity

import (
	"errors"
	"fmt"
)

const (
	// TestStatusPending is a TestStatus of type Pending.
	TestStatusPending TestStatus = iota
	// TestStatusNotRun is a TestStatus of type Not_run.
	TestStatusNotRun
	// TestStatusRunning is a TestStatus of type Running.
	TestStatusRunning
	// TestStatusPassed is a TestStatus of type Passed.
	TestStatusPassed
	// TestStatusFailed is a TestStatus of type Failed.
	TestStatusFailed
	// TestStatusSkipped is a TestStatus of type Skipped.
	TestStatusSkipped
)

var ErrInvalidTestStatus = errors.New("not a valid TestStatus")

const _TestStatusName = "pendingnot_runrunningpassedfailedskipped"

var _TestStatusMap = map[TestStatus]string{
	TestStatusPending: _TestStatusName[0:7],
	TestStatusNotRun:  _TestStatusName[7:14],
	TestStatusRunning: _TestStatusName[14:21],
	TestStatusPassed:  _TestStatusName[21:27],
	TestStatusFailed:  _TestStatusName[27:33],
	TestStatusSkipped: _TestStatusName[33:40],
}

// String implements the Stringer interface.
func (x TestStatus) String() string {
	if str, ok := _TestStatusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("TestStatus(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TestStatus) IsValid() bool {
	_, ok := _TestStatusMap[x]
	return ok
}

var _TestStatusValue = map[string]TestStatus{
	_TestStatusName[0:7]:   TestStatusPending,
	_TestStatusName[7:14]:  TestStatusNotRun,
	_TestStatusName[14:21]: TestStatusRunning,
	_TestStatusName[21:27]: TestStatusPassed,
	_TestStatusName[27:33]: TestStatusFailed,
	_TestStatusName[33:40]: TestStatusSkipped,
}

// ParseTestStatus attempts to convert a string to a TestStatus.
func ParseTestStatus(name string) (TestStatus, error) {
	if x, ok := _TestStatusValue[name]; ok {
		return x, nil
	}
	return TestStatus(0), fmt.Errorf("%s is %w", name, ErrInvalidTestStatus)
}

// MarshalText implements the text marshaller method.
func (x TestStatus) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *TestStatus) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseTestStatus(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *TestStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
