// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.dit.htwk-leipzig.de/projekt2025-w-llm-unterstuetztes-autotesting-fuer-moderne-web-frontends/smart/internal/suproxy/domain/entity"
)

// NewMockRespondeUpdateService creates a new instance of MockRespondeUpdateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRespondeUpdateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRespondeUpdateService {
	mock := &MockRespondeUpdateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRespondeUpdateService is an autogenerated mock type for the RespondeUpdateService type
type MockRespondeUpdateService struct {
	mock.Mock
}

type MockRespondeUpdateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRespondeUpdateService) EXPECT() *MockRespondeUpdateService_Expecter {
	return &MockRespondeUpdateService_Expecter{mock: &_m.Mock}
}

// UpdateResponse provides a mock function for the type MockRespondeUpdateService
func (_mock *MockRespondeUpdateService) UpdateResponse(ctx context.Context, mockRequest *entity.Request) error {
	ret := _mock.Called(ctx, mockRequest)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResponse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Request) error); ok {
		r0 = returnFunc(ctx, mockRequest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRespondeUpdateService_UpdateResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResponse'
type MockRespondeUpdateService_UpdateResponse_Call struct {
	*mock.Call
}

// UpdateResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - mockRequest *entity.Request
func (_e *MockRespondeUpdateService_Expecter) UpdateResponse(ctx interface{}, mockRequest interface{}) *MockRespondeUpdateService_UpdateResponse_Call {
	return &MockRespondeUpdateService_UpdateResponse_Call{Call: _e.mock.On("UpdateResponse", ctx, mockRequest)}
}

func (_c *MockRespondeUpdateService_UpdateResponse_Call) Run(run func(ctx context.Context, mockRequest *entity.Request)) *MockRespondeUpdateService_UpdateResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Request
		if args[1] != nil {
			arg1 = args[1].(*entity.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRespondeUpdateService_UpdateResponse_Call) Return(err error) *MockRespondeUpdateService_UpdateResponse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRespondeUpdateService_UpdateResponse_Call) RunAndReturn(run func(ctx context.Context, mockRequest *entity.Request) error) *MockRespondeUpdateService_UpdateResponse_Call {
	_c.Call.Return(run)
	return _c
}
