FROM golang:latest AS builder

WORKDIR /app

COPY build/suproxy bin/suproxy

FROM scratch

COPY --from=builder /app/bin/suproxy /bin/suproxy

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENTRYPOINT ["/bin/suproxy"]
