openapi: 3.0.4
info:
  title: Suproxy API
  description: API for suproxy between supplier-d and supplier
  version: 1.0.0
paths:
  /api/v1/request:
    post:
      summary: takes request from supplier-d and returns response from supplier
      operationId: RequestID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/suRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/suResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '422':
          description: Invalid Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    suRequest:
      type: object
      properties:
        header:
          type: string
          example: "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,/;q=0.8"
        prompt:
          type: string
          example: "Schreibe mir einen Test für die Funktionalität Filter für Hotels mit Haustieren erlaubt, ertelle dafür Testdaten"
        source:
          type: string
          example: "storage/ip/..."
        destination:
          type: string
          example: "autotester/ip/..."
        request-message:
          type: string
          example: "request json von supplier-d"
    suResponse:
      type: object
      properties:
        response-message:
          type: string
          example: "response vom Supplier"
    Error:
      type: object
      properties:
        message:
          type: string
          example: "Error"
