openapi: 3.0.4
info:
  title: suproxy - OpenAPI 3.0
  version: 1.0.0
  description:  API for suproxy between supplier-d and supplier
tags:
- name: Offerlist
paths:
  /api/v1/Offerlist:
    post:
      tags:
        - Offerlist
      summary: takes request from supplier-d and returns response from supplier
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OfferlistRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferlistResponse'
        '400':
          description: Invalid Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
            description: Internal server error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    OfferlistRequest:
      type: object
      properties:
        header:
          type: object
          additionalProperties:
            type: string
            example: "text/html,application/xhtml+xml,application/xml;q=0.9,/;q=0.8"
          required: true
        tags:
          type: string
          example: "hotelid ..."
          required: false
        destination:
          type: string
          example: "IP or Hostname"
          required: true
        body:
          type: string
          example: "{\"apimode\":\"live\",\"id\":\"a0950be9-76ad-4fcb-932d-37660d10b1f8\",\"method\":\"search.getOfferList\",\"params\":[{\"airlineslist\":null,\"departureairportlist\":[\"FRA\",\"FKB\",\"LBC\",\"MUC\",\"PAD\",\"BRE\",\"NUE\",\"ERF\",\"KSF\",\"RLG\",\"FDH\",\"HAJ\",\"LEJ\",\"HAM\",\"FMM\",\"DTM\",\"SCN\",\"CGN\",\"HHN\",\"NRN\",\"FMO\",\"BER\",\"STR\",\"DRS\",\"DUS\",\"GWT\"],\"departuredate\":\"2025-07-07\",\"journeyattributelist\":[],\"maxtravelduration\":7,\"mintravelduration\":7,\"objectidlist\":[\"11539\"],\"regionidlist\":null,\"returndate\":\"2025-07-15\",\"rooms\":[{\"id\":1,\"mealtypelist\":[],\"roomattributelist\":[],\"roomtypelist\":[],\"travelerassignment\":[\"a1\",\"a2\"]}],\"sortdirection\":\"asc\",\"sortfield\":\"price\",\"touroperatorlist\":[\"SLR\",\"TUID\",\"ATID\",\"ALL\",\"XTUI\",\"TUR3\",\"TUR1\",\"ITS\",\"JAHN\",\"DER\",\"MWR\",\"ANEX\",\"BU\",\"OGE\",\"NEC\",\"EWHO\",\"BCH\",\"COR\",\"COS\",\"BYE\",\"ETI\",\"TJAL\",\"ALD\"],\"traveldatetype\":\"duration\",\"travelers\":{\"adults\":{\"a1\":36,\"a2\":36},\"children\":[],\"infants\":[]},\"traveltype\":\"package\"}],\"requestSource\":\"pr.offerlist\"}"
          required: true
    OfferlistResponse:
      type: string
      example: "Response JSON from supplier"
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
